apiVersion: iam.nebius.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1beta1/serviceaccount
  labels:
    testing.upbound.io/example-name: terraform
  name: terraform
spec:
  forProvider:
    description: Service account for Terraform automation
    name: terraform-sa
    parentId: project-id
