apiVersion: compute.nebius.m.upbound.io/v1beta1
kind: Filesystem
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/filesystem
  labels:
    testing.upbound.io/example-name: default
  name: default
  namespace: upbound-system
spec:
  forProvider:
    name: computev1filesystem
    parentId: ${data.nebius_project_id}
    sizeGibibytes: 8
    type: NETWORK_SSD
