apiVersion: mk8s.nebius.m.upbound.io/v1beta1
kind: NodeGroup
metadata:
  annotations:
    meta.upbound.io/example-id: mk8s/v1beta1/nodegroup
  labels:
    testing.upbound.io/example-name: mk8s-v1beta1-nodegroup
  name: mk8sv1nodegroup
  namespace: upbound-system
spec:
  forProvider:
    fixedNodeCount: 1
    name: mk8sv1nodegroup
    parentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: mk8s-v1beta1-nodegroup
    template:
      bootDisk:
        sizeGibibytes: 64
        type: NETWORK_SSD
      networkInterfaces:
        - subnetIdSelector:
            matchLabels:
              testing.upbound.io/example-name: mk8s-v1beta1-nodegroup
      resources:
        platform: cpu-d3
        preset: 4vcpu-16gb
    version: "1.36"

---

apiVersion: mk8s.nebius.m.upbound.io/v1beta1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: mk8s/v1beta1/nodegroup
  labels:
    testing.upbound.io/example-name: mk8s-v1beta1-nodegroup
  name: mk8sv1nodegroup
  namespace: upbound-system
spec:
  forProvider:
    controlPlane:
      endpoints:
        publicEndpoint: {}
      etcdClusterSize: 1
      subnetIdSelector:
        matchLabels:
          testing.upbound.io/example-name: mk8s-v1beta1-nodegroup
      version: "1.36"
    name: mk8sv1nodegroup
    parentId: ${data.nebius_project_id}

---

apiVersion: vpc.nebius.m.upbound.io/v1beta1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: mk8s/v1beta1/nodegroup
  labels:
    testing.upbound.io/example-name: mk8s-v1beta1-nodegroup
  name: mk8sv1nodegroup
  namespace: upbound-system
spec:
  forProvider:
    ipv4PrivatePools:
      useNetworkPools: true
    name: mk8sv1nodegroup
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: mk8s-v1beta1-nodegroup
    parentId: ${data.nebius_project_id}

---

apiVersion: vpc.nebius.m.upbound.io/v1beta1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: mk8s/v1beta1/nodegroup
  labels:
    testing.upbound.io/example-name: mk8s-v1beta1-nodegroup
  name: mk8sv1nodegroup
  namespace: upbound-system
spec:
  forProvider:
    name: mk8sv1nodegroup
    parentId: ${data.nebius_project_id}
