apiVersion: iam.nebius.m.upbound.io/v1beta1
kind: AuthPublicKey
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1beta1/authpublickey
  labels:
    testing.upbound.io/example-name: terraform
  name: terraform
  namespace: upbound-system
spec:
  forProvider:
    account:
      serviceAccount:
        idSelector:
          matchLabels:
            testing.upbound.io/example-name: terraform
    dataSecretRef:
      key: attribute.public.pem
      name: example-secret
    name: terraform-auth-key
    parentId: project-id

---

apiVersion: iam.nebius.m.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1beta1/authpublickey
  labels:
    testing.upbound.io/example-name: terraform
  name: terraform
  namespace: upbound-system
spec:
  forProvider:
    name: terraform-sa
    parentId: project-id
