// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ComputeInstanceSpecInitParameters struct {
	V1 *V1InitParameters `json:"v1,omitempty" tf:"v1,omitempty"`
}

type ComputeInstanceSpecObservation struct {
	V1 *V1Observation `json:"v1,omitempty" tf:"v1,omitempty"`
}

type ComputeInstanceSpecParameters struct {

	// +kubebuilder:validation:Optional
	V1 *V1Parameters `json:"v1,omitempty" tf:"v1,omitempty"`
}

type MaxPriceV1InitParameters struct {

	// :
	//
	// Per-GPU hourly limit in USD, decimal string 3 digits precision. Example: "3.515".
	// Must be within the allowed price range (OUT_OF_RANGE otherwise);
	// a value below the current market price is accepted but blocks scheduling.
	// Mutable only while `status.running_vm_count` is 0
	// (FAILED_PRECONDITION otherwise); the policy reports STATE_UPDATING and
	// blocks scheduling while the change is applied.
	MaxPrice *string `json:"maxPrice,omitempty" tf:"max_price,omitempty"`
}

type MaxPriceV1Observation struct {

	// :
	//
	// Per-GPU hourly limit in USD, decimal string 3 digits precision. Example: "3.515".
	// Must be within the allowed price range (OUT_OF_RANGE otherwise);
	// a value below the current market price is accepted but blocks scheduling.
	// Mutable only while `status.running_vm_count` is 0
	// (FAILED_PRECONDITION otherwise); the policy reports STATE_UPDATING and
	// blocks scheduling while the change is applied.
	MaxPrice *string `json:"maxPrice,omitempty" tf:"max_price,omitempty"`
}

type MaxPriceV1Parameters struct {

	// :
	//
	// Per-GPU hourly limit in USD, decimal string 3 digits precision. Example: "3.515".
	// Must be within the allowed price range (OUT_OF_RANGE otherwise);
	// a value below the current market price is accepted but blocks scheduling.
	// Mutable only while `status.running_vm_count` is 0
	// (FAILED_PRECONDITION otherwise); the policy reports STATE_UPDATING and
	// blocks scheduling while the change is applied.
	// +kubebuilder:validation:Optional
	MaxPrice *string `json:"maxPrice" tf:"max_price,omitempty"`
}

type MetadataInitParameters struct {
}

type MetadataObservation struct {
}

type MetadataParameters struct {
}

type PricingInitParameters struct {
	MaxPriceV1 *MaxPriceV1InitParameters `json:"maxPriceV1,omitempty" tf:"max_price_v1,omitempty"`
}

type PricingObservation struct {
	MaxPriceV1 *MaxPriceV1Observation `json:"maxPriceV1,omitempty" tf:"max_price_v1,omitempty"`
}

type PricingParameters struct {

	// +kubebuilder:validation:Optional
	MaxPriceV1 *MaxPriceV1Parameters `json:"maxPriceV1,omitempty" tf:"max_price_v1,omitempty"`
}

type PricingPolicyInitParameters struct {
	ComputeInstanceSpec *ComputeInstanceSpecInitParameters `json:"computeInstanceSpec,omitempty" tf:"compute_instance_spec,omitempty"`

	// Labels associated with the resource.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	Metadata *MetadataInitParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// Human readable name for the resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Identifier of the parent resource to which the resource belongs.
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	Pricing *PricingInitParameters `json:"pricing,omitempty" tf:"pricing,omitempty"`
}

type PricingPolicyObservation struct {
	ComputeInstanceSpec *ComputeInstanceSpecObservation `json:"computeInstanceSpec,omitempty" tf:"compute_instance_spec,omitempty"`

	// :
	//
	// Timestamp indicating when the resource was created.
	//
	// A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Labels associated with the resource.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Effective labels sent to the API after merging provider `default_labels` with resource `labels`.
	// +mapType=granular
	LabelsAll map[string]*string `json:"labelsAll,omitempty" tf:"labels_all,omitempty"`

	Metadata *MetadataParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// Human readable name for the resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Identifier of the parent resource to which the resource belongs.
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	Pricing *PricingObservation `json:"pricing,omitempty" tf:"pricing,omitempty"`

	// :
	//
	// Version of the resource for safe concurrent modifications and consistent reads.
	// Positive and monotonically increases on each resource spec change (but *not* on each change of the
	// resource's container(s) or status).
	// Service allows zero value or current.
	ResourceVersion *float64 `json:"resourceVersion,omitempty" tf:"resource_version,omitempty"`

	Status *StatusObservation `json:"status,omitempty" tf:"status,omitempty"`

	// :
	//
	// Timestamp indicating when the resource was last updated.
	//
	// A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type PricingPolicyParameters struct {

	// +kubebuilder:validation:Optional
	ComputeInstanceSpec *ComputeInstanceSpecParameters `json:"computeInstanceSpec,omitempty" tf:"compute_instance_spec,omitempty"`

	// Labels associated with the resource.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// +kubebuilder:validation:Optional
	Metadata *MetadataParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// Human readable name for the resource.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Identifier of the parent resource to which the resource belongs.
	// +kubebuilder:validation:Optional
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// +kubebuilder:validation:Optional
	Pricing *PricingParameters `json:"pricing,omitempty" tf:"pricing,omitempty"`
}

type StatusInitParameters struct {
}

type StatusObservation struct {

	// ISO 4217 currency code of max_price, e.g. "USD".
	Currency *string `json:"currency,omitempty" tf:"currency,omitempty"`

	// :
	//
	// Number of VMs currently running under this policy. Nonzero blocks resource
	// changes and deletion.
	RunningVMCount *float64 `json:"runningVmCount,omitempty" tf:"running_vm_count,omitempty"`

	// :
	//
	// Whether new VMs may currently start under this policy.
	//
	// #### Supported values
	//
	// Possible values:
	//
	// - `SCHEDULING_STATE_UNSPECIFIED`
	// - `SCHEDULING_STATE_ALLOWED` - New VMs may start.
	// - `SCHEDULING_STATE_BLOCKED`:
	// The max_price limit is below the market price in force or below a market price
	// that is being applied; VM creation succeeds once the price falls to it.
	SchedulingState *string `json:"schedulingState,omitempty" tf:"scheduling_state,omitempty"`

	// SKU resolved from the spec.
	SkuID *string `json:"skuId,omitempty" tf:"sku_id,omitempty"`

	// :
	//
	// #### Supported values
	//
	// Possible values:
	//
	// - `STATE_UNSPECIFIED`
	// - `STATE_CREATING`:
	// Not ready yet; a VM referencing the policy gets a retryable error.
	// The state can last while a market price change is applied to the segment.
	//
	// - `STATE_ACTIVE` - Ready; whether VMs may start is `scheduling_state`.
	// - `STATE_DELETING` - Being deleted; does not accept new VMs.
	// - `STATE_UPDATING`:
	// The bid is being changed; scheduling is blocked until the change lands.
	// The state can last while a market price change is applied to the segment.
	State *string `json:"state,omitempty" tf:"state,omitempty"`
}

type StatusParameters struct {
}

type V1InitParameters struct {

	// Compute platform. Example: "gpu-h100-sxm".
	Platform *string `json:"platform,omitempty" tf:"platform,omitempty"`
}

type V1Observation struct {

	// Compute platform. Example: "gpu-h100-sxm".
	Platform *string `json:"platform,omitempty" tf:"platform,omitempty"`
}

type V1Parameters struct {

	// Compute platform. Example: "gpu-h100-sxm".
	// +kubebuilder:validation:Optional
	Platform *string `json:"platform" tf:"platform,omitempty"`
}

// PricingPolicySpec defines the desired state of PricingPolicy
type PricingPolicySpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            PricingPolicyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PricingPolicyInitParameters `json:"initProvider,omitempty"`
}

// PricingPolicyStatus defines the observed state of PricingPolicy.
type PricingPolicyStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               PricingPolicyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// PricingPolicy is the Schema for the PricingPolicys API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,nebius}
type PricingPolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.computeInstanceSpec) || (has(self.initProvider) && has(self.initProvider.computeInstanceSpec))",message="spec.forProvider.computeInstanceSpec is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.pricing) || (has(self.initProvider) && has(self.initProvider.pricing))",message="spec.forProvider.pricing is a required parameter"
	Spec   PricingPolicySpec   `json:"spec"`
	Status PricingPolicyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PricingPolicyList contains a list of PricingPolicys
type PricingPolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PricingPolicy `json:"items"`
}

// Repository type metadata.
var (
	PricingPolicy_Kind             = "PricingPolicy"
	PricingPolicy_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PricingPolicy_Kind}.String()
	PricingPolicy_KindAPIVersion   = PricingPolicy_Kind + "." + CRDGroupVersion.String()
	PricingPolicy_GroupVersionKind = CRDGroupVersion.WithKind(PricingPolicy_Kind)
)

func init() {
	SchemeBuilder.Register(&PricingPolicy{}, &PricingPolicyList{})
}
