// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type IPv4PrivatePoolsPoolsInitParameters struct {

	// (Attributes List) (see below for nested schema)
	Cidrs []PoolsCidrsInitParameters `json:"cidrs,omitempty" tf:"cidrs,omitempty"`
}

type IPv4PrivatePoolsPoolsObservation struct {

	// (Attributes List) (see below for nested schema)
	Cidrs []PoolsCidrsObservation `json:"cidrs,omitempty" tf:"cidrs,omitempty"`
}

type IPv4PrivatePoolsPoolsParameters struct {

	// (Attributes List) (see below for nested schema)
	// +kubebuilder:validation:Optional
	Cidrs []PoolsCidrsParameters `json:"cidrs,omitempty" tf:"cidrs,omitempty"`
}

type IPv4PublicPoolsPoolsCidrsInitParameters struct {

	// (String) :
	// :
	//
	// A CIDR block (e.g., "10.1.2.0/24") or a prefix length (e.g., "/24").
	// If prefix length is specified, the CIDR block will be auto-allocated
	// from the network's available space.
	Cidr *string `json:"cidr,omitempty" tf:"cidr,omitempty"`

	// (Number) Maximum mask length for an allocation from this block. Defaults to /32 for IPv4.
	// Maximum mask length for an allocation from this block. Defaults to /32 for IPv4.
	MaxMaskLength *float64 `json:"maxMaskLength,omitempty" tf:"max_mask_length,omitempty"`

	// (String) :
	// :
	//
	// Controls provisioning of IP addresses from the CIDR block. Defaults to AVAILABLE.
	//
	// #### Supported values
	//
	// Controls provisioning of IP addresses from this pool to other pools
	// or allocations. Defaults to AVAILABLE.
	// Possible values:
	//
	// - `STATE_UNSPECIFIED` - Not used, mandated by the protocol.
	// - `AVAILABLE` - Default state. Provision of the IP addresses from this CIDR block is allowed.
	// - `DISABLED` - Provision of the IP addresses from this CIDR block is denied.
	State *string `json:"state,omitempty" tf:"state,omitempty"`
}

type IPv4PublicPoolsPoolsCidrsObservation struct {

	// (String) :
	// :
	//
	// A CIDR block (e.g., "10.1.2.0/24") or a prefix length (e.g., "/24").
	// If prefix length is specified, the CIDR block will be auto-allocated
	// from the network's available space.
	Cidr *string `json:"cidr,omitempty" tf:"cidr,omitempty"`

	// (Number) Maximum mask length for an allocation from this block. Defaults to /32 for IPv4.
	// Maximum mask length for an allocation from this block. Defaults to /32 for IPv4.
	MaxMaskLength *float64 `json:"maxMaskLength,omitempty" tf:"max_mask_length,omitempty"`

	// (String) :
	// :
	//
	// Controls provisioning of IP addresses from the CIDR block. Defaults to AVAILABLE.
	//
	// #### Supported values
	//
	// Controls provisioning of IP addresses from this pool to other pools
	// or allocations. Defaults to AVAILABLE.
	// Possible values:
	//
	// - `STATE_UNSPECIFIED` - Not used, mandated by the protocol.
	// - `AVAILABLE` - Default state. Provision of the IP addresses from this CIDR block is allowed.
	// - `DISABLED` - Provision of the IP addresses from this CIDR block is denied.
	State *string `json:"state,omitempty" tf:"state,omitempty"`
}

type IPv4PublicPoolsPoolsCidrsParameters struct {

	// (String) :
	// :
	//
	// A CIDR block (e.g., "10.1.2.0/24") or a prefix length (e.g., "/24").
	// If prefix length is specified, the CIDR block will be auto-allocated
	// from the network's available space.
	// +kubebuilder:validation:Optional
	Cidr *string `json:"cidr,omitempty" tf:"cidr,omitempty"`

	// (Number) Maximum mask length for an allocation from this block. Defaults to /32 for IPv4.
	// Maximum mask length for an allocation from this block. Defaults to /32 for IPv4.
	// +kubebuilder:validation:Optional
	MaxMaskLength *float64 `json:"maxMaskLength,omitempty" tf:"max_mask_length,omitempty"`

	// (String) :
	// :
	//
	// Controls provisioning of IP addresses from the CIDR block. Defaults to AVAILABLE.
	//
	// #### Supported values
	//
	// Controls provisioning of IP addresses from this pool to other pools
	// or allocations. Defaults to AVAILABLE.
	// Possible values:
	//
	// - `STATE_UNSPECIFIED` - Not used, mandated by the protocol.
	// - `AVAILABLE` - Default state. Provision of the IP addresses from this CIDR block is allowed.
	// - `DISABLED` - Provision of the IP addresses from this CIDR block is denied.
	// +kubebuilder:validation:Optional
	State *string `json:"state,omitempty" tf:"state,omitempty"`
}

type PoolsCidrsInitParameters struct {

	// (String) :
	// :
	//
	// A CIDR block (e.g., "10.1.2.0/24") or a prefix length (e.g., "/24").
	// If prefix length is specified, the CIDR block will be auto-allocated
	// from the network's available space.
	Cidr *string `json:"cidr,omitempty" tf:"cidr,omitempty"`

	// (Number) Maximum mask length for an allocation from this block. Defaults to /32 for IPv4.
	// Maximum mask length for an allocation from this block. Defaults to /32 for IPv4.
	MaxMaskLength *float64 `json:"maxMaskLength,omitempty" tf:"max_mask_length,omitempty"`

	// (String) :
	// :
	//
	// Controls provisioning of IP addresses from the CIDR block. Defaults to AVAILABLE.
	//
	// #### Supported values
	//
	// Controls provisioning of IP addresses from this pool to other pools
	// or allocations. Defaults to AVAILABLE.
	// Possible values:
	//
	// - `STATE_UNSPECIFIED` - Not used, mandated by the protocol.
	// - `AVAILABLE` - Default state. Provision of the IP addresses from this CIDR block is allowed.
	// - `DISABLED` - Provision of the IP addresses from this CIDR block is denied.
	State *string `json:"state,omitempty" tf:"state,omitempty"`
}

type PoolsCidrsObservation struct {

	// (String) :
	// :
	//
	// A CIDR block (e.g., "10.1.2.0/24") or a prefix length (e.g., "/24").
	// If prefix length is specified, the CIDR block will be auto-allocated
	// from the network's available space.
	Cidr *string `json:"cidr,omitempty" tf:"cidr,omitempty"`

	// (Number) Maximum mask length for an allocation from this block. Defaults to /32 for IPv4.
	// Maximum mask length for an allocation from this block. Defaults to /32 for IPv4.
	MaxMaskLength *float64 `json:"maxMaskLength,omitempty" tf:"max_mask_length,omitempty"`

	// (String) :
	// :
	//
	// Controls provisioning of IP addresses from the CIDR block. Defaults to AVAILABLE.
	//
	// #### Supported values
	//
	// Controls provisioning of IP addresses from this pool to other pools
	// or allocations. Defaults to AVAILABLE.
	// Possible values:
	//
	// - `STATE_UNSPECIFIED` - Not used, mandated by the protocol.
	// - `AVAILABLE` - Default state. Provision of the IP addresses from this CIDR block is allowed.
	// - `DISABLED` - Provision of the IP addresses from this CIDR block is denied.
	State *string `json:"state,omitempty" tf:"state,omitempty"`
}

type PoolsCidrsParameters struct {

	// (String) :
	// :
	//
	// A CIDR block (e.g., "10.1.2.0/24") or a prefix length (e.g., "/24").
	// If prefix length is specified, the CIDR block will be auto-allocated
	// from the network's available space.
	// +kubebuilder:validation:Optional
	Cidr *string `json:"cidr,omitempty" tf:"cidr,omitempty"`

	// (Number) Maximum mask length for an allocation from this block. Defaults to /32 for IPv4.
	// Maximum mask length for an allocation from this block. Defaults to /32 for IPv4.
	// +kubebuilder:validation:Optional
	MaxMaskLength *float64 `json:"maxMaskLength,omitempty" tf:"max_mask_length,omitempty"`

	// (String) :
	// :
	//
	// Controls provisioning of IP addresses from the CIDR block. Defaults to AVAILABLE.
	//
	// #### Supported values
	//
	// Controls provisioning of IP addresses from this pool to other pools
	// or allocations. Defaults to AVAILABLE.
	// Possible values:
	//
	// - `STATE_UNSPECIFIED` - Not used, mandated by the protocol.
	// - `AVAILABLE` - Default state. Provision of the IP addresses from this CIDR block is allowed.
	// - `DISABLED` - Provision of the IP addresses from this CIDR block is denied.
	// +kubebuilder:validation:Optional
	State *string `json:"state,omitempty" tf:"state,omitempty"`
}

type StatusRouteTableInitParameters struct {
}

type StatusRouteTableObservation struct {

	// (Boolean) :
	// :
	//
	// Indicates whether this is the network's default route table.
	// If true, this is the default route table inherited from the network.
	// If false, this is a custom route table explicitly associated with the subnet via spec.
	Default *bool `json:"default,omitempty" tf:"default,omitempty"`

	// (String) Identifier for the resource, unique for its resource type.
	// ID of the route table.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type StatusRouteTableParameters struct {
}

type SubnetIPv4PrivatePoolsInitParameters struct {

	// (Attributes List) :
	Pools []IPv4PrivatePoolsPoolsInitParameters `json:"pools,omitempty" tf:"pools,omitempty"`

	// is true. (see below for nested schema)
	// :
	//
	// If true, inherit private IPv4 pools from the network. Defaults to true.
	// Must be false if `pools` is specified.
	UseNetworkPools *bool `json:"useNetworkPools,omitempty" tf:"use_network_pools,omitempty"`
}

type SubnetIPv4PrivatePoolsObservation struct {

	// (Attributes List) :
	Pools []IPv4PrivatePoolsPoolsObservation `json:"pools,omitempty" tf:"pools,omitempty"`

	// is true. (see below for nested schema)
	// :
	//
	// If true, inherit private IPv4 pools from the network. Defaults to true.
	// Must be false if `pools` is specified.
	UseNetworkPools *bool `json:"useNetworkPools,omitempty" tf:"use_network_pools,omitempty"`
}

type SubnetIPv4PrivatePoolsParameters struct {

	// (Attributes List) :
	// +kubebuilder:validation:Optional
	Pools []IPv4PrivatePoolsPoolsParameters `json:"pools,omitempty" tf:"pools,omitempty"`

	// is true. (see below for nested schema)
	// :
	//
	// If true, inherit private IPv4 pools from the network. Defaults to true.
	// Must be false if `pools` is specified.
	// +kubebuilder:validation:Optional
	UseNetworkPools *bool `json:"useNetworkPools,omitempty" tf:"use_network_pools,omitempty"`
}

type SubnetIPv4PublicPoolsInitParameters struct {

	// (Attributes List) :
	Pools []SubnetIPv4PublicPoolsPoolsInitParameters `json:"pools,omitempty" tf:"pools,omitempty"`

	// is true. (see below for nested schema)
	// :
	//
	// If true, inherit public IPv4 pools from the network.
	// Must be false if `pools` is specified.
	UseNetworkPools *bool `json:"useNetworkPools,omitempty" tf:"use_network_pools,omitempty"`
}

type SubnetIPv4PublicPoolsObservation struct {

	// (Attributes List) :
	Pools []SubnetIPv4PublicPoolsPoolsObservation `json:"pools,omitempty" tf:"pools,omitempty"`

	// is true. (see below for nested schema)
	// :
	//
	// If true, inherit public IPv4 pools from the network.
	// Must be false if `pools` is specified.
	UseNetworkPools *bool `json:"useNetworkPools,omitempty" tf:"use_network_pools,omitempty"`
}

type SubnetIPv4PublicPoolsParameters struct {

	// (Attributes List) :
	// +kubebuilder:validation:Optional
	Pools []SubnetIPv4PublicPoolsPoolsParameters `json:"pools,omitempty" tf:"pools,omitempty"`

	// is true. (see below for nested schema)
	// :
	//
	// If true, inherit public IPv4 pools from the network.
	// Must be false if `pools` is specified.
	// +kubebuilder:validation:Optional
	UseNetworkPools *bool `json:"useNetworkPools,omitempty" tf:"use_network_pools,omitempty"`
}

type SubnetIPv4PublicPoolsPoolsInitParameters struct {

	// (Attributes List) (see below for nested schema)
	Cidrs []IPv4PublicPoolsPoolsCidrsInitParameters `json:"cidrs,omitempty" tf:"cidrs,omitempty"`
}

type SubnetIPv4PublicPoolsPoolsObservation struct {

	// (Attributes List) (see below for nested schema)
	Cidrs []IPv4PublicPoolsPoolsCidrsObservation `json:"cidrs,omitempty" tf:"cidrs,omitempty"`
}

type SubnetIPv4PublicPoolsPoolsParameters struct {

	// (Attributes List) (see below for nested schema)
	// +kubebuilder:validation:Optional
	Cidrs []IPv4PublicPoolsPoolsCidrsParameters `json:"cidrs,omitempty" tf:"cidrs,omitempty"`
}

type SubnetInitParameters struct {

	// (Attributes) :
	IPv4PrivatePools *SubnetIPv4PrivatePoolsInitParameters `json:"ipv4PrivatePools,omitempty" tf:"ipv4_private_pools,omitempty"`

	// (Attributes) :
	IPv4PublicPools *SubnetIPv4PublicPoolsInitParameters `json:"ipv4PublicPools,omitempty" tf:"ipv4_public_pools,omitempty"`

	// (Map of String) :
	// :
	//
	// Labels associated with the resource.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (Attributes) :
	Metadata *SubnetMetadataInitParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// (String) Human readable name for the resource.
	// Human readable name for the resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) ID of the network this subnet belongs to.
	// ID of the network this subnet belongs to.
	// +crossplane:generate:reference:type=github.com/upbound/provider-nebius/apis/namespaced/vpcv1/v1beta1.Network
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id",true)
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// Reference to a Network in vpcv1 to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDRef *v1.NamespacedReference `json:"networkIdRef,omitempty" tf:"-"`

	// Selector for a Network in vpcv1 to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDSelector *v1.NamespacedSelector `json:"networkIdSelector,omitempty" tf:"-"`

	// (String) Identifier of the parent resource to which the resource belongs.
	// Identifier of the parent resource to which the resource belongs.
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// (String) :
	// :
	//
	// ID of the route table to associate with the subnet.
	// If unspecified, the network's default route table is used.
	// +crossplane:generate:reference:type=github.com/upbound/provider-nebius/apis/namespaced/vpcv1/v1beta1.RouteTable
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id",true)
	RouteTableID *string `json:"routeTableId,omitempty" tf:"route_table_id,omitempty"`

	// Reference to a RouteTable in vpcv1 to populate routeTableId.
	// +kubebuilder:validation:Optional
	RouteTableIDRef *v1.NamespacedReference `json:"routeTableIdRef,omitempty" tf:"-"`

	// Selector for a RouteTable in vpcv1 to populate routeTableId.
	// +kubebuilder:validation:Optional
	RouteTableIDSelector *v1.NamespacedSelector `json:"routeTableIdSelector,omitempty" tf:"-"`
}

type SubnetMetadataInitParameters struct {
}

type SubnetMetadataObservation struct {
}

type SubnetMetadataParameters struct {
}

type SubnetObservation struct {

	// (String) :
	// :
	//
	// Timestamp indicating when the resource was created.
	//
	// A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String) Identifier for the resource, unique for its resource type.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Attributes) :
	IPv4PrivatePools *SubnetIPv4PrivatePoolsObservation `json:"ipv4PrivatePools,omitempty" tf:"ipv4_private_pools,omitempty"`

	// (Attributes) :
	IPv4PublicPools *SubnetIPv4PublicPoolsObservation `json:"ipv4PublicPools,omitempty" tf:"ipv4_public_pools,omitempty"`

	// (Map of String) :
	// :
	//
	// Labels associated with the resource.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (Attributes) :
	Metadata *SubnetMetadataParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// (String) Human readable name for the resource.
	// Human readable name for the resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) ID of the network this subnet belongs to.
	// ID of the network this subnet belongs to.
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// (String) Identifier of the parent resource to which the resource belongs.
	// Identifier of the parent resource to which the resource belongs.
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// (Number) :
	// :
	//
	// Version of the resource for safe concurrent modifications and consistent reads.
	// Positive and monotonically increases on each resource spec change (but *not* on each change of the
	// resource's container(s) or status).
	// Service allows zero value or current.
	ResourceVersion *float64 `json:"resourceVersion,omitempty" tf:"resource_version,omitempty"`

	// (String) :
	// :
	//
	// ID of the route table to associate with the subnet.
	// If unspecified, the network's default route table is used.
	RouteTableID *string `json:"routeTableId,omitempty" tf:"route_table_id,omitempty"`

	// (Attributes) Status of the subnet. (see below for nested schema)
	Status *SubnetStatusObservation `json:"status,omitempty" tf:"status,omitempty"`

	// (String) :
	// :
	//
	// Timestamp indicating when the resource was last updated.
	//
	// A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type SubnetParameters struct {

	// (Attributes) :
	// +kubebuilder:validation:Optional
	IPv4PrivatePools *SubnetIPv4PrivatePoolsParameters `json:"ipv4PrivatePools,omitempty" tf:"ipv4_private_pools,omitempty"`

	// (Attributes) :
	// +kubebuilder:validation:Optional
	IPv4PublicPools *SubnetIPv4PublicPoolsParameters `json:"ipv4PublicPools,omitempty" tf:"ipv4_public_pools,omitempty"`

	// (Map of String) :
	// :
	//
	// Labels associated with the resource.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (Attributes) :
	// +kubebuilder:validation:Optional
	Metadata *SubnetMetadataParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// (String) Human readable name for the resource.
	// Human readable name for the resource.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) ID of the network this subnet belongs to.
	// ID of the network this subnet belongs to.
	// +crossplane:generate:reference:type=github.com/upbound/provider-nebius/apis/namespaced/vpcv1/v1beta1.Network
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id",true)
	// +kubebuilder:validation:Optional
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// Reference to a Network in vpcv1 to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDRef *v1.NamespacedReference `json:"networkIdRef,omitempty" tf:"-"`

	// Selector for a Network in vpcv1 to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDSelector *v1.NamespacedSelector `json:"networkIdSelector,omitempty" tf:"-"`

	// (String) Identifier of the parent resource to which the resource belongs.
	// Identifier of the parent resource to which the resource belongs.
	// +kubebuilder:validation:Optional
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// (String) :
	// :
	//
	// ID of the route table to associate with the subnet.
	// If unspecified, the network's default route table is used.
	// +crossplane:generate:reference:type=github.com/upbound/provider-nebius/apis/namespaced/vpcv1/v1beta1.RouteTable
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id",true)
	// +kubebuilder:validation:Optional
	RouteTableID *string `json:"routeTableId,omitempty" tf:"route_table_id,omitempty"`

	// Reference to a RouteTable in vpcv1 to populate routeTableId.
	// +kubebuilder:validation:Optional
	RouteTableIDRef *v1.NamespacedReference `json:"routeTableIdRef,omitempty" tf:"-"`

	// Selector for a RouteTable in vpcv1 to populate routeTableId.
	// +kubebuilder:validation:Optional
	RouteTableIDSelector *v1.NamespacedSelector `json:"routeTableIdSelector,omitempty" tf:"-"`
}

type SubnetStatusInitParameters struct {
}

type SubnetStatusObservation struct {

	// (List of String) CIDR blocks.
	// CIDR blocks.
	IPv4PrivateCidrs []*string `json:"ipv4PrivateCidrs,omitempty" tf:"ipv4_private_cidrs,omitempty"`

	// (List of String) CIDR blocks.
	// CIDR blocks.
	IPv4PublicCidrs []*string `json:"ipv4PublicCidrs,omitempty" tf:"ipv4_public_cidrs,omitempty"`

	// (Attributes) :
	RouteTable *StatusRouteTableObservation `json:"routeTable,omitempty" tf:"route_table,omitempty"`

	// (String) :
	// :
	//
	// Current state of the subnet.
	//
	// #### Supported values
	//
	// Enumeration of possible states of the subnet.
	// Possible values:
	//
	// - `STATE_UNSPECIFIED` - Default state, unspecified.
	// - `CREATING` - Subnet is being created.
	// - `READY` - Subnet is ready for use.
	// - `DELETING` - Subnet is being deleted.
	State *string `json:"state,omitempty" tf:"state,omitempty"`
}

type SubnetStatusParameters struct {
}

// SubnetSpec defines the desired state of Subnet
type SubnetSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            SubnetParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SubnetInitParameters `json:"initProvider,omitempty"`
}

// SubnetStatus defines the observed state of Subnet.
type SubnetStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SubnetObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Subnet is the Schema for the Subnets API. Defines a Subnet, a segment of a network used for more granular control and management. Subnet uses pools to organize address space.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,nebius}
type Subnet struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.parentId) || (has(self.initProvider) && has(self.initProvider.parentId))",message="spec.forProvider.parentId is a required parameter"
	Spec   SubnetSpec   `json:"spec"`
	Status SubnetStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SubnetList contains a list of Subnets
type SubnetList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Subnet `json:"items"`
}

// Repository type metadata.
var (
	Subnet_Kind             = "Subnet"
	Subnet_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Subnet_Kind}.String()
	Subnet_KindAPIVersion   = Subnet_Kind + "." + CRDGroupVersion.String()
	Subnet_GroupVersionKind = CRDGroupVersion.WithKind(Subnet_Kind)
)

func init() {
	SchemeBuilder.Register(&Subnet{}, &SubnetList{})
}
