// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1beta1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Allocation.
func (mg *Allocation) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	if mg.Spec.ForProvider.IPv4Private != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.IPv4Private.PoolID),
			Extract:      resource.ExtractParamPath("id", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.IPv4Private.PoolIDRef,
			Selector:     mg.Spec.ForProvider.IPv4Private.PoolIDSelector,
			To: reference.To{
				List:    &PoolList{},
				Managed: &Pool{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.IPv4Private.PoolID")
		}
		mg.Spec.ForProvider.IPv4Private.PoolID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.IPv4Private.PoolIDRef = rsp.ResolvedReference

	}
	if mg.Spec.ForProvider.IPv4Private != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.IPv4Private.SubnetID),
			Extract:      resource.ExtractParamPath("id", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.IPv4Private.SubnetIDRef,
			Selector:     mg.Spec.ForProvider.IPv4Private.SubnetIDSelector,
			To: reference.To{
				List:    &SubnetList{},
				Managed: &Subnet{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.IPv4Private.SubnetID")
		}
		mg.Spec.ForProvider.IPv4Private.SubnetID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.IPv4Private.SubnetIDRef = rsp.ResolvedReference

	}
	if mg.Spec.ForProvider.IPv4Public != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.IPv4Public.PoolID),
			Extract:      resource.ExtractParamPath("id", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.IPv4Public.PoolIDRef,
			Selector:     mg.Spec.ForProvider.IPv4Public.PoolIDSelector,
			To: reference.To{
				List:    &PoolList{},
				Managed: &Pool{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.IPv4Public.PoolID")
		}
		mg.Spec.ForProvider.IPv4Public.PoolID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.IPv4Public.PoolIDRef = rsp.ResolvedReference

	}
	if mg.Spec.ForProvider.IPv4Public != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.IPv4Public.SubnetID),
			Extract:      resource.ExtractParamPath("id", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.IPv4Public.SubnetIDRef,
			Selector:     mg.Spec.ForProvider.IPv4Public.SubnetIDSelector,
			To: reference.To{
				List:    &SubnetList{},
				Managed: &Subnet{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.IPv4Public.SubnetID")
		}
		mg.Spec.ForProvider.IPv4Public.SubnetID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.IPv4Public.SubnetIDRef = rsp.ResolvedReference

	}
	if mg.Spec.InitProvider.IPv4Private != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.IPv4Private.PoolID),
			Extract:      resource.ExtractParamPath("id", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.IPv4Private.PoolIDRef,
			Selector:     mg.Spec.InitProvider.IPv4Private.PoolIDSelector,
			To: reference.To{
				List:    &PoolList{},
				Managed: &Pool{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.IPv4Private.PoolID")
		}
		mg.Spec.InitProvider.IPv4Private.PoolID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.IPv4Private.PoolIDRef = rsp.ResolvedReference

	}
	if mg.Spec.InitProvider.IPv4Private != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.IPv4Private.SubnetID),
			Extract:      resource.ExtractParamPath("id", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.IPv4Private.SubnetIDRef,
			Selector:     mg.Spec.InitProvider.IPv4Private.SubnetIDSelector,
			To: reference.To{
				List:    &SubnetList{},
				Managed: &Subnet{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.IPv4Private.SubnetID")
		}
		mg.Spec.InitProvider.IPv4Private.SubnetID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.IPv4Private.SubnetIDRef = rsp.ResolvedReference

	}
	if mg.Spec.InitProvider.IPv4Public != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.IPv4Public.PoolID),
			Extract:      resource.ExtractParamPath("id", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.IPv4Public.PoolIDRef,
			Selector:     mg.Spec.InitProvider.IPv4Public.PoolIDSelector,
			To: reference.To{
				List:    &PoolList{},
				Managed: &Pool{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.IPv4Public.PoolID")
		}
		mg.Spec.InitProvider.IPv4Public.PoolID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.IPv4Public.PoolIDRef = rsp.ResolvedReference

	}
	if mg.Spec.InitProvider.IPv4Public != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.IPv4Public.SubnetID),
			Extract:      resource.ExtractParamPath("id", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.IPv4Public.SubnetIDRef,
			Selector:     mg.Spec.InitProvider.IPv4Public.SubnetIDSelector,
			To: reference.To{
				List:    &SubnetList{},
				Managed: &Subnet{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.IPv4Public.SubnetID")
		}
		mg.Spec.InitProvider.IPv4Public.SubnetID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.IPv4Public.SubnetIDRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this Network.
func (mg *Network) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	if mg.Spec.ForProvider.IPv4PrivatePools != nil {
		for i4 := 0; i4 < len(mg.Spec.ForProvider.IPv4PrivatePools.Pools); i4++ {
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.IPv4PrivatePools.Pools[i4].ID),
				Extract:      resource.ExtractParamPath("id", true),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.IPv4PrivatePools.Pools[i4].IDRef,
				Selector:     mg.Spec.ForProvider.IPv4PrivatePools.Pools[i4].IDSelector,
				To: reference.To{
					List:    &PoolList{},
					Managed: &Pool{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.IPv4PrivatePools.Pools[i4].ID")
			}
			mg.Spec.ForProvider.IPv4PrivatePools.Pools[i4].ID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.IPv4PrivatePools.Pools[i4].IDRef = rsp.ResolvedReference

		}
	}
	if mg.Spec.ForProvider.IPv4PublicPools != nil {
		for i4 := 0; i4 < len(mg.Spec.ForProvider.IPv4PublicPools.Pools); i4++ {
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.IPv4PublicPools.Pools[i4].ID),
				Extract:      resource.ExtractParamPath("id", true),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.IPv4PublicPools.Pools[i4].IDRef,
				Selector:     mg.Spec.ForProvider.IPv4PublicPools.Pools[i4].IDSelector,
				To: reference.To{
					List:    &PoolList{},
					Managed: &Pool{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.IPv4PublicPools.Pools[i4].ID")
			}
			mg.Spec.ForProvider.IPv4PublicPools.Pools[i4].ID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.IPv4PublicPools.Pools[i4].IDRef = rsp.ResolvedReference

		}
	}
	if mg.Spec.InitProvider.IPv4PrivatePools != nil {
		for i4 := 0; i4 < len(mg.Spec.InitProvider.IPv4PrivatePools.Pools); i4++ {
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.IPv4PrivatePools.Pools[i4].ID),
				Extract:      resource.ExtractParamPath("id", true),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.IPv4PrivatePools.Pools[i4].IDRef,
				Selector:     mg.Spec.InitProvider.IPv4PrivatePools.Pools[i4].IDSelector,
				To: reference.To{
					List:    &PoolList{},
					Managed: &Pool{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.IPv4PrivatePools.Pools[i4].ID")
			}
			mg.Spec.InitProvider.IPv4PrivatePools.Pools[i4].ID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.IPv4PrivatePools.Pools[i4].IDRef = rsp.ResolvedReference

		}
	}
	if mg.Spec.InitProvider.IPv4PublicPools != nil {
		for i4 := 0; i4 < len(mg.Spec.InitProvider.IPv4PublicPools.Pools); i4++ {
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.IPv4PublicPools.Pools[i4].ID),
				Extract:      resource.ExtractParamPath("id", true),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.IPv4PublicPools.Pools[i4].IDRef,
				Selector:     mg.Spec.InitProvider.IPv4PublicPools.Pools[i4].IDSelector,
				To: reference.To{
					List:    &PoolList{},
					Managed: &Pool{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.IPv4PublicPools.Pools[i4].ID")
			}
			mg.Spec.InitProvider.IPv4PublicPools.Pools[i4].ID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.IPv4PublicPools.Pools[i4].IDRef = rsp.ResolvedReference

		}
	}

	return nil
}

// ResolveReferences of this Pool.
func (mg *Pool) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SourcePoolID),
		Extract:      resource.ExtractParamPath("id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.SourcePoolIDRef,
		Selector:     mg.Spec.ForProvider.SourcePoolIDSelector,
		To: reference.To{
			List:    &PoolList{},
			Managed: &Pool{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SourcePoolID")
	}
	mg.Spec.ForProvider.SourcePoolID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SourcePoolIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SourcePoolID),
		Extract:      resource.ExtractParamPath("id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.SourcePoolIDRef,
		Selector:     mg.Spec.InitProvider.SourcePoolIDSelector,
		To: reference.To{
			List:    &PoolList{},
			Managed: &Pool{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.SourcePoolID")
	}
	mg.Spec.InitProvider.SourcePoolID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.SourcePoolIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Route.
func (mg *Route) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	if mg.Spec.ForProvider.NextHop != nil {
		if mg.Spec.ForProvider.NextHop.Allocation != nil {
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.NextHop.Allocation.ID),
				Extract:      resource.ExtractParamPath("id", true),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.NextHop.Allocation.IDRef,
				Selector:     mg.Spec.ForProvider.NextHop.Allocation.IDSelector,
				To: reference.To{
					List:    &AllocationList{},
					Managed: &Allocation{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.NextHop.Allocation.ID")
			}
			mg.Spec.ForProvider.NextHop.Allocation.ID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.NextHop.Allocation.IDRef = rsp.ResolvedReference

		}
	}
	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ParentID),
		Extract:      resource.ExtractParamPath("id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ParentIDRef,
		Selector:     mg.Spec.ForProvider.ParentIDSelector,
		To: reference.To{
			List:    &RouteTableList{},
			Managed: &RouteTable{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ParentID")
	}
	mg.Spec.ForProvider.ParentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ParentIDRef = rsp.ResolvedReference

	if mg.Spec.InitProvider.NextHop != nil {
		if mg.Spec.InitProvider.NextHop.Allocation != nil {
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.NextHop.Allocation.ID),
				Extract:      resource.ExtractParamPath("id", true),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.NextHop.Allocation.IDRef,
				Selector:     mg.Spec.InitProvider.NextHop.Allocation.IDSelector,
				To: reference.To{
					List:    &AllocationList{},
					Managed: &Allocation{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.NextHop.Allocation.ID")
			}
			mg.Spec.InitProvider.NextHop.Allocation.ID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.NextHop.Allocation.IDRef = rsp.ResolvedReference

		}
	}
	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ParentID),
		Extract:      resource.ExtractParamPath("id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ParentIDRef,
		Selector:     mg.Spec.InitProvider.ParentIDSelector,
		To: reference.To{
			List:    &RouteTableList{},
			Managed: &RouteTable{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ParentID")
	}
	mg.Spec.InitProvider.ParentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ParentIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this RouteTable.
func (mg *RouteTable) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.NetworkID),
		Extract:      resource.ExtractParamPath("id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.NetworkIDRef,
		Selector:     mg.Spec.ForProvider.NetworkIDSelector,
		To: reference.To{
			List:    &NetworkList{},
			Managed: &Network{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.NetworkID")
	}
	mg.Spec.ForProvider.NetworkID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.NetworkIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.NetworkID),
		Extract:      resource.ExtractParamPath("id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.NetworkIDRef,
		Selector:     mg.Spec.InitProvider.NetworkIDSelector,
		To: reference.To{
			List:    &NetworkList{},
			Managed: &Network{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.NetworkID")
	}
	mg.Spec.InitProvider.NetworkID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.NetworkIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this SecurityGroup.
func (mg *SecurityGroup) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.NetworkID),
		Extract:      resource.ExtractParamPath("id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.NetworkIDRef,
		Selector:     mg.Spec.ForProvider.NetworkIDSelector,
		To: reference.To{
			List:    &NetworkList{},
			Managed: &Network{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.NetworkID")
	}
	mg.Spec.ForProvider.NetworkID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.NetworkIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.NetworkID),
		Extract:      resource.ExtractParamPath("id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.NetworkIDRef,
		Selector:     mg.Spec.InitProvider.NetworkIDSelector,
		To: reference.To{
			List:    &NetworkList{},
			Managed: &Network{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.NetworkID")
	}
	mg.Spec.InitProvider.NetworkID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.NetworkIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this SecurityRule.
func (mg *SecurityRule) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	if mg.Spec.ForProvider.Egress != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Egress.DestinationSecurityGroupID),
			Extract:      resource.ExtractParamPath("id", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.Egress.DestinationSecurityGroupIDRef,
			Selector:     mg.Spec.ForProvider.Egress.DestinationSecurityGroupIDSelector,
			To: reference.To{
				List:    &SecurityGroupList{},
				Managed: &SecurityGroup{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Egress.DestinationSecurityGroupID")
		}
		mg.Spec.ForProvider.Egress.DestinationSecurityGroupID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Egress.DestinationSecurityGroupIDRef = rsp.ResolvedReference

	}
	if mg.Spec.ForProvider.Ingress != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Ingress.SourceSecurityGroupID),
			Extract:      resource.ExtractParamPath("id", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.Ingress.SourceSecurityGroupIDRef,
			Selector:     mg.Spec.ForProvider.Ingress.SourceSecurityGroupIDSelector,
			To: reference.To{
				List:    &SecurityGroupList{},
				Managed: &SecurityGroup{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Ingress.SourceSecurityGroupID")
		}
		mg.Spec.ForProvider.Ingress.SourceSecurityGroupID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Ingress.SourceSecurityGroupIDRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ParentID),
		Extract:      resource.ExtractParamPath("id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ParentIDRef,
		Selector:     mg.Spec.ForProvider.ParentIDSelector,
		To: reference.To{
			List:    &SecurityGroupList{},
			Managed: &SecurityGroup{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ParentID")
	}
	mg.Spec.ForProvider.ParentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ParentIDRef = rsp.ResolvedReference

	if mg.Spec.InitProvider.Egress != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Egress.DestinationSecurityGroupID),
			Extract:      resource.ExtractParamPath("id", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.Egress.DestinationSecurityGroupIDRef,
			Selector:     mg.Spec.InitProvider.Egress.DestinationSecurityGroupIDSelector,
			To: reference.To{
				List:    &SecurityGroupList{},
				Managed: &SecurityGroup{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Egress.DestinationSecurityGroupID")
		}
		mg.Spec.InitProvider.Egress.DestinationSecurityGroupID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Egress.DestinationSecurityGroupIDRef = rsp.ResolvedReference

	}
	if mg.Spec.InitProvider.Ingress != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Ingress.SourceSecurityGroupID),
			Extract:      resource.ExtractParamPath("id", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.Ingress.SourceSecurityGroupIDRef,
			Selector:     mg.Spec.InitProvider.Ingress.SourceSecurityGroupIDSelector,
			To: reference.To{
				List:    &SecurityGroupList{},
				Managed: &SecurityGroup{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Ingress.SourceSecurityGroupID")
		}
		mg.Spec.InitProvider.Ingress.SourceSecurityGroupID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Ingress.SourceSecurityGroupIDRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ParentID),
		Extract:      resource.ExtractParamPath("id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ParentIDRef,
		Selector:     mg.Spec.InitProvider.ParentIDSelector,
		To: reference.To{
			List:    &SecurityGroupList{},
			Managed: &SecurityGroup{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ParentID")
	}
	mg.Spec.InitProvider.ParentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ParentIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Subnet.
func (mg *Subnet) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.NetworkID),
		Extract:      resource.ExtractParamPath("id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.NetworkIDRef,
		Selector:     mg.Spec.ForProvider.NetworkIDSelector,
		To: reference.To{
			List:    &NetworkList{},
			Managed: &Network{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.NetworkID")
	}
	mg.Spec.ForProvider.NetworkID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.NetworkIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.RouteTableID),
		Extract:      resource.ExtractParamPath("id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.RouteTableIDRef,
		Selector:     mg.Spec.ForProvider.RouteTableIDSelector,
		To: reference.To{
			List:    &RouteTableList{},
			Managed: &RouteTable{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.RouteTableID")
	}
	mg.Spec.ForProvider.RouteTableID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.RouteTableIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.NetworkID),
		Extract:      resource.ExtractParamPath("id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.NetworkIDRef,
		Selector:     mg.Spec.InitProvider.NetworkIDSelector,
		To: reference.To{
			List:    &NetworkList{},
			Managed: &Network{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.NetworkID")
	}
	mg.Spec.InitProvider.NetworkID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.NetworkIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.RouteTableID),
		Extract:      resource.ExtractParamPath("id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.RouteTableIDRef,
		Selector:     mg.Spec.InitProvider.RouteTableIDSelector,
		To: reference.To{
			List:    &RouteTableList{},
			Managed: &RouteTable{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.RouteTableID")
	}
	mg.Spec.InitProvider.RouteTableID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.RouteTableIDRef = rsp.ResolvedReference

	return nil
}
