apiVersion: mysteryboxv1.nebius.upbound.io/v1beta1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: mysteryboxv1/v1beta1/secret
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    name: mysteryboxv1secret
    description: Application secret
    parentId: ${data.nebius_project_id}
