apiVersion: vpc.nebius.m.upbound.io/v1beta1
kind: SecurityRule
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/securityrule
  labels:
    testing.upbound.io/example-name: allow_https
  name: allow-https
  namespace: upbound-system
spec:
  forProvider:
    access: ALLOW
    ingress:
      destinationPorts:
      - 443
      sourceCidrs:
      - 0.0.0.0/0
    name: allow-https
    parentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: web
    priority: 100
    protocol: TCP
    type: STATEFUL

---

apiVersion: vpc.nebius.m.upbound.io/v1beta1
kind: SecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/securityrule
  labels:
    testing.upbound.io/example-name: web
  name: web
  namespace: upbound-system
spec:
  forProvider:
    name: web-security-group
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    parentId: project-id
