apiVersion: vpcv1.nebius.m.upbound.io/v1beta1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: vpcv1/v1beta1/subnet
  labels:
    testing.upbound.io/example-name: default
  name: default
  namespace: upbound-system
spec:
  forProvider:
    ipv4PrivatePools:
      useNetworkPools: true
    name: default-subnet
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    parentId: project-id

---

apiVersion: vpcv1.nebius.m.upbound.io/v1beta1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: vpcv1/v1beta1/subnet
  labels:
    testing.upbound.io/example-name: default
  name: default
  namespace: upbound-system
spec:
  forProvider:
    name: default-network
    parentId: project-id
