apiVersion: registryv1.nebius.upbound.io/v1beta1
kind: Registry
metadata:
  annotations:
    meta.upbound.io/example-id: registryv1/v1beta1/registry
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    parentId: ${data.nebius_project_id}
    name: registryv1registry
    description: Container images for the application
