apiVersion: vpcv1.nebius.m.upbound.io/v1beta1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: vpcv1/v1beta1/network
  labels:
    testing.upbound.io/example-name: default
  name: default
  namespace: upbound-system
spec:
  forProvider:
    name: vpv1network
    parentId: ${data.nebius_project_id}
