apiVersion: vpcv1.nebius.m.upbound.io/v1beta1
kind: SecurityRule
metadata:
  annotations:
    meta.upbound.io/example-id: vpcv1/v1beta1/securityrule
  labels:
    testing.upbound.io/example-name: default
  name: default
  namespace: upbound-system
spec:
  forProvider:
    access: ALLOW
    type: STATEFUL
    protocol: TCP
    priority: 100
    name: vpcv1securityrule
    ingress:
      destinationPorts:
      - 443
      sourceCidrs:
      - 0.0.0.0/0
    parentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default

---

apiVersion: vpcv1.nebius.m.upbound.io/v1beta1
kind: SecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: vpcv1/v1beta1/securityrule
  labels:
    testing.upbound.io/example-name: default
  name: default
  namespace: upbound-system
spec:
  forProvider:
    name: vpcv1securityrule
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    parentId: ${data.nebius_project_id}

---

apiVersion: vpcv1.nebius.m.upbound.io/v1beta1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: vpcv1/v1beta1/securityrule
  labels:
    testing.upbound.io/example-name: default
  name: default
  namespace: upbound-system
spec:
  forProvider:
    name: vpcv1securityrule
    parentId: ${data.nebius_project_id}
