// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type AutoRepairInitParameters struct {

	// (Attributes List) Conditions that determine whether a node should be auto repaired. (see below for nested schema)
	Conditions []ConditionsInitParameters `json:"conditions,omitempty" tf:"conditions,omitempty"`
}

type AutoRepairObservation struct {

	// (Attributes List) Conditions that determine whether a node should be auto repaired. (see below for nested schema)
	Conditions []ConditionsObservation `json:"conditions,omitempty" tf:"conditions,omitempty"`
}

type AutoRepairParameters struct {

	// (Attributes List) Conditions that determine whether a node should be auto repaired. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Conditions []ConditionsParameters `json:"conditions,omitempty" tf:"conditions,omitempty"`
}

type AutoscalingInitParameters struct {

	// (Number)
	MaxNodeCount *float64 `json:"maxNodeCount,omitempty" tf:"max_node_count,omitempty"`

	// (Number)
	MinNodeCount *float64 `json:"minNodeCount,omitempty" tf:"min_node_count,omitempty"`
}

type AutoscalingObservation struct {

	// (Number)
	MaxNodeCount *float64 `json:"maxNodeCount,omitempty" tf:"max_node_count,omitempty"`

	// (Number)
	MinNodeCount *float64 `json:"minNodeCount,omitempty" tf:"min_node_count,omitempty"`
}

type AutoscalingParameters struct {

	// (Number)
	// +kubebuilder:validation:Optional
	MaxNodeCount *float64 `json:"maxNodeCount,omitempty" tf:"max_node_count,omitempty"`

	// (Number)
	// +kubebuilder:validation:Optional
	MinNodeCount *float64 `json:"minNodeCount,omitempty" tf:"min_node_count,omitempty"`
}

type BootDiskInitParameters struct {

	// (Number)
	BlockSizeBytes *float64 `json:"blockSizeBytes,omitempty" tf:"block_size_bytes,omitempty"`

	// (Number) Cannot be set alongside size_kibibytes, size_mebibytes or size_gibibytes.
	// *Cannot be set alongside size_kibibytes, size_mebibytes or size_gibibytes.*
	SizeBytes *float64 `json:"sizeBytes,omitempty" tf:"size_bytes,omitempty"`

	// (Number) Cannot be set alongside size_bytes, size_kibibytes or size_mebibytes.
	// *Cannot be set alongside size_bytes, size_kibibytes or size_mebibytes.*
	SizeGibibytes *float64 `json:"sizeGibibytes,omitempty" tf:"size_gibibytes,omitempty"`

	// (Number) Cannot be set alongside size_bytes, size_mebibytes or size_gibibytes.
	// *Cannot be set alongside size_bytes, size_mebibytes or size_gibibytes.*
	SizeKibibytes *float64 `json:"sizeKibibytes,omitempty" tf:"size_kibibytes,omitempty"`

	// (Number) Cannot be set alongside size_bytes, size_kibibytes or size_gibibytes.
	// *Cannot be set alongside size_bytes, size_kibibytes or size_gibibytes.*
	SizeMebibytes *float64 `json:"sizeMebibytes,omitempty" tf:"size_mebibytes,omitempty"`

	// (String) :
	// :
	//
	// #### Supported values
	//
	// Possible values:
	//
	// - `UNSPECIFIED`
	// - `NETWORK_SSD`
	// - `NETWORK_HDD`
	// - `NETWORK_SSD_IO_M3`
	// - `NETWORK_SSD_NON_REPLICATED`
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type BootDiskObservation struct {

	// (Number)
	BlockSizeBytes *float64 `json:"blockSizeBytes,omitempty" tf:"block_size_bytes,omitempty"`

	// (Number) Cannot be set alongside size_kibibytes, size_mebibytes or size_gibibytes.
	// *Cannot be set alongside size_kibibytes, size_mebibytes or size_gibibytes.*
	SizeBytes *float64 `json:"sizeBytes,omitempty" tf:"size_bytes,omitempty"`

	// (Number) Cannot be set alongside size_bytes, size_kibibytes or size_mebibytes.
	// *Cannot be set alongside size_bytes, size_kibibytes or size_mebibytes.*
	SizeGibibytes *float64 `json:"sizeGibibytes,omitempty" tf:"size_gibibytes,omitempty"`

	// (Number) Cannot be set alongside size_bytes, size_mebibytes or size_gibibytes.
	// *Cannot be set alongside size_bytes, size_mebibytes or size_gibibytes.*
	SizeKibibytes *float64 `json:"sizeKibibytes,omitempty" tf:"size_kibibytes,omitempty"`

	// (Number) Cannot be set alongside size_bytes, size_kibibytes or size_gibibytes.
	// *Cannot be set alongside size_bytes, size_kibibytes or size_gibibytes.*
	SizeMebibytes *float64 `json:"sizeMebibytes,omitempty" tf:"size_mebibytes,omitempty"`

	// (String) :
	// :
	//
	// #### Supported values
	//
	// Possible values:
	//
	// - `UNSPECIFIED`
	// - `NETWORK_SSD`
	// - `NETWORK_HDD`
	// - `NETWORK_SSD_IO_M3`
	// - `NETWORK_SSD_NON_REPLICATED`
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type BootDiskParameters struct {

	// (Number)
	// +kubebuilder:validation:Optional
	BlockSizeBytes *float64 `json:"blockSizeBytes,omitempty" tf:"block_size_bytes,omitempty"`

	// (Number) Cannot be set alongside size_kibibytes, size_mebibytes or size_gibibytes.
	// *Cannot be set alongside size_kibibytes, size_mebibytes or size_gibibytes.*
	// +kubebuilder:validation:Optional
	SizeBytes *float64 `json:"sizeBytes,omitempty" tf:"size_bytes,omitempty"`

	// (Number) Cannot be set alongside size_bytes, size_kibibytes or size_mebibytes.
	// *Cannot be set alongside size_bytes, size_kibibytes or size_mebibytes.*
	// +kubebuilder:validation:Optional
	SizeGibibytes *float64 `json:"sizeGibibytes,omitempty" tf:"size_gibibytes,omitempty"`

	// (Number) Cannot be set alongside size_bytes, size_mebibytes or size_gibibytes.
	// *Cannot be set alongside size_bytes, size_mebibytes or size_gibibytes.*
	// +kubebuilder:validation:Optional
	SizeKibibytes *float64 `json:"sizeKibibytes,omitempty" tf:"size_kibibytes,omitempty"`

	// (Number) Cannot be set alongside size_bytes, size_kibibytes or size_gibibytes.
	// *Cannot be set alongside size_bytes, size_kibibytes or size_gibibytes.*
	// +kubebuilder:validation:Optional
	SizeMebibytes *float64 `json:"sizeMebibytes,omitempty" tf:"size_mebibytes,omitempty"`

	// (String) :
	// :
	//
	// #### Supported values
	//
	// Possible values:
	//
	// - `UNSPECIFIED`
	// - `NETWORK_SSD`
	// - `NETWORK_HDD`
	// - `NETWORK_SSD_IO_M3`
	// - `NETWORK_SSD_NON_REPLICATED`
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ConditionsInitParameters struct {

	// (Boolean) :
	// :
	//
	// When true, disables the default auto-repair condition rules.
	//
	// *Cannot be set alongside timeout.*
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (Attributes) (see below for nested schema)
	// :
	//
	// Node condition status.
	//
	// #### Supported values
	//
	// Possible values:
	//
	// - `CONDITION_STATUS_UNSPECIFIED`
	// - `TRUE`
	// - `FALSE`
	// - `UNKNOWN`
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (String) :
	// :
	//
	// The duration after which the node is automatically repaired if the condition remains in the specified status.
	//
	// Duration as a string: possibly signed sequence of decimal numbers, each with optional fraction and a unit suffix, such as `300ms`, `-1.5h` or `2h45m`. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`, `d`.
	//
	// *Cannot be set alongside disabled.*
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// (String) :
	// Node condition type.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ConditionsObservation struct {

	// (Boolean) :
	// :
	//
	// When true, disables the default auto-repair condition rules.
	//
	// *Cannot be set alongside timeout.*
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (Attributes) (see below for nested schema)
	// :
	//
	// Node condition status.
	//
	// #### Supported values
	//
	// Possible values:
	//
	// - `CONDITION_STATUS_UNSPECIFIED`
	// - `TRUE`
	// - `FALSE`
	// - `UNKNOWN`
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (String) :
	// :
	//
	// The duration after which the node is automatically repaired if the condition remains in the specified status.
	//
	// Duration as a string: possibly signed sequence of decimal numbers, each with optional fraction and a unit suffix, such as `300ms`, `-1.5h` or `2h45m`. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`, `d`.
	//
	// *Cannot be set alongside disabled.*
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// (String) :
	// Node condition type.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ConditionsParameters struct {

	// (Boolean) :
	// :
	//
	// When true, disables the default auto-repair condition rules.
	//
	// *Cannot be set alongside timeout.*
	// +kubebuilder:validation:Optional
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (Attributes) (see below for nested schema)
	// :
	//
	// Node condition status.
	//
	// #### Supported values
	//
	// Possible values:
	//
	// - `CONDITION_STATUS_UNSPECIFIED`
	// - `TRUE`
	// - `FALSE`
	// - `UNKNOWN`
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (String) :
	// :
	//
	// The duration after which the node is automatically repaired if the condition remains in the specified status.
	//
	// Duration as a string: possibly signed sequence of decimal numbers, each with optional fraction and a unit suffix, such as `300ms`, `-1.5h` or `2h45m`. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`, `d`.
	//
	// *Cannot be set alongside disabled.*
	// +kubebuilder:validation:Optional
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// (String) :
	// Node condition type.
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

type ConfigInitParameters struct {

	// (Boolean) :
	// :
	//
	// kubelet_ephemeral: combine all local disks into a single storage volume and use it as kubelet's local ephemeral storage on the node
	// See also https://kubernetes.io/docs/concepts/storage/ephemeral-storage/
	//
	// The default when LocalDisksSpecConfig is not set.
	//
	// *Cannot be set alongside none.*
	KubeletEphemeral *bool `json:"kubeletEphemeral,omitempty" tf:"kubelet_ephemeral,omitempty"`

	// (Boolean) :
	// :
	//
	// none: "do nothing" - local disks will be provisioned as on a regular compute instance.
	//
	// *Cannot be set alongside kubelet_ephemeral.*
	None *bool `json:"none,omitempty" tf:"none,omitempty"`
}

type ConfigObservation struct {

	// (Boolean) :
	// :
	//
	// kubelet_ephemeral: combine all local disks into a single storage volume and use it as kubelet's local ephemeral storage on the node
	// See also https://kubernetes.io/docs/concepts/storage/ephemeral-storage/
	//
	// The default when LocalDisksSpecConfig is not set.
	//
	// *Cannot be set alongside none.*
	KubeletEphemeral *bool `json:"kubeletEphemeral,omitempty" tf:"kubelet_ephemeral,omitempty"`

	// (Boolean) :
	// :
	//
	// none: "do nothing" - local disks will be provisioned as on a regular compute instance.
	//
	// *Cannot be set alongside kubelet_ephemeral.*
	None *bool `json:"none,omitempty" tf:"none,omitempty"`
}

type ConfigParameters struct {

	// (Boolean) :
	// :
	//
	// kubelet_ephemeral: combine all local disks into a single storage volume and use it as kubelet's local ephemeral storage on the node
	// See also https://kubernetes.io/docs/concepts/storage/ephemeral-storage/
	//
	// The default when LocalDisksSpecConfig is not set.
	//
	// *Cannot be set alongside none.*
	// +kubebuilder:validation:Optional
	KubeletEphemeral *bool `json:"kubeletEphemeral,omitempty" tf:"kubelet_ephemeral,omitempty"`

	// (Boolean) :
	// :
	//
	// none: "do nothing" - local disks will be provisioned as on a regular compute instance.
	//
	// *Cannot be set alongside kubelet_ephemeral.*
	// +kubebuilder:validation:Optional
	None *bool `json:"none,omitempty" tf:"none,omitempty"`
}

type EventsLastOccurrenceInitParameters struct {
}

type EventsLastOccurrenceObservation struct {

	// (String) Event code (unique within the API service), in UpperCamelCase, e.g. "DiskAttached"
	// Event code (unique within the API service), in UpperCamelCase, e.g. `"DiskAttached"`
	Code *string `json:"code,omitempty" tf:"code,omitempty"`

	// (String) :
	// :
	//
	// # Severity level for the event
	//
	// #### Supported values
	//
	// Possible values:
	//
	// - `UNSPECIFIED` - Unspecified event severity level
	// - `DEBUG` - A debug event providing detailed insight. Such events are used to debug problems with specific resource(s) and process(es)
	// - `INFO` - A normal event or state change. Informs what is happening with the API resource. Does not require user attention or interaction
	// - `WARN`:
	// Warning event. Indicates a potential or minor problem with the API resource and/or the corresponding processes. Needs user attention,
	// but requires no immediate action (yet)
	//
	// - `ERROR` - Error event. Indicates a serious problem with the API resource and/or the corresponding processes. Requires immediate user action
	Level *string `json:"level,omitempty" tf:"level,omitempty"`

	// (String) :
	// :
	//
	// A human-readable message describing what has happened
	// (and suggested actions for the user, if this is a `WARN` or `ERROR` level event)
	Message *string `json:"message,omitempty" tf:"message,omitempty"`

	// (String) :
	// :
	//
	// # Time at which the event has occurred
	//
	// A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
	OccurredAt *string `json:"occurredAt,omitempty" tf:"occurred_at,omitempty"`
}

type EventsLastOccurrenceParameters struct {
}

type ExistingFilesystemInitParameters struct {

	// (String) Identifier for the resource, unique for its resource type.
	// +crossplane:generate:reference:type=github.com/upbound/provider-nebius/apis/namespaced/compute/v1beta1.Filesystem
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id",true)
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Reference to a Filesystem in compute to populate id.
	// +kubebuilder:validation:Optional
	IDRef *v1.NamespacedReference `json:"idRef,omitempty" tf:"-"`

	// Selector for a Filesystem in compute to populate id.
	// +kubebuilder:validation:Optional
	IDSelector *v1.NamespacedSelector `json:"idSelector,omitempty" tf:"-"`
}

type ExistingFilesystemObservation struct {

	// (String) Identifier for the resource, unique for its resource type.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type ExistingFilesystemParameters struct {

	// (String) Identifier for the resource, unique for its resource type.
	// +crossplane:generate:reference:type=github.com/upbound/provider-nebius/apis/namespaced/compute/v1beta1.Filesystem
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id",true)
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Reference to a Filesystem in compute to populate id.
	// +kubebuilder:validation:Optional
	IDRef *v1.NamespacedReference `json:"idRef,omitempty" tf:"-"`

	// Selector for a Filesystem in compute to populate id.
	// +kubebuilder:validation:Optional
	IDSelector *v1.NamespacedSelector `json:"idSelector,omitempty" tf:"-"`
}

type FilesystemsInitParameters struct {

	// (String) :
	// :
	//
	// #### Supported values
	//
	// Possible values:
	//
	// - `UNSPECIFIED`
	// - `READ_ONLY`
	// - `READ_WRITE`
	AttachMode *string `json:"attachMode,omitempty" tf:"attach_mode,omitempty"`

	// (Attributes) (see below for nested schema)
	ExistingFilesystem *ExistingFilesystemInitParameters `json:"existingFilesystem,omitempty" tf:"existing_filesystem,omitempty"`

	// defined identifier, allowing to use it as a device in mount command.
	// Specifies the user-defined identifier, allowing to use it as a device in mount command.
	MountTag *string `json:"mountTag,omitempty" tf:"mount_tag,omitempty"`
}

type FilesystemsObservation struct {

	// (String) :
	// :
	//
	// #### Supported values
	//
	// Possible values:
	//
	// - `UNSPECIFIED`
	// - `READ_ONLY`
	// - `READ_WRITE`
	AttachMode *string `json:"attachMode,omitempty" tf:"attach_mode,omitempty"`

	// (Attributes) (see below for nested schema)
	ExistingFilesystem *ExistingFilesystemObservation `json:"existingFilesystem,omitempty" tf:"existing_filesystem,omitempty"`

	// defined identifier, allowing to use it as a device in mount command.
	// Specifies the user-defined identifier, allowing to use it as a device in mount command.
	MountTag *string `json:"mountTag,omitempty" tf:"mount_tag,omitempty"`
}

type FilesystemsParameters struct {

	// (String) :
	// :
	//
	// #### Supported values
	//
	// Possible values:
	//
	// - `UNSPECIFIED`
	// - `READ_ONLY`
	// - `READ_WRITE`
	// +kubebuilder:validation:Optional
	AttachMode *string `json:"attachMode" tf:"attach_mode,omitempty"`

	// (Attributes) (see below for nested schema)
	// +kubebuilder:validation:Optional
	ExistingFilesystem *ExistingFilesystemParameters `json:"existingFilesystem,omitempty" tf:"existing_filesystem,omitempty"`

	// defined identifier, allowing to use it as a device in mount command.
	// Specifies the user-defined identifier, allowing to use it as a device in mount command.
	// +kubebuilder:validation:Optional
	MountTag *string `json:"mountTag" tf:"mount_tag,omitempty"`
}

type GpuClusterInitParameters struct {

	// (String) Identifier for the resource, unique for its resource type.
	// +crossplane:generate:reference:type=github.com/upbound/provider-nebius/apis/namespaced/compute/v1beta1.GpuCluster
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id",true)
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Reference to a GpuCluster in compute to populate id.
	// +kubebuilder:validation:Optional
	IDRef *v1.NamespacedReference `json:"idRef,omitempty" tf:"-"`

	// Selector for a GpuCluster in compute to populate id.
	// +kubebuilder:validation:Optional
	IDSelector *v1.NamespacedSelector `json:"idSelector,omitempty" tf:"-"`
}

type GpuClusterObservation struct {

	// (String) Identifier for the resource, unique for its resource type.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type GpuClusterParameters struct {

	// (String) Identifier for the resource, unique for its resource type.
	// +crossplane:generate:reference:type=github.com/upbound/provider-nebius/apis/namespaced/compute/v1beta1.GpuCluster
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id",true)
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Reference to a GpuCluster in compute to populate id.
	// +kubebuilder:validation:Optional
	IDRef *v1.NamespacedReference `json:"idRef,omitempty" tf:"-"`

	// Selector for a GpuCluster in compute to populate id.
	// +kubebuilder:validation:Optional
	IDSelector *v1.NamespacedSelector `json:"idSelector,omitempty" tf:"-"`
}

type GpuSettingsInitParameters struct {

	// : ""
	// :
	//
	// Identifier of the predefined set of drivers included in the ComputeImage deployed on ComputeInstances that are part of the NodeGroup.
	// Supported presets for different platform / Kubernetes version combinations:
	// * `gpu-l40s-a`, `gpu-l40s-d`, `gpu-h100-sxm`, `gpu-h200-sxm`:
	// * `version`: 1.30 → `"cuda12"` (CUDA 12.4)
	// * `version`: 1.31 → `"cuda12"` (CUDA 12.4), `"cuda12.4"`, `"cuda12.8"`
	// * `gpu-b200-sxm`:
	// * `version`: 1.31 → `"cuda12"` (CUDA 12.8), `"cuda12.8"`
	// * `gpu-b200-sxm-a`:
	// * `version`: 1.31 → `"cuda12.8"`
	DriversPreset *string `json:"driversPreset,omitempty" tf:"drivers_preset,omitempty"`
}

type GpuSettingsObservation struct {

	// : ""
	// :
	//
	// Identifier of the predefined set of drivers included in the ComputeImage deployed on ComputeInstances that are part of the NodeGroup.
	// Supported presets for different platform / Kubernetes version combinations:
	// * `gpu-l40s-a`, `gpu-l40s-d`, `gpu-h100-sxm`, `gpu-h200-sxm`:
	// * `version`: 1.30 → `"cuda12"` (CUDA 12.4)
	// * `version`: 1.31 → `"cuda12"` (CUDA 12.4), `"cuda12.4"`, `"cuda12.8"`
	// * `gpu-b200-sxm`:
	// * `version`: 1.31 → `"cuda12"` (CUDA 12.8), `"cuda12.8"`
	// * `gpu-b200-sxm-a`:
	// * `version`: 1.31 → `"cuda12.8"`
	DriversPreset *string `json:"driversPreset,omitempty" tf:"drivers_preset,omitempty"`
}

type GpuSettingsParameters struct {

	// : ""
	// :
	//
	// Identifier of the predefined set of drivers included in the ComputeImage deployed on ComputeInstances that are part of the NodeGroup.
	// Supported presets for different platform / Kubernetes version combinations:
	// * `gpu-l40s-a`, `gpu-l40s-d`, `gpu-h100-sxm`, `gpu-h200-sxm`:
	// * `version`: 1.30 → `"cuda12"` (CUDA 12.4)
	// * `version`: 1.31 → `"cuda12"` (CUDA 12.4), `"cuda12.4"`, `"cuda12.8"`
	// * `gpu-b200-sxm`:
	// * `version`: 1.31 → `"cuda12"` (CUDA 12.8), `"cuda12.8"`
	// * `gpu-b200-sxm-a`:
	// * `version`: 1.31 → `"cuda12.8"`
	// +kubebuilder:validation:Optional
	DriversPreset *string `json:"driversPreset" tf:"drivers_preset,omitempty"`
}

type LocalDisksInitParameters struct {

	// (Attributes) :
	Config *ConfigInitParameters `json:"config,omitempty" tf:"config,omitempty"`

	// (Attributes) :
	PassthroughGroup *PassthroughGroupInitParameters `json:"passthroughGroup,omitempty" tf:"passthrough_group,omitempty"`
}

type LocalDisksObservation struct {

	// (Attributes) :
	Config *ConfigObservation `json:"config,omitempty" tf:"config,omitempty"`

	// (Attributes) :
	PassthroughGroup *PassthroughGroupObservation `json:"passthroughGroup,omitempty" tf:"passthrough_group,omitempty"`
}

type LocalDisksParameters struct {

	// (Attributes) :
	// +kubebuilder:validation:Optional
	Config *ConfigParameters `json:"config,omitempty" tf:"config,omitempty"`

	// (Attributes) :
	// +kubebuilder:validation:Optional
	PassthroughGroup *PassthroughGroupParameters `json:"passthroughGroup,omitempty" tf:"passthrough_group,omitempty"`
}

type MaxSurgeInitParameters struct {
}

type MaxSurgeObservation struct {

	// (Number) Cannot be set alongside percent.
	// *Cannot be set alongside percent.*
	Count *float64 `json:"count,omitempty" tf:"count,omitempty"`

	// (Number) Cannot be set alongside count.
	// *Cannot be set alongside count.*
	Percent *float64 `json:"percent,omitempty" tf:"percent,omitempty"`
}

type MaxSurgeParameters struct {
}

type MaxUnavailableInitParameters struct {
}

type MaxUnavailableObservation struct {

	// (Number) Cannot be set alongside percent.
	// *Cannot be set alongside percent.*
	Count *float64 `json:"count,omitempty" tf:"count,omitempty"`

	// (Number) Cannot be set alongside count.
	// *Cannot be set alongside count.*
	Percent *float64 `json:"percent,omitempty" tf:"percent,omitempty"`
}

type MaxUnavailableParameters struct {
}

type NetworkInterfacesInitParameters struct {

	// (Attributes) :
	PublicIPAddress *PublicIPAddressInitParameters `json:"publicIpAddress,omitempty" tf:"public_ip_address,omitempty"`

	// (Attributes List) User provided VPC Security Groups which will be assigned to all nodes of this NodeGroup. (see below for nested schema)
	SecurityGroups []SecurityGroupsInitParameters `json:"securityGroups,omitempty" tf:"security_groups,omitempty"`

	// (String) :
	// :
	//
	// Nebius VPC Subnet ID that will be attached to a node cloud instance network interface.
	// By default Cluster control plane subnet_id used.
	// Subnet should be located in the same network with control plane.
	// +crossplane:generate:reference:type=github.com/upbound/provider-nebius/apis/namespaced/vpc/v1beta1.Subnet
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id",true)
	SubnetID *string `json:"subnetId,omitempty" tf:"subnet_id,omitempty"`

	// Reference to a Subnet in vpc to populate subnetId.
	// +kubebuilder:validation:Optional
	SubnetIDRef *v1.NamespacedReference `json:"subnetIdRef,omitempty" tf:"-"`

	// Selector for a Subnet in vpc to populate subnetId.
	// +kubebuilder:validation:Optional
	SubnetIDSelector *v1.NamespacedSelector `json:"subnetIdSelector,omitempty" tf:"-"`
}

type NetworkInterfacesObservation struct {

	// (Attributes) :
	PublicIPAddress *PublicIPAddressParameters `json:"publicIpAddress,omitempty" tf:"public_ip_address,omitempty"`

	// (Attributes List) User provided VPC Security Groups which will be assigned to all nodes of this NodeGroup. (see below for nested schema)
	SecurityGroups []SecurityGroupsObservation `json:"securityGroups,omitempty" tf:"security_groups,omitempty"`

	// (String) :
	// :
	//
	// Nebius VPC Subnet ID that will be attached to a node cloud instance network interface.
	// By default Cluster control plane subnet_id used.
	// Subnet should be located in the same network with control plane.
	SubnetID *string `json:"subnetId,omitempty" tf:"subnet_id,omitempty"`
}

type NetworkInterfacesParameters struct {

	// (Attributes) :
	// +kubebuilder:validation:Optional
	PublicIPAddress *PublicIPAddressParameters `json:"publicIpAddress,omitempty" tf:"public_ip_address,omitempty"`

	// (Attributes List) User provided VPC Security Groups which will be assigned to all nodes of this NodeGroup. (see below for nested schema)
	// +kubebuilder:validation:Optional
	SecurityGroups []SecurityGroupsParameters `json:"securityGroups,omitempty" tf:"security_groups,omitempty"`

	// (String) :
	// :
	//
	// Nebius VPC Subnet ID that will be attached to a node cloud instance network interface.
	// By default Cluster control plane subnet_id used.
	// Subnet should be located in the same network with control plane.
	// +crossplane:generate:reference:type=github.com/upbound/provider-nebius/apis/namespaced/vpc/v1beta1.Subnet
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id",true)
	// +kubebuilder:validation:Optional
	SubnetID *string `json:"subnetId,omitempty" tf:"subnet_id,omitempty"`

	// Reference to a Subnet in vpc to populate subnetId.
	// +kubebuilder:validation:Optional
	SubnetIDRef *v1.NamespacedReference `json:"subnetIdRef,omitempty" tf:"-"`

	// Selector for a Subnet in vpc to populate subnetId.
	// +kubebuilder:validation:Optional
	SubnetIDSelector *v1.NamespacedSelector `json:"subnetIdSelector,omitempty" tf:"-"`
}

type NodeGroupInitParameters struct {

	// (Attributes) Parameters for nodes auto repair. (see below for nested schema)
	AutoRepair *AutoRepairInitParameters `json:"autoRepair,omitempty" tf:"auto_repair,omitempty"`

	// (Attributes) :
	Autoscaling *AutoscalingInitParameters `json:"autoscaling,omitempty" tf:"autoscaling,omitempty"`

	// (Number) :
	// :
	//
	// Number of nodes in the group. Can be changed manually at any time.
	//
	// *Cannot be set alongside autoscaling.*
	FixedNodeCount *float64 `json:"fixedNodeCount,omitempty" tf:"fixed_node_count,omitempty"`

	// (Map of String) Labels associated with the resource.
	// Labels associated with the resource.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (Attributes) :
	Metadata *NodeGroupMetadataInitParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// (String) Human readable name for the resource.
	// Human readable name for the resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Identifier of the parent resource to which the resource belongs.
	// Identifier of the parent resource to which the resource belongs.
	// +crossplane:generate:reference:type=github.com/upbound/provider-nebius/apis/namespaced/mk8s/v1beta1.Cluster
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id",true)
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// Reference to a Cluster in mk8s to populate parentId.
	// +kubebuilder:validation:Optional
	ParentIDRef *v1.NamespacedReference `json:"parentIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in mk8s to populate parentId.
	// +kubebuilder:validation:Optional
	ParentIDSelector *v1.NamespacedSelector `json:"parentIdSelector,omitempty" tf:"-"`

	// (Attributes) :
	Strategy *NodeGroupStrategyInitParameters `json:"strategy,omitempty" tf:"strategy,omitempty"`

	// (Attributes) :
	Template *TemplateInitParameters `json:"template,omitempty" tf:"template,omitempty"`

	// (String) :
	// :
	//
	// Version is desired Kubernetes version of the cluster. For now only acceptable format is
	// `<major>.<minor>` like "1.31". Option for patch version update will be added later.
	// By default the cluster control plane `<major>.<minor>` version will be used.
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type NodeGroupMetadataInitParameters struct {
}

type NodeGroupMetadataObservation struct {
}

type NodeGroupMetadataParameters struct {
}

type NodeGroupObservation struct {

	// (Attributes) Parameters for nodes auto repair. (see below for nested schema)
	AutoRepair *AutoRepairObservation `json:"autoRepair,omitempty" tf:"auto_repair,omitempty"`

	// (Attributes) :
	Autoscaling *AutoscalingObservation `json:"autoscaling,omitempty" tf:"autoscaling,omitempty"`

	// (String) :
	// :
	//
	// Timestamp indicating when the resource was created.
	//
	// A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (Number) :
	// :
	//
	// Number of nodes in the group. Can be changed manually at any time.
	//
	// *Cannot be set alongside autoscaling.*
	FixedNodeCount *float64 `json:"fixedNodeCount,omitempty" tf:"fixed_node_count,omitempty"`

	// (String) Identifier for the resource, unique for its resource type.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Map of String) Labels associated with the resource.
	// Labels associated with the resource.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (Attributes) :
	Metadata *NodeGroupMetadataParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// (String) Human readable name for the resource.
	// Human readable name for the resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Identifier of the parent resource to which the resource belongs.
	// Identifier of the parent resource to which the resource belongs.
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// (Number) :
	// :
	//
	// Version of the resource for safe concurrent modifications and consistent reads.
	// Positive and monotonically increases on each resource spec change (but *not* on each change of the
	// resource's container(s) or status).
	// Service allows zero value or current.
	ResourceVersion *float64 `json:"resourceVersion,omitempty" tf:"resource_version,omitempty"`

	// (Attributes) (see below for nested schema)
	Status *NodeGroupStatusObservation `json:"status,omitempty" tf:"status,omitempty"`

	// (Attributes) :
	Strategy *NodeGroupStrategyObservation `json:"strategy,omitempty" tf:"strategy,omitempty"`

	// (Attributes) :
	Template *TemplateObservation `json:"template,omitempty" tf:"template,omitempty"`

	// (String) :
	// :
	//
	// Timestamp indicating when the resource was last updated.
	//
	// A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`

	// (String) :
	// :
	//
	// Version is desired Kubernetes version of the cluster. For now only acceptable format is
	// `<major>.<minor>` like "1.31". Option for patch version update will be added later.
	// By default the cluster control plane `<major>.<minor>` version will be used.
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type NodeGroupParameters struct {

	// (Attributes) Parameters for nodes auto repair. (see below for nested schema)
	// +kubebuilder:validation:Optional
	AutoRepair *AutoRepairParameters `json:"autoRepair,omitempty" tf:"auto_repair,omitempty"`

	// (Attributes) :
	// +kubebuilder:validation:Optional
	Autoscaling *AutoscalingParameters `json:"autoscaling,omitempty" tf:"autoscaling,omitempty"`

	// (Number) :
	// :
	//
	// Number of nodes in the group. Can be changed manually at any time.
	//
	// *Cannot be set alongside autoscaling.*
	// +kubebuilder:validation:Optional
	FixedNodeCount *float64 `json:"fixedNodeCount,omitempty" tf:"fixed_node_count,omitempty"`

	// (Map of String) Labels associated with the resource.
	// Labels associated with the resource.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (Attributes) :
	// +kubebuilder:validation:Optional
	Metadata *NodeGroupMetadataParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// (String) Human readable name for the resource.
	// Human readable name for the resource.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Identifier of the parent resource to which the resource belongs.
	// Identifier of the parent resource to which the resource belongs.
	// +crossplane:generate:reference:type=github.com/upbound/provider-nebius/apis/namespaced/mk8s/v1beta1.Cluster
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id",true)
	// +kubebuilder:validation:Optional
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// Reference to a Cluster in mk8s to populate parentId.
	// +kubebuilder:validation:Optional
	ParentIDRef *v1.NamespacedReference `json:"parentIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in mk8s to populate parentId.
	// +kubebuilder:validation:Optional
	ParentIDSelector *v1.NamespacedSelector `json:"parentIdSelector,omitempty" tf:"-"`

	// (Attributes) :
	// +kubebuilder:validation:Optional
	Strategy *NodeGroupStrategyParameters `json:"strategy,omitempty" tf:"strategy,omitempty"`

	// (Attributes) :
	// +kubebuilder:validation:Optional
	Template *TemplateParameters `json:"template,omitempty" tf:"template,omitempty"`

	// (String) :
	// :
	//
	// Version is desired Kubernetes version of the cluster. For now only acceptable format is
	// `<major>.<minor>` like "1.31". Option for patch version update will be added later.
	// By default the cluster control plane `<major>.<minor>` version will be used.
	// +kubebuilder:validation:Optional
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type NodeGroupStatusInitParameters struct {
}

type NodeGroupStatusObservation struct {

	// (Attributes List) :
	Events []StatusEventsObservation `json:"events,omitempty" tf:"events,omitempty"`

	// (Number) :
	// :
	//
	// Total number of nodes that are currently in the node group.
	// Both ready and not ready nodes are counted.
	NodeCount *float64 `json:"nodeCount,omitempty" tf:"node_count,omitempty"`

	// (Number) :
	// :
	//
	// Total number of nodes that has outdated node configuration.
	// These nodes will be replaced by new nodes with up-to-date configuration.
	OutdatedNodeCount *float64 `json:"outdatedNodeCount,omitempty" tf:"outdated_node_count,omitempty"`

	// (Number) :
	// :
	//
	// Total number of nodes that successfully joined the cluster and are ready to serve workloads.
	// Both outdated and up-to-date nodes are counted.
	ReadyNodeCount *float64 `json:"readyNodeCount,omitempty" tf:"ready_node_count,omitempty"`

	// (Boolean) Show that there are changes are in flight.
	// Show that there are changes are in flight.
	Reconciling *bool `json:"reconciling,omitempty" tf:"reconciling,omitempty"`

	// (String) :
	// :
	//
	// #### Supported values
	//
	// Possible values:
	//
	// - `STATE_UNSPECIFIED`
	// - `PROVISIONING`
	// - `RUNNING`
	// - `DELETING`
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// (Attributes) :
	Strategy *StrategyObservation `json:"strategy,omitempty" tf:"strategy,omitempty"`

	// (Number) :
	// :
	//
	// Desired total number of nodes that should be in the node group.
	// It is either `NodeGroupSpec.fixed_node_count` or arbitrary number between
	// `NodeGroupAutoscalingSpec.min_node_count` and `NodeGroupAutoscalingSpec.max_node_count` decided by autoscaler.
	TargetNodeCount *float64 `json:"targetNodeCount,omitempty" tf:"target_node_count,omitempty"`

	// (String) :
	// :
	//
	// Actual version of NodeGroup. Have format `<major>.<minor>.<patch>-nebius-node.<infra_version>` like "1.30.0-nebius-node.10".
	// Where `<major>.<minor>.<patch>` is Kubernetes version and `<infra_version>` is version of Node infrastructure and configuration,
	// which update may include bug fixes, security updates and new features depending on worker node configuration.
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type NodeGroupStatusParameters struct {
}

type NodeGroupStrategyInitParameters struct {

	// (String) :
	// :
	//
	// Maximum amount of time that the service will spend attempting to gracefully drain a node
	// (evicting its pods) before falling back to pod deletion.
	// A value of 0 (or when field is omitted) means no timeout: the node can be drained for an unlimited time.
	// Important consequence of that is if PodDisruptionBudget doesn't allow evicting a pod,
	// then NodeGroup update with node re-creation will hang on that pod eviction.
	// Note that this is different from `kubectl drain --timeout`, which gives up and returns an error.
	//
	// Duration as a string: possibly signed sequence of decimal numbers, each with optional fraction and a unit suffix, such as `300ms`, `-1.5h` or `2h45m`. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`, `d`.
	DrainTimeout *string `json:"drainTimeout,omitempty" tf:"drain_timeout,omitempty"`

	// (Attributes) :
	MaxSurge *StrategyMaxSurgeInitParameters `json:"maxSurge,omitempty" tf:"max_surge,omitempty"`

	// is also set to 0.
	MaxUnavailable *StrategyMaxUnavailableInitParameters `json:"maxUnavailable,omitempty" tf:"max_unavailable,omitempty"`
}

type NodeGroupStrategyObservation struct {

	// (String) :
	// :
	//
	// Maximum amount of time that the service will spend attempting to gracefully drain a node
	// (evicting its pods) before falling back to pod deletion.
	// A value of 0 (or when field is omitted) means no timeout: the node can be drained for an unlimited time.
	// Important consequence of that is if PodDisruptionBudget doesn't allow evicting a pod,
	// then NodeGroup update with node re-creation will hang on that pod eviction.
	// Note that this is different from `kubectl drain --timeout`, which gives up and returns an error.
	//
	// Duration as a string: possibly signed sequence of decimal numbers, each with optional fraction and a unit suffix, such as `300ms`, `-1.5h` or `2h45m`. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`, `d`.
	DrainTimeout *string `json:"drainTimeout,omitempty" tf:"drain_timeout,omitempty"`

	// (Attributes) :
	MaxSurge *StrategyMaxSurgeObservation `json:"maxSurge,omitempty" tf:"max_surge,omitempty"`

	// is also set to 0.
	MaxUnavailable *StrategyMaxUnavailableObservation `json:"maxUnavailable,omitempty" tf:"max_unavailable,omitempty"`
}

type NodeGroupStrategyParameters struct {

	// (String) :
	// :
	//
	// Maximum amount of time that the service will spend attempting to gracefully drain a node
	// (evicting its pods) before falling back to pod deletion.
	// A value of 0 (or when field is omitted) means no timeout: the node can be drained for an unlimited time.
	// Important consequence of that is if PodDisruptionBudget doesn't allow evicting a pod,
	// then NodeGroup update with node re-creation will hang on that pod eviction.
	// Note that this is different from `kubectl drain --timeout`, which gives up and returns an error.
	//
	// Duration as a string: possibly signed sequence of decimal numbers, each with optional fraction and a unit suffix, such as `300ms`, `-1.5h` or `2h45m`. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`, `d`.
	// +kubebuilder:validation:Optional
	DrainTimeout *string `json:"drainTimeout,omitempty" tf:"drain_timeout,omitempty"`

	// (Attributes) :
	// +kubebuilder:validation:Optional
	MaxSurge *StrategyMaxSurgeParameters `json:"maxSurge,omitempty" tf:"max_surge,omitempty"`

	// is also set to 0.
	// +kubebuilder:validation:Optional
	MaxUnavailable *StrategyMaxUnavailableParameters `json:"maxUnavailable,omitempty" tf:"max_unavailable,omitempty"`
}

type NvlinkInitParameters struct {

	// (String) Existing NVLInstanceGroup ID to use.
	// Existing NVLInstanceGroup ID to use.
	// +crossplane:generate:reference:type=github.com/upbound/provider-nebius/apis/namespaced/compute/v1beta1.NvlInstanceGroup
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id",true)
	NvlInstanceGroupID *string `json:"nvlInstanceGroupId,omitempty" tf:"nvl_instance_group_id,omitempty"`

	// Reference to a NvlInstanceGroup in compute to populate nvlInstanceGroupId.
	// +kubebuilder:validation:Optional
	NvlInstanceGroupIDRef *v1.NamespacedReference `json:"nvlInstanceGroupIdRef,omitempty" tf:"-"`

	// Selector for a NvlInstanceGroup in compute to populate nvlInstanceGroupId.
	// +kubebuilder:validation:Optional
	NvlInstanceGroupIDSelector *v1.NamespacedSelector `json:"nvlInstanceGroupIdSelector,omitempty" tf:"-"`
}

type NvlinkObservation struct {

	// (String) Existing NVLInstanceGroup ID to use.
	// Existing NVLInstanceGroup ID to use.
	NvlInstanceGroupID *string `json:"nvlInstanceGroupId,omitempty" tf:"nvl_instance_group_id,omitempty"`
}

type NvlinkParameters struct {

	// (String) Existing NVLInstanceGroup ID to use.
	// Existing NVLInstanceGroup ID to use.
	// +crossplane:generate:reference:type=github.com/upbound/provider-nebius/apis/namespaced/compute/v1beta1.NvlInstanceGroup
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id",true)
	// +kubebuilder:validation:Optional
	NvlInstanceGroupID *string `json:"nvlInstanceGroupId,omitempty" tf:"nvl_instance_group_id,omitempty"`

	// Reference to a NvlInstanceGroup in compute to populate nvlInstanceGroupId.
	// +kubebuilder:validation:Optional
	NvlInstanceGroupIDRef *v1.NamespacedReference `json:"nvlInstanceGroupIdRef,omitempty" tf:"-"`

	// Selector for a NvlInstanceGroup in compute to populate nvlInstanceGroupId.
	// +kubebuilder:validation:Optional
	NvlInstanceGroupIDSelector *v1.NamespacedSelector `json:"nvlInstanceGroupIdSelector,omitempty" tf:"-"`
}

type PassthroughGroupInitParameters struct {

	// (Boolean) :
	// :
	//
	// Passthrough local disks from the underlying host.
	//
	// Devices are expected to appear in the guest as NVMe devices (nvme0, nvme1, ...),
	// but the exact number depends on the preset.
	// Enabled only when this field is explicitly set.
	Requested *bool `json:"requested,omitempty" tf:"requested,omitempty"`
}

type PassthroughGroupObservation struct {

	// (Boolean) :
	// :
	//
	// Passthrough local disks from the underlying host.
	//
	// Devices are expected to appear in the guest as NVMe devices (nvme0, nvme1, ...),
	// but the exact number depends on the preset.
	// Enabled only when this field is explicitly set.
	Requested *bool `json:"requested,omitempty" tf:"requested,omitempty"`
}

type PassthroughGroupParameters struct {

	// (Boolean) :
	// :
	//
	// Passthrough local disks from the underlying host.
	//
	// Devices are expected to appear in the guest as NVMe devices (nvme0, nvme1, ...),
	// but the exact number depends on the preset.
	// Enabled only when this field is explicitly set.
	// +kubebuilder:validation:Optional
	Requested *bool `json:"requested,omitempty" tf:"requested,omitempty"`
}

type PreemptibleInitParameters struct {
}

type PreemptibleObservation struct {
}

type PreemptibleParameters struct {
}

type PublicIPAddressInitParameters struct {
}

type PublicIPAddressObservation struct {
}

type PublicIPAddressParameters struct {
}

type ReservationPolicyInitParameters struct {

	// (String) :
	// :
	//
	// #### Supported values
	//
	// Possible values:
	//
	// - `AUTO`:
	// 1) Will try to launch instance in any reservation_ids if provided.
	// 2) Will try to launch instance in any of the available capacity block.
	// 3) Will try to launch instance in PAYG if 1 & 2 are not satisfied.
	//
	// - `FORBID`:
	// The instance is launched only using on-demand (PAYG) capacity.
	// No attempt is made to find or use a Capacity Block.
	// It's an error to provide reservation_ids with policy = FORBID
	//
	// - `STRICT`:
	// 1) Will try to launch the instance in Capacity Blocks from reservation_ids if provided.
	// 2) If reservation_ids are not provided will try to launch instance in suitable & available Capacity Block.
	// 3) Fail otherwise.
	Policy *string `json:"policy,omitempty" tf:"policy,omitempty"`

	// (List of String) Capacity block groups, order matters
	// Capacity block groups, order matters
	ReservationIds []*string `json:"reservationIds,omitempty" tf:"reservation_ids,omitempty"`
}

type ReservationPolicyObservation struct {

	// (String) :
	// :
	//
	// #### Supported values
	//
	// Possible values:
	//
	// - `AUTO`:
	// 1) Will try to launch instance in any reservation_ids if provided.
	// 2) Will try to launch instance in any of the available capacity block.
	// 3) Will try to launch instance in PAYG if 1 & 2 are not satisfied.
	//
	// - `FORBID`:
	// The instance is launched only using on-demand (PAYG) capacity.
	// No attempt is made to find or use a Capacity Block.
	// It's an error to provide reservation_ids with policy = FORBID
	//
	// - `STRICT`:
	// 1) Will try to launch the instance in Capacity Blocks from reservation_ids if provided.
	// 2) If reservation_ids are not provided will try to launch instance in suitable & available Capacity Block.
	// 3) Fail otherwise.
	Policy *string `json:"policy,omitempty" tf:"policy,omitempty"`

	// (List of String) Capacity block groups, order matters
	// Capacity block groups, order matters
	ReservationIds []*string `json:"reservationIds,omitempty" tf:"reservation_ids,omitempty"`
}

type ReservationPolicyParameters struct {

	// (String) :
	// :
	//
	// #### Supported values
	//
	// Possible values:
	//
	// - `AUTO`:
	// 1) Will try to launch instance in any reservation_ids if provided.
	// 2) Will try to launch instance in any of the available capacity block.
	// 3) Will try to launch instance in PAYG if 1 & 2 are not satisfied.
	//
	// - `FORBID`:
	// The instance is launched only using on-demand (PAYG) capacity.
	// No attempt is made to find or use a Capacity Block.
	// It's an error to provide reservation_ids with policy = FORBID
	//
	// - `STRICT`:
	// 1) Will try to launch the instance in Capacity Blocks from reservation_ids if provided.
	// 2) If reservation_ids are not provided will try to launch instance in suitable & available Capacity Block.
	// 3) Fail otherwise.
	// +kubebuilder:validation:Optional
	Policy *string `json:"policy,omitempty" tf:"policy,omitempty"`

	// (List of String) Capacity block groups, order matters
	// Capacity block groups, order matters
	// +kubebuilder:validation:Optional
	ReservationIds []*string `json:"reservationIds,omitempty" tf:"reservation_ids,omitempty"`
}

type ResourcesInitParameters struct {

	// (String)
	Platform *string `json:"platform,omitempty" tf:"platform,omitempty"`

	// (String)
	Preset *string `json:"preset,omitempty" tf:"preset,omitempty"`
}

type ResourcesObservation struct {

	// (String)
	Platform *string `json:"platform,omitempty" tf:"platform,omitempty"`

	// (String)
	Preset *string `json:"preset,omitempty" tf:"preset,omitempty"`
}

type ResourcesParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	Platform *string `json:"platform" tf:"platform,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Preset *string `json:"preset,omitempty" tf:"preset,omitempty"`
}

type SecurityGroupsInitParameters struct {

	// (String) Identifier for the resource, unique for its resource type.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type SecurityGroupsObservation struct {

	// (String) Identifier for the resource, unique for its resource type.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type SecurityGroupsParameters struct {

	// (String) Identifier for the resource, unique for its resource type.
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type StatusEventsInitParameters struct {
}

type StatusEventsObservation struct {

	// (String) :
	// :
	//
	// # Time of the first occurrence of a recurrent event
	//
	// A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
	FirstOccurredAt *string `json:"firstOccurredAt,omitempty" tf:"first_occurred_at,omitempty"`

	// (Attributes) :
	LastOccurrence *EventsLastOccurrenceObservation `json:"lastOccurrence,omitempty" tf:"last_occurrence,omitempty"`

	// (Number) The number of times this event has occurred between first_occurred_at and last_occurrence.occurred_at. Must be > 0
	// The number of times this event has occurred between `first_occurred_at` and `last_occurrence.occurred_at`. Must be > 0
	OccurrenceCount *float64 `json:"occurrenceCount,omitempty" tf:"occurrence_count,omitempty"`
}

type StatusEventsParameters struct {
}

type StrategyInitParameters struct {
}

type StrategyMaxSurgeInitParameters struct {

	// (Number) Cannot be set alongside percent.
	// *Cannot be set alongside percent.*
	Count *float64 `json:"count,omitempty" tf:"count,omitempty"`

	// (Number) Cannot be set alongside count.
	// *Cannot be set alongside count.*
	Percent *float64 `json:"percent,omitempty" tf:"percent,omitempty"`
}

type StrategyMaxSurgeObservation struct {

	// (Number) Cannot be set alongside percent.
	// *Cannot be set alongside percent.*
	Count *float64 `json:"count,omitempty" tf:"count,omitempty"`

	// (Number) Cannot be set alongside count.
	// *Cannot be set alongside count.*
	Percent *float64 `json:"percent,omitempty" tf:"percent,omitempty"`
}

type StrategyMaxSurgeParameters struct {

	// (Number) Cannot be set alongside percent.
	// *Cannot be set alongside percent.*
	// +kubebuilder:validation:Optional
	Count *float64 `json:"count,omitempty" tf:"count,omitempty"`

	// (Number) Cannot be set alongside count.
	// *Cannot be set alongside count.*
	// +kubebuilder:validation:Optional
	Percent *float64 `json:"percent,omitempty" tf:"percent,omitempty"`
}

type StrategyMaxUnavailableInitParameters struct {

	// (Number) Cannot be set alongside percent.
	// *Cannot be set alongside percent.*
	Count *float64 `json:"count,omitempty" tf:"count,omitempty"`

	// (Number) Cannot be set alongside count.
	// *Cannot be set alongside count.*
	Percent *float64 `json:"percent,omitempty" tf:"percent,omitempty"`
}

type StrategyMaxUnavailableObservation struct {

	// (Number) Cannot be set alongside percent.
	// *Cannot be set alongside percent.*
	Count *float64 `json:"count,omitempty" tf:"count,omitempty"`

	// (Number) Cannot be set alongside count.
	// *Cannot be set alongside count.*
	Percent *float64 `json:"percent,omitempty" tf:"percent,omitempty"`
}

type StrategyMaxUnavailableParameters struct {

	// (Number) Cannot be set alongside percent.
	// *Cannot be set alongside percent.*
	// +kubebuilder:validation:Optional
	Count *float64 `json:"count,omitempty" tf:"count,omitempty"`

	// (Number) Cannot be set alongside count.
	// *Cannot be set alongside count.*
	// +kubebuilder:validation:Optional
	Percent *float64 `json:"percent,omitempty" tf:"percent,omitempty"`
}

type StrategyObservation struct {

	// (String) :
	// :
	//
	// Maximum amount of time that the service will spend attempting to gracefully drain a node
	// (evicting its pods) before falling back to pod deletion.
	// A value of 0 (or when field is omitted) means no timeout: the node can be drained for an unlimited time.
	// Important consequence of that is if PodDisruptionBudget doesn't allow evicting a pod,
	// then NodeGroup update with node re-creation will hang on that pod eviction.
	// Note that this is different from `kubectl drain --timeout`, which gives up and returns an error.
	//
	// Duration as a string: possibly signed sequence of decimal numbers, each with optional fraction and a unit suffix, such as `300ms`, `-1.5h` or `2h45m`. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`, `d`.
	DrainTimeout *string `json:"drainTimeout,omitempty" tf:"drain_timeout,omitempty"`

	// (Attributes) :
	MaxSurge *MaxSurgeObservation `json:"maxSurge,omitempty" tf:"max_surge,omitempty"`

	// is also set to 0.
	MaxUnavailable *MaxUnavailableObservation `json:"maxUnavailable,omitempty" tf:"max_unavailable,omitempty"`
}

type StrategyParameters struct {
}

type TaintsInitParameters struct {

	// (String) :
	// :
	//
	// #### Supported values
	//
	// Possible values:
	//
	// - `EFFECT_UNSPECIFIED`
	// - `NO_EXECUTE`
	// - `NO_SCHEDULE`
	// - `PREFER_NO_SCHEDULE`
	Effect *string `json:"effect,omitempty" tf:"effect,omitempty"`

	// (String)
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type TaintsObservation struct {

	// (String) :
	// :
	//
	// #### Supported values
	//
	// Possible values:
	//
	// - `EFFECT_UNSPECIFIED`
	// - `NO_EXECUTE`
	// - `NO_SCHEDULE`
	// - `PREFER_NO_SCHEDULE`
	Effect *string `json:"effect,omitempty" tf:"effect,omitempty"`

	// (String)
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type TaintsParameters struct {

	// (String) :
	// :
	//
	// #### Supported values
	//
	// Possible values:
	//
	// - `EFFECT_UNSPECIFIED`
	// - `NO_EXECUTE`
	// - `NO_SCHEDULE`
	// - `PREFER_NO_SCHEDULE`
	// +kubebuilder:validation:Optional
	Effect *string `json:"effect" tf:"effect,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Key *string `json:"key" tf:"key,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`
}

type TemplateInitParameters struct {

	// (Attributes) Parameters of a Node Nebius Compute Instance boot disk. (see below for nested schema)
	BootDisk *BootDiskInitParameters `json:"bootDisk,omitempty" tf:"boot_disk,omitempty"`

	// (String, Sensitive) :
	// :
	//
	// cloud-init user-data
	// Should contain at least one SSH key.
	CloudInitUserDataSecretRef *v1.LocalSecretKeySelector `json:"cloudInitUserDataSecretRef,omitempty" tf:"-"`

	// (Attributes List) :
	Filesystems []FilesystemsInitParameters `json:"filesystems,omitempty" tf:"filesystems,omitempty"`

	// (Attributes) Nebius Compute GPUCluster ID that will be attached to node. (see below for nested schema)
	GpuCluster *GpuClusterInitParameters `json:"gpuCluster,omitempty" tf:"gpu_cluster,omitempty"`

	// (Attributes) :
	GpuSettings *GpuSettingsInitParameters `json:"gpuSettings,omitempty" tf:"gpu_settings,omitempty"`

	// (Attributes) :
	LocalDisks *LocalDisksInitParameters `json:"localDisks,omitempty" tf:"local_disks,omitempty"`

	// (Number) :
	// :
	//
	// The maximum number of Pods per node for your cluster. If omitted, MK8S assigns the default value of 110. When you
	// configure the maximum number of Pods per node for the cluster, MK8S uses this value to allocate a CIDR range for every node
	// in group. The node CIDR prefix is calculated as `32 - ceil(log2(2 * max_pods))`, i.e. the smallest IPv4 subnet whose total address
	// count is at least `2 * max_pods`. Not all IPs are usable for workload Pods because some of them are consumed by system Pods.
	MaxPods *float64 `json:"maxPods,omitempty" tf:"max_pods,omitempty"`

	// (Attributes) :
	Metadata *TemplateMetadataInitParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// (Attributes List) (see below for nested schema)
	NetworkInterfaces []NetworkInterfacesInitParameters `json:"networkInterfaces,omitempty" tf:"network_interfaces,omitempty"`

	// (Attributes) NVLinkSpec configures NVLink settings for the NodeGroup. (see below for nested schema)
	Nvlink *NvlinkInitParameters `json:"nvlink,omitempty" tf:"nvlink,omitempty"`

	// (String) :
	// :
	//
	// OS version that will be used to create the boot disk of Compute Instances in the NodeGroup.
	// Supported platform / Kubernetes version / OS / driver presets combinations
	// * `gpu-l40s-a`, `gpu-l40s-d`, `gpu-h100-sxm`, `gpu-h200-sxm`, `cpu-e1`, `cpu-e2`, `cpu-d3`:
	// * `drivers_preset`: `""`
	// * `version`: 1.30 → `"ubuntu22.04"`
	// * `version`: 1.31 → `"ubuntu22.04"` (default), `"ubuntu24.04"`
	// * `gpu-l40s-a`, `gpu-l40s-d`, `gpu-h100-sxm`, `gpu-h200-sxm`:
	// * `drivers_preset`: `"cuda12"` (CUDA 12.4)
	// * `version`: 1.30, 1.31 → `"ubuntu22.04"`
	// * `drivers_preset`: `"cuda12.4"`
	// * `version`: 1.31 → `"ubuntu22.04"`
	// * `drivers_preset`: `"cuda12.8"`
	// * `version`: 1.31 → `"ubuntu24.04"`
	// * `gpu-b200-sxm`:
	// * `drivers_preset`: `""`
	// * `version`: 1.30, 1.31 → `"ubuntu24.04"`
	// * `drivers_preset`: `"cuda12"` (CUDA 12.8)
	// * `version`: 1.30, 1.31 → `"ubuntu24.04"`
	// * `drivers_preset`: `"cuda12.8"`
	// * `version`: 1.31 → `"ubuntu24.04"`
	// * `gpu-b200-sxm-a`:
	// * `drivers_preset`: `""`
	// * `version`: 1.31 → `"ubuntu24.04"`
	// * `drivers_preset`: `"cuda12.8"`
	// * `version`: 1.31 → `"ubuntu24.04"`
	Os *string `json:"os,omitempty" tf:"os,omitempty"`

	// (Attributes) :
	Preemptible *PreemptibleInitParameters `json:"preemptible,omitempty" tf:"preemptible,omitempty"`

	// (Attributes) :
	ReservationPolicy *ReservationPolicyInitParameters `json:"reservationPolicy,omitempty" tf:"reservation_policy,omitempty"`

	// (Attributes) Resources that will have Nebius Compute Instance where Node kubelet will run. (see below for nested schema)
	Resources *ResourcesInitParameters `json:"resources,omitempty" tf:"resources,omitempty"`

	// (String) :
	// :
	//
	// the Nebius service account whose credentials will be available on the nodes of the group.
	// With these credentials, it is possible to make `nebius` CLI or public API requests from the nodes
	// without the need for extra authentication.
	// This service account is also used to make requests to container registry.
	//
	// `resource.serviceaccount.issueAccessToken` permission is required to use this field.
	// +crossplane:generate:reference:type=github.com/upbound/provider-nebius/apis/namespaced/iam/v1beta1.ServiceAccount
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id",true)
	ServiceAccountID *string `json:"serviceAccountId,omitempty" tf:"service_account_id,omitempty"`

	// Reference to a ServiceAccount in iam to populate serviceAccountId.
	// +kubebuilder:validation:Optional
	ServiceAccountIDRef *v1.NamespacedReference `json:"serviceAccountIdRef,omitempty" tf:"-"`

	// Selector for a ServiceAccount in iam to populate serviceAccountId.
	// +kubebuilder:validation:Optional
	ServiceAccountIDSelector *v1.NamespacedSelector `json:"serviceAccountIdSelector,omitempty" tf:"-"`

	// (Attributes List) :
	Taints []TaintsInitParameters `json:"taints,omitempty" tf:"taints,omitempty"`
}

type TemplateMetadataInitParameters struct {

	// (Map of String) Labels associated with the resource.
	// :
	//
	// Kubernetes Node labels.
	//
	// Keys and values must follow Kubernetes label syntax:
	// https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
	//
	// For now change will not be propagated to existing nodes, so will be applied only to Kubernetes Nodes created after the field change.
	// That behavior may change later.
	// So, for now you will need to manually set them to existing nodes, if that is needed.
	//
	// System labels containing "kubernetes.io" and "k8s.io" will be ignored.
	// Field change will NOT trigger NodeGroup roll out.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`
}

type TemplateMetadataObservation struct {

	// (Map of String) Labels associated with the resource.
	// :
	//
	// Kubernetes Node labels.
	//
	// Keys and values must follow Kubernetes label syntax:
	// https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
	//
	// For now change will not be propagated to existing nodes, so will be applied only to Kubernetes Nodes created after the field change.
	// That behavior may change later.
	// So, for now you will need to manually set them to existing nodes, if that is needed.
	//
	// System labels containing "kubernetes.io" and "k8s.io" will be ignored.
	// Field change will NOT trigger NodeGroup roll out.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`
}

type TemplateMetadataParameters struct {

	// (Map of String) Labels associated with the resource.
	// :
	//
	// Kubernetes Node labels.
	//
	// Keys and values must follow Kubernetes label syntax:
	// https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
	//
	// For now change will not be propagated to existing nodes, so will be applied only to Kubernetes Nodes created after the field change.
	// That behavior may change later.
	// So, for now you will need to manually set them to existing nodes, if that is needed.
	//
	// System labels containing "kubernetes.io" and "k8s.io" will be ignored.
	// Field change will NOT trigger NodeGroup roll out.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`
}

type TemplateObservation struct {

	// (Attributes) Parameters of a Node Nebius Compute Instance boot disk. (see below for nested schema)
	BootDisk *BootDiskObservation `json:"bootDisk,omitempty" tf:"boot_disk,omitempty"`

	// (Attributes List) :
	Filesystems []FilesystemsObservation `json:"filesystems,omitempty" tf:"filesystems,omitempty"`

	// (Attributes) Nebius Compute GPUCluster ID that will be attached to node. (see below for nested schema)
	GpuCluster *GpuClusterObservation `json:"gpuCluster,omitempty" tf:"gpu_cluster,omitempty"`

	// (Attributes) :
	GpuSettings *GpuSettingsObservation `json:"gpuSettings,omitempty" tf:"gpu_settings,omitempty"`

	// (Attributes) :
	LocalDisks *LocalDisksObservation `json:"localDisks,omitempty" tf:"local_disks,omitempty"`

	// (Number) :
	// :
	//
	// The maximum number of Pods per node for your cluster. If omitted, MK8S assigns the default value of 110. When you
	// configure the maximum number of Pods per node for the cluster, MK8S uses this value to allocate a CIDR range for every node
	// in group. The node CIDR prefix is calculated as `32 - ceil(log2(2 * max_pods))`, i.e. the smallest IPv4 subnet whose total address
	// count is at least `2 * max_pods`. Not all IPs are usable for workload Pods because some of them are consumed by system Pods.
	MaxPods *float64 `json:"maxPods,omitempty" tf:"max_pods,omitempty"`

	// (Attributes) :
	Metadata *TemplateMetadataObservation `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// (Attributes List) (see below for nested schema)
	NetworkInterfaces []NetworkInterfacesObservation `json:"networkInterfaces,omitempty" tf:"network_interfaces,omitempty"`

	// (Attributes) NVLinkSpec configures NVLink settings for the NodeGroup. (see below for nested schema)
	Nvlink *NvlinkObservation `json:"nvlink,omitempty" tf:"nvlink,omitempty"`

	// (String) :
	// :
	//
	// OS version that will be used to create the boot disk of Compute Instances in the NodeGroup.
	// Supported platform / Kubernetes version / OS / driver presets combinations
	// * `gpu-l40s-a`, `gpu-l40s-d`, `gpu-h100-sxm`, `gpu-h200-sxm`, `cpu-e1`, `cpu-e2`, `cpu-d3`:
	// * `drivers_preset`: `""`
	// * `version`: 1.30 → `"ubuntu22.04"`
	// * `version`: 1.31 → `"ubuntu22.04"` (default), `"ubuntu24.04"`
	// * `gpu-l40s-a`, `gpu-l40s-d`, `gpu-h100-sxm`, `gpu-h200-sxm`:
	// * `drivers_preset`: `"cuda12"` (CUDA 12.4)
	// * `version`: 1.30, 1.31 → `"ubuntu22.04"`
	// * `drivers_preset`: `"cuda12.4"`
	// * `version`: 1.31 → `"ubuntu22.04"`
	// * `drivers_preset`: `"cuda12.8"`
	// * `version`: 1.31 → `"ubuntu24.04"`
	// * `gpu-b200-sxm`:
	// * `drivers_preset`: `""`
	// * `version`: 1.30, 1.31 → `"ubuntu24.04"`
	// * `drivers_preset`: `"cuda12"` (CUDA 12.8)
	// * `version`: 1.30, 1.31 → `"ubuntu24.04"`
	// * `drivers_preset`: `"cuda12.8"`
	// * `version`: 1.31 → `"ubuntu24.04"`
	// * `gpu-b200-sxm-a`:
	// * `drivers_preset`: `""`
	// * `version`: 1.31 → `"ubuntu24.04"`
	// * `drivers_preset`: `"cuda12.8"`
	// * `version`: 1.31 → `"ubuntu24.04"`
	Os *string `json:"os,omitempty" tf:"os,omitempty"`

	// (Attributes) :
	Preemptible *PreemptibleParameters `json:"preemptible,omitempty" tf:"preemptible,omitempty"`

	// (Attributes) :
	ReservationPolicy *ReservationPolicyObservation `json:"reservationPolicy,omitempty" tf:"reservation_policy,omitempty"`

	// (Attributes) Resources that will have Nebius Compute Instance where Node kubelet will run. (see below for nested schema)
	Resources *ResourcesObservation `json:"resources,omitempty" tf:"resources,omitempty"`

	// (String) :
	// :
	//
	// the Nebius service account whose credentials will be available on the nodes of the group.
	// With these credentials, it is possible to make `nebius` CLI or public API requests from the nodes
	// without the need for extra authentication.
	// This service account is also used to make requests to container registry.
	//
	// `resource.serviceaccount.issueAccessToken` permission is required to use this field.
	ServiceAccountID *string `json:"serviceAccountId,omitempty" tf:"service_account_id,omitempty"`

	// (Attributes List) :
	Taints []TaintsObservation `json:"taints,omitempty" tf:"taints,omitempty"`
}

type TemplateParameters struct {

	// (Attributes) Parameters of a Node Nebius Compute Instance boot disk. (see below for nested schema)
	// +kubebuilder:validation:Optional
	BootDisk *BootDiskParameters `json:"bootDisk,omitempty" tf:"boot_disk,omitempty"`

	// (String, Sensitive) :
	// :
	//
	// cloud-init user-data
	// Should contain at least one SSH key.
	// +kubebuilder:validation:Optional
	CloudInitUserDataSecretRef *v1.LocalSecretKeySelector `json:"cloudInitUserDataSecretRef,omitempty" tf:"-"`

	// (Attributes List) :
	// +kubebuilder:validation:Optional
	Filesystems []FilesystemsParameters `json:"filesystems,omitempty" tf:"filesystems,omitempty"`

	// (Attributes) Nebius Compute GPUCluster ID that will be attached to node. (see below for nested schema)
	// +kubebuilder:validation:Optional
	GpuCluster *GpuClusterParameters `json:"gpuCluster,omitempty" tf:"gpu_cluster,omitempty"`

	// (Attributes) :
	// +kubebuilder:validation:Optional
	GpuSettings *GpuSettingsParameters `json:"gpuSettings,omitempty" tf:"gpu_settings,omitempty"`

	// (Attributes) :
	// +kubebuilder:validation:Optional
	LocalDisks *LocalDisksParameters `json:"localDisks,omitempty" tf:"local_disks,omitempty"`

	// (Number) :
	// :
	//
	// The maximum number of Pods per node for your cluster. If omitted, MK8S assigns the default value of 110. When you
	// configure the maximum number of Pods per node for the cluster, MK8S uses this value to allocate a CIDR range for every node
	// in group. The node CIDR prefix is calculated as `32 - ceil(log2(2 * max_pods))`, i.e. the smallest IPv4 subnet whose total address
	// count is at least `2 * max_pods`. Not all IPs are usable for workload Pods because some of them are consumed by system Pods.
	// +kubebuilder:validation:Optional
	MaxPods *float64 `json:"maxPods,omitempty" tf:"max_pods,omitempty"`

	// (Attributes) :
	// +kubebuilder:validation:Optional
	Metadata *TemplateMetadataParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// (Attributes List) (see below for nested schema)
	// +kubebuilder:validation:Optional
	NetworkInterfaces []NetworkInterfacesParameters `json:"networkInterfaces,omitempty" tf:"network_interfaces,omitempty"`

	// (Attributes) NVLinkSpec configures NVLink settings for the NodeGroup. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Nvlink *NvlinkParameters `json:"nvlink,omitempty" tf:"nvlink,omitempty"`

	// (String) :
	// :
	//
	// OS version that will be used to create the boot disk of Compute Instances in the NodeGroup.
	// Supported platform / Kubernetes version / OS / driver presets combinations
	// * `gpu-l40s-a`, `gpu-l40s-d`, `gpu-h100-sxm`, `gpu-h200-sxm`, `cpu-e1`, `cpu-e2`, `cpu-d3`:
	// * `drivers_preset`: `""`
	// * `version`: 1.30 → `"ubuntu22.04"`
	// * `version`: 1.31 → `"ubuntu22.04"` (default), `"ubuntu24.04"`
	// * `gpu-l40s-a`, `gpu-l40s-d`, `gpu-h100-sxm`, `gpu-h200-sxm`:
	// * `drivers_preset`: `"cuda12"` (CUDA 12.4)
	// * `version`: 1.30, 1.31 → `"ubuntu22.04"`
	// * `drivers_preset`: `"cuda12.4"`
	// * `version`: 1.31 → `"ubuntu22.04"`
	// * `drivers_preset`: `"cuda12.8"`
	// * `version`: 1.31 → `"ubuntu24.04"`
	// * `gpu-b200-sxm`:
	// * `drivers_preset`: `""`
	// * `version`: 1.30, 1.31 → `"ubuntu24.04"`
	// * `drivers_preset`: `"cuda12"` (CUDA 12.8)
	// * `version`: 1.30, 1.31 → `"ubuntu24.04"`
	// * `drivers_preset`: `"cuda12.8"`
	// * `version`: 1.31 → `"ubuntu24.04"`
	// * `gpu-b200-sxm-a`:
	// * `drivers_preset`: `""`
	// * `version`: 1.31 → `"ubuntu24.04"`
	// * `drivers_preset`: `"cuda12.8"`
	// * `version`: 1.31 → `"ubuntu24.04"`
	// +kubebuilder:validation:Optional
	Os *string `json:"os,omitempty" tf:"os,omitempty"`

	// (Attributes) :
	// +kubebuilder:validation:Optional
	Preemptible *PreemptibleParameters `json:"preemptible,omitempty" tf:"preemptible,omitempty"`

	// (Attributes) :
	// +kubebuilder:validation:Optional
	ReservationPolicy *ReservationPolicyParameters `json:"reservationPolicy,omitempty" tf:"reservation_policy,omitempty"`

	// (Attributes) Resources that will have Nebius Compute Instance where Node kubelet will run. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Resources *ResourcesParameters `json:"resources" tf:"resources,omitempty"`

	// (String) :
	// :
	//
	// the Nebius service account whose credentials will be available on the nodes of the group.
	// With these credentials, it is possible to make `nebius` CLI or public API requests from the nodes
	// without the need for extra authentication.
	// This service account is also used to make requests to container registry.
	//
	// `resource.serviceaccount.issueAccessToken` permission is required to use this field.
	// +crossplane:generate:reference:type=github.com/upbound/provider-nebius/apis/namespaced/iam/v1beta1.ServiceAccount
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id",true)
	// +kubebuilder:validation:Optional
	ServiceAccountID *string `json:"serviceAccountId,omitempty" tf:"service_account_id,omitempty"`

	// Reference to a ServiceAccount in iam to populate serviceAccountId.
	// +kubebuilder:validation:Optional
	ServiceAccountIDRef *v1.NamespacedReference `json:"serviceAccountIdRef,omitempty" tf:"-"`

	// Selector for a ServiceAccount in iam to populate serviceAccountId.
	// +kubebuilder:validation:Optional
	ServiceAccountIDSelector *v1.NamespacedSelector `json:"serviceAccountIdSelector,omitempty" tf:"-"`

	// (Attributes List) :
	// +kubebuilder:validation:Optional
	Taints []TaintsParameters `json:"taints,omitempty" tf:"taints,omitempty"`
}

// NodeGroupSpec defines the desired state of NodeGroup
type NodeGroupSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            NodeGroupParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider NodeGroupInitParameters `json:"initProvider,omitempty"`
}

// NodeGroupStatus defines the observed state of NodeGroup.
type NodeGroupStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        NodeGroupObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// NodeGroup is the Schema for the NodeGroups API. NodeGroup represents Kubernetes node pool - set of worker machines having the same configuration. A Node is a Nebius Compute Instance created in Cluster.metadata.parent_id container, running kubelet that registers in Kubernetes API and a Node object created.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,nebius}
type NodeGroup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.template) || (has(self.initProvider) && has(self.initProvider.template))",message="spec.forProvider.template is a required parameter"
	Spec   NodeGroupSpec   `json:"spec"`
	Status NodeGroupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NodeGroupList contains a list of NodeGroups
type NodeGroupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NodeGroup `json:"items"`
}

// Repository type metadata.
var (
	NodeGroup_Kind             = "NodeGroup"
	NodeGroup_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: NodeGroup_Kind}.String()
	NodeGroup_KindAPIVersion   = NodeGroup_Kind + "." + CRDGroupVersion.String()
	NodeGroup_GroupVersionKind = CRDGroupVersion.WithKind(NodeGroup_Kind)
)

func init() {
	SchemeBuilder.Register(&NodeGroup{}, &NodeGroupList{})
}
