apiVersion: mysteryboxv1.nebius.m.upbound.io/v1beta1
kind: SecretVersion
metadata:
  annotations:
    meta.upbound.io/example-id: mysteryboxv1/v1beta1/secretversion
  labels:
    testing.upbound.io/example-name: default
  name: default
  namespace: upbound-system
spec:
  forProvider:
    parentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    payload:
      - key: password
        stringValueSecretRef:
          name: mysterybox-payload
          key: payload-value
    setPrimary: true

---

apiVersion: mysteryboxv1.nebius.m.upbound.io/v1beta1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: mysteryboxv1/v1beta1/secretversion
  labels:
    testing.upbound.io/example-name: default
  name: default
  namespace: upbound-system
spec:
  forProvider:
    name: mysteryboxv1secret
    parentId: ${data.nebius_project_id}

---

apiVersion: v1
kind: Secret
metadata:
  name: mysterybox-payload
  namespace: upbound-system
type: Opaque
stringData:
  payload-value: example-secret-value
