// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type DiskEncryptionInitParameters struct {

	// (String) :
	// :
	//
	// #### Supported values
	//
	// Possible values:
	//
	// - `DISK_ENCRYPTION_UNSPECIFIED` - No encryption is applied unless explicitly specified.
	// - `DISK_ENCRYPTION_MANAGED`:
	// Enables encryption using the platform's default root key from KMS.
	// Available for disks with NETWORK_SSD_NON_REPLICATED and NETWORK_SSD_IO_M3 types only.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type DiskEncryptionObservation struct {

	// (String) :
	// :
	//
	// #### Supported values
	//
	// Possible values:
	//
	// - `DISK_ENCRYPTION_UNSPECIFIED` - No encryption is applied unless explicitly specified.
	// - `DISK_ENCRYPTION_MANAGED`:
	// Enables encryption using the platform's default root key from KMS.
	// Available for disks with NETWORK_SSD_NON_REPLICATED and NETWORK_SSD_IO_M3 types only.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type DiskEncryptionParameters struct {

	// (String) :
	// :
	//
	// #### Supported values
	//
	// Possible values:
	//
	// - `DISK_ENCRYPTION_UNSPECIFIED` - No encryption is applied unless explicitly specified.
	// - `DISK_ENCRYPTION_MANAGED`:
	// Enables encryption using the platform's default root key from KMS.
	// Available for disks with NETWORK_SSD_NON_REPLICATED and NETWORK_SSD_IO_M3 types only.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type DiskInitParameters struct {

	// (Number) :
	// :
	//
	// Block size in bytes.
	// The block size must be a power of two between 4096 bytes (4 KiB) and 131072 bytes (128 KiB).
	// The default value is 4096 bytes (4 KiB).
	BlockSizeBytes *float64 `json:"blockSizeBytes,omitempty" tf:"block_size_bytes,omitempty"`

	// (Attributes) Defines how data on the disk is encrypted. By default, no encryption is applied. (see below for nested schema)
	DiskEncryption *DiskEncryptionInitParameters `json:"diskEncryption,omitempty" tf:"disk_encryption,omitempty"`

	// (Boolean) Prevents deletion whilst set
	// Prevents deletion whilst set
	ForbidDeletion *bool `json:"forbidDeletion,omitempty" tf:"forbid_deletion,omitempty"`

	// (Map of String) :
	// :
	//
	// Labels associated with the resource.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (Attributes) :
	Metadata *MetadataInitParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// (String) Human readable name for the resource.
	// Human readable name for the resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Identifier of the parent resource to which the resource belongs.
	// Identifier of the parent resource to which the resource belongs.
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// (Number) Cannot be set alongside size_kibibytes, size_mebibytes or size_gibibytes.
	// *Cannot be set alongside size_kibibytes, size_mebibytes or size_gibibytes.*
	SizeBytes *float64 `json:"sizeBytes,omitempty" tf:"size_bytes,omitempty"`

	// (Number) Cannot be set alongside size_bytes, size_kibibytes or size_mebibytes.
	// *Cannot be set alongside size_bytes, size_kibibytes or size_mebibytes.*
	SizeGibibytes *float64 `json:"sizeGibibytes,omitempty" tf:"size_gibibytes,omitempty"`

	// (Number) Cannot be set alongside size_bytes, size_mebibytes or size_gibibytes.
	// *Cannot be set alongside size_bytes, size_mebibytes or size_gibibytes.*
	SizeKibibytes *float64 `json:"sizeKibibytes,omitempty" tf:"size_kibibytes,omitempty"`

	// (Number) Cannot be set alongside size_bytes, size_kibibytes or size_gibibytes.
	// *Cannot be set alongside size_bytes, size_kibibytes or size_gibibytes.*
	SizeMebibytes *float64 `json:"sizeMebibytes,omitempty" tf:"size_mebibytes,omitempty"`

	// (Attributes) Cannot be set alongside source_image_id. (see below for nested schema)
	SourceImageFamily *SourceImageFamilyInitParameters `json:"sourceImageFamily,omitempty" tf:"source_image_family,omitempty"`

	// (String) Cannot be set alongside source_image_family.
	// *Cannot be set alongside source_image_family.*
	SourceImageID *string `json:"sourceImageId,omitempty" tf:"source_image_id,omitempty"`

	// (String) :
	// :
	//
	// The type of disk defines the performance and reliability characteristics of the block device.
	// For details, see https://docs.nebius.com/compute/storage/types#disks-types
	//
	// #### Supported values
	//
	// the list of available types will be clarified later, it is not final version
	// Possible values:
	//
	// - `UNSPECIFIED`
	// - `NETWORK_SSD`
	// - `NETWORK_HDD`
	// - `NETWORK_SSD_NON_REPLICATED`
	// - `NETWORK_SSD_IO_M3`
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type DiskObservation struct {

	// (Number) :
	// :
	//
	// Block size in bytes.
	// The block size must be a power of two between 4096 bytes (4 KiB) and 131072 bytes (128 KiB).
	// The default value is 4096 bytes (4 KiB).
	BlockSizeBytes *float64 `json:"blockSizeBytes,omitempty" tf:"block_size_bytes,omitempty"`

	// (String) :
	// :
	//
	// Timestamp indicating when the resource was created.
	//
	// A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (Attributes) Defines how data on the disk is encrypted. By default, no encryption is applied. (see below for nested schema)
	DiskEncryption *DiskEncryptionObservation `json:"diskEncryption,omitempty" tf:"disk_encryption,omitempty"`

	// (Boolean) Prevents deletion whilst set
	// Prevents deletion whilst set
	ForbidDeletion *bool `json:"forbidDeletion,omitempty" tf:"forbid_deletion,omitempty"`

	// (String) Identifier for the resource, unique for its resource type.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Map of String) :
	// :
	//
	// Labels associated with the resource.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (Attributes) :
	Metadata *MetadataParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// (String) Human readable name for the resource.
	// Human readable name for the resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Identifier of the parent resource to which the resource belongs.
	// Identifier of the parent resource to which the resource belongs.
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// (Number) :
	// :
	//
	// Version of the resource for safe concurrent modifications and consistent reads.
	// Positive and monotonically increases on each resource spec change (but *not* on each change of the
	// resource's container(s) or status).
	// Service allows zero value or current.
	ResourceVersion *float64 `json:"resourceVersion,omitempty" tf:"resource_version,omitempty"`

	// (Number) Cannot be set alongside size_kibibytes, size_mebibytes or size_gibibytes.
	// *Cannot be set alongside size_kibibytes, size_mebibytes or size_gibibytes.*
	SizeBytes *float64 `json:"sizeBytes,omitempty" tf:"size_bytes,omitempty"`

	// (Number) Cannot be set alongside size_bytes, size_kibibytes or size_mebibytes.
	// *Cannot be set alongside size_bytes, size_kibibytes or size_mebibytes.*
	SizeGibibytes *float64 `json:"sizeGibibytes,omitempty" tf:"size_gibibytes,omitempty"`

	// (Number) Cannot be set alongside size_bytes, size_mebibytes or size_gibibytes.
	// *Cannot be set alongside size_bytes, size_mebibytes or size_gibibytes.*
	SizeKibibytes *float64 `json:"sizeKibibytes,omitempty" tf:"size_kibibytes,omitempty"`

	// (Number) Cannot be set alongside size_bytes, size_kibibytes or size_gibibytes.
	// *Cannot be set alongside size_bytes, size_kibibytes or size_gibibytes.*
	SizeMebibytes *float64 `json:"sizeMebibytes,omitempty" tf:"size_mebibytes,omitempty"`

	// (Attributes) Cannot be set alongside source_image_id. (see below for nested schema)
	SourceImageFamily *SourceImageFamilyObservation `json:"sourceImageFamily,omitempty" tf:"source_image_family,omitempty"`

	// (String) Cannot be set alongside source_image_family.
	// *Cannot be set alongside source_image_family.*
	SourceImageID *string `json:"sourceImageId,omitempty" tf:"source_image_id,omitempty"`

	// (Attributes) (see below for nested schema)
	Status *StatusObservation `json:"status,omitempty" tf:"status,omitempty"`

	// (String) :
	// :
	//
	// The type of disk defines the performance and reliability characteristics of the block device.
	// For details, see https://docs.nebius.com/compute/storage/types#disks-types
	//
	// #### Supported values
	//
	// the list of available types will be clarified later, it is not final version
	// Possible values:
	//
	// - `UNSPECIFIED`
	// - `NETWORK_SSD`
	// - `NETWORK_HDD`
	// - `NETWORK_SSD_NON_REPLICATED`
	// - `NETWORK_SSD_IO_M3`
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) :
	// :
	//
	// Timestamp indicating when the resource was last updated.
	//
	// A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type DiskParameters struct {

	// (Number) :
	// :
	//
	// Block size in bytes.
	// The block size must be a power of two between 4096 bytes (4 KiB) and 131072 bytes (128 KiB).
	// The default value is 4096 bytes (4 KiB).
	// +kubebuilder:validation:Optional
	BlockSizeBytes *float64 `json:"blockSizeBytes,omitempty" tf:"block_size_bytes,omitempty"`

	// (Attributes) Defines how data on the disk is encrypted. By default, no encryption is applied. (see below for nested schema)
	// +kubebuilder:validation:Optional
	DiskEncryption *DiskEncryptionParameters `json:"diskEncryption,omitempty" tf:"disk_encryption,omitempty"`

	// (Boolean) Prevents deletion whilst set
	// Prevents deletion whilst set
	// +kubebuilder:validation:Optional
	ForbidDeletion *bool `json:"forbidDeletion,omitempty" tf:"forbid_deletion,omitempty"`

	// (Map of String) :
	// :
	//
	// Labels associated with the resource.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (Attributes) :
	// +kubebuilder:validation:Optional
	Metadata *MetadataParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// (String) Human readable name for the resource.
	// Human readable name for the resource.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Identifier of the parent resource to which the resource belongs.
	// Identifier of the parent resource to which the resource belongs.
	// +kubebuilder:validation:Optional
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// (Number) Cannot be set alongside size_kibibytes, size_mebibytes or size_gibibytes.
	// *Cannot be set alongside size_kibibytes, size_mebibytes or size_gibibytes.*
	// +kubebuilder:validation:Optional
	SizeBytes *float64 `json:"sizeBytes,omitempty" tf:"size_bytes,omitempty"`

	// (Number) Cannot be set alongside size_bytes, size_kibibytes or size_mebibytes.
	// *Cannot be set alongside size_bytes, size_kibibytes or size_mebibytes.*
	// +kubebuilder:validation:Optional
	SizeGibibytes *float64 `json:"sizeGibibytes,omitempty" tf:"size_gibibytes,omitempty"`

	// (Number) Cannot be set alongside size_bytes, size_mebibytes or size_gibibytes.
	// *Cannot be set alongside size_bytes, size_mebibytes or size_gibibytes.*
	// +kubebuilder:validation:Optional
	SizeKibibytes *float64 `json:"sizeKibibytes,omitempty" tf:"size_kibibytes,omitempty"`

	// (Number) Cannot be set alongside size_bytes, size_kibibytes or size_gibibytes.
	// *Cannot be set alongside size_bytes, size_kibibytes or size_gibibytes.*
	// +kubebuilder:validation:Optional
	SizeMebibytes *float64 `json:"sizeMebibytes,omitempty" tf:"size_mebibytes,omitempty"`

	// (Attributes) Cannot be set alongside source_image_id. (see below for nested schema)
	// +kubebuilder:validation:Optional
	SourceImageFamily *SourceImageFamilyParameters `json:"sourceImageFamily,omitempty" tf:"source_image_family,omitempty"`

	// (String) Cannot be set alongside source_image_family.
	// *Cannot be set alongside source_image_family.*
	// +kubebuilder:validation:Optional
	SourceImageID *string `json:"sourceImageId,omitempty" tf:"source_image_id,omitempty"`

	// (String) :
	// :
	//
	// The type of disk defines the performance and reliability characteristics of the block device.
	// For details, see https://docs.nebius.com/compute/storage/types#disks-types
	//
	// #### Supported values
	//
	// the list of available types will be clarified later, it is not final version
	// Possible values:
	//
	// - `UNSPECIFIED`
	// - `NETWORK_SSD`
	// - `NETWORK_HDD`
	// - `NETWORK_SSD_NON_REPLICATED`
	// - `NETWORK_SSD_IO_M3`
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type LockStateInitParameters struct {
}

type LockStateObservation struct {

	// (List of String) :
	// :
	//
	// Disk is locked for deletion and for read-write operations while image is being created.
	// Here is the list of these images.
	Images []*string `json:"images,omitempty" tf:"images,omitempty"`
}

type LockStateParameters struct {
}

type MetadataInitParameters struct {
}

type MetadataObservation struct {
}

type MetadataParameters struct {
}

type SourceImageFamilyInitParameters struct {

	// (String)
	ImageFamily *string `json:"imageFamily,omitempty" tf:"image_family,omitempty"`

	// (String) Identifier of the parent resource to which the resource belongs.
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`
}

type SourceImageFamilyObservation struct {

	// (String)
	ImageFamily *string `json:"imageFamily,omitempty" tf:"image_family,omitempty"`

	// (String) Identifier of the parent resource to which the resource belongs.
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`
}

type SourceImageFamilyParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	ImageFamily *string `json:"imageFamily" tf:"image_family,omitempty"`

	// (String) Identifier of the parent resource to which the resource belongs.
	// +kubebuilder:validation:Optional
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`
}

type StatusInitParameters struct {
}

type StatusObservation struct {

	// (Number) :
	BlockSizeBytes *float64 `json:"blockSizeBytes,omitempty" tf:"block_size_bytes,omitempty"`

	// write. (see below for nested schema)
	LockState *LockStateObservation `json:"lockState,omitempty" tf:"lock_state,omitempty"`

	// (String) :
	// :
	//
	// Indicates whether the disk is deleted along with an instance.
	// Set only for disks declared in the instance spec.
	// If set, the value is the instance ID that manages this disk's lifecycle (the disk is deleted when that instance is deleted).
	// To change this value, update the instance specification (see AttachedDiskSpec.type).
	ManagedBy *string `json:"managedBy,omitempty" tf:"managed_by,omitempty"`

	// (List of String)
	ReadOnlyAttachments []*string `json:"readOnlyAttachments,omitempty" tf:"read_only_attachments,omitempty"`

	// (String) :
	// :
	//
	// Current read-write owner (instance ID).
	// May refer to an instance in any state, including stopped
	// (this semantics is preserved for backward compatibility).
	// Reassigned on disk detach, instance deletion, or ownership transfer.
	// Ownership transfer occurs when this disk is explicitly attached to another instance
	// or when a VM with this disk attached starts while the current owner is stopped.
	ReadWriteAttachment *string `json:"readWriteAttachment,omitempty" tf:"read_write_attachment,omitempty"`

	// (Boolean) Indicates whether there is an ongoing operation
	// Indicates whether there is an ongoing operation
	Reconciling *bool `json:"reconciling,omitempty" tf:"reconciling,omitempty"`

	// (Number) Cannot be set alongside size_kibibytes, size_mebibytes or size_gibibytes.
	SizeBytes *float64 `json:"sizeBytes,omitempty" tf:"size_bytes,omitempty"`

	// (String) :
	// :
	//
	// #### Supported values
	//
	// Possible values:
	//
	// - `SOURCE_IMAGE_CPU_UNSPECIFIED`
	// - `AMD64`
	// - `ARM64`
	SourceImageCPUArchitecture *string `json:"sourceImageCpuArchitecture,omitempty" tf:"source_image_cpu_architecture,omitempty"`

	// (String) Cannot be set alongside source_image_family.
	SourceImageID *string `json:"sourceImageId,omitempty" tf:"source_image_id,omitempty"`

	// (String) :
	// :
	//
	// #### Supported values
	//
	// Possible values:
	//
	// - `UNSPECIFIED`
	// - `CREATING`
	// - `READY`
	// - `UPDATING`
	// - `DELETING`
	// - `ERROR` - Indicates that error happened during disk creation, and the disk cannot be recovered.
	// - `BROKEN` - Indicates that an error has occurred during the disk's life cycle, and the disk is broken or unhealthy, but can still be recovered.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// (String)
	StateDescription *string `json:"stateDescription,omitempty" tf:"state_description,omitempty"`
}

type StatusParameters struct {
}

// DiskSpec defines the desired state of Disk
type DiskSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            DiskParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DiskInitParameters `json:"initProvider,omitempty"`
}

// DiskStatus defines the observed state of Disk.
type DiskStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DiskObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Disk is the Schema for the Disks API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,nebius}
type Disk struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   DiskSpec   `json:"spec"`
	Status DiskStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DiskList contains a list of Disks
type DiskList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Disk `json:"items"`
}

// Repository type metadata.
var (
	Disk_Kind             = "Disk"
	Disk_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Disk_Kind}.String()
	Disk_KindAPIVersion   = Disk_Kind + "." + CRDGroupVersion.String()
	Disk_GroupVersionKind = CRDGroupVersion.WithKind(Disk_Kind)
)

func init() {
	SchemeBuilder.Register(&Disk{}, &DiskList{})
}
