apiVersion: computev1.nebius.upbound.io/v1beta1
kind: Disk
metadata:
  annotations:
    meta.upbound.io/example-id: computev1/v1beta1/disk
  labels:
    testing.upbound.io/example-name: boot
  name: boot
spec:
  forProvider:
    name: ubuntu-boot-disk
    parentId: project-id
    sizeGibibytes: 64
    sourceImageFamily:
      imageFamily: ubuntu22.04
      parentId: project-id
    type: NETWORK_SSD
