apiVersion: iamv1.nebius.upbound.io/v1beta1
kind: FederatedCredentials
metadata:
  annotations:
    meta.upbound.io/example-id: iamv1/v1beta1/federatedcredentials
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    name: iamv1federatedcredentials
    parentId: ${data.nebius_project_id}
    # subject_id is the service account the federated subject impersonates.
    subjectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    # federated_subject_id is the external subject (the "sub" claim of the JWT).
    federatedSubjectId: repo:my-org/my-repo:ref:refs/heads/main
    oidcProvider:
      issuerUrl: https://token.actions.githubusercontent.com

---

apiVersion: iamv1.nebius.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  annotations:
    meta.upbound.io/example-id: iamv1/v1beta1/federatedcredentials
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    name: iamv1federatedcredentials
    parentId: ${data.nebius_project_id}
