// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type EgressInitParameters struct {

	// (List of String) :
	// :
	//
	// CIDR blocks as the destination.
	// Optional. Empty list means any address.
	// Must be a valid IPv4.
	// Maximum of 8 CIDRs can be specified.
	DestinationCidrs []*string `json:"destinationCidrs,omitempty" tf:"destination_cidrs,omitempty"`

	// (List of Number) :
	// :
	//
	// List of ports to which the rule applies.
	// Optional. Empty list means any port.
	// Valid range: 1–65535.
	// Maximum of 8 ports can be specified.
	DestinationPorts []*float64 `json:"destinationPorts,omitempty" tf:"destination_ports,omitempty"`

	// (String) ID of the referenced Security Group as the destination.
	// ID of the referenced Security Group as the destination.
	// +crossplane:generate:reference:type=github.com/upbound/provider-nebius/apis/cluster/vpc/v1beta1.SecurityGroup
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id",true)
	DestinationSecurityGroupID *string `json:"destinationSecurityGroupId,omitempty" tf:"destination_security_group_id,omitempty"`

	// Reference to a SecurityGroup in vpc to populate destinationSecurityGroupId.
	// +kubebuilder:validation:Optional
	DestinationSecurityGroupIDRef *v1.Reference `json:"destinationSecurityGroupIdRef,omitempty" tf:"-"`

	// Selector for a SecurityGroup in vpc to populate destinationSecurityGroupId.
	// +kubebuilder:validation:Optional
	DestinationSecurityGroupIDSelector *v1.Selector `json:"destinationSecurityGroupIdSelector,omitempty" tf:"-"`
}

type EgressObservation struct {

	// (List of String) :
	// :
	//
	// CIDR blocks as the destination.
	// Optional. Empty list means any address.
	// Must be a valid IPv4.
	// Maximum of 8 CIDRs can be specified.
	DestinationCidrs []*string `json:"destinationCidrs,omitempty" tf:"destination_cidrs,omitempty"`

	// (List of Number) :
	// :
	//
	// List of ports to which the rule applies.
	// Optional. Empty list means any port.
	// Valid range: 1–65535.
	// Maximum of 8 ports can be specified.
	DestinationPorts []*float64 `json:"destinationPorts,omitempty" tf:"destination_ports,omitempty"`

	// (String) ID of the referenced Security Group as the destination.
	// ID of the referenced Security Group as the destination.
	DestinationSecurityGroupID *string `json:"destinationSecurityGroupId,omitempty" tf:"destination_security_group_id,omitempty"`
}

type EgressParameters struct {

	// (List of String) :
	// :
	//
	// CIDR blocks as the destination.
	// Optional. Empty list means any address.
	// Must be a valid IPv4.
	// Maximum of 8 CIDRs can be specified.
	// +kubebuilder:validation:Optional
	DestinationCidrs []*string `json:"destinationCidrs,omitempty" tf:"destination_cidrs,omitempty"`

	// (List of Number) :
	// :
	//
	// List of ports to which the rule applies.
	// Optional. Empty list means any port.
	// Valid range: 1–65535.
	// Maximum of 8 ports can be specified.
	// +kubebuilder:validation:Optional
	DestinationPorts []*float64 `json:"destinationPorts,omitempty" tf:"destination_ports,omitempty"`

	// (String) ID of the referenced Security Group as the destination.
	// ID of the referenced Security Group as the destination.
	// +crossplane:generate:reference:type=github.com/upbound/provider-nebius/apis/cluster/vpc/v1beta1.SecurityGroup
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id",true)
	// +kubebuilder:validation:Optional
	DestinationSecurityGroupID *string `json:"destinationSecurityGroupId,omitempty" tf:"destination_security_group_id,omitempty"`

	// Reference to a SecurityGroup in vpc to populate destinationSecurityGroupId.
	// +kubebuilder:validation:Optional
	DestinationSecurityGroupIDRef *v1.Reference `json:"destinationSecurityGroupIdRef,omitempty" tf:"-"`

	// Selector for a SecurityGroup in vpc to populate destinationSecurityGroupId.
	// +kubebuilder:validation:Optional
	DestinationSecurityGroupIDSelector *v1.Selector `json:"destinationSecurityGroupIdSelector,omitempty" tf:"-"`
}

type IngressInitParameters struct {

	// (List of Number) :
	// :
	//
	// List of destination ports to which the rule applies.
	// Optional. Empty list means any port.
	// Valid range: 1–65535.
	// Maximum of 8 ports can be specified.
	DestinationPorts []*float64 `json:"destinationPorts,omitempty" tf:"destination_ports,omitempty"`

	// (List of String) :
	// :
	//
	// CIDR blocks as the source.
	// Optional. Empty list means any address.
	// Must be a valid IPv4
	// Maximum of 8 CIDRs can be specified.
	SourceCidrs []*string `json:"sourceCidrs,omitempty" tf:"source_cidrs,omitempty"`

	// (String) ID of the referenced Security Group as the source.
	// ID of the referenced Security Group as the source.
	// +crossplane:generate:reference:type=github.com/upbound/provider-nebius/apis/cluster/vpc/v1beta1.SecurityGroup
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id",true)
	SourceSecurityGroupID *string `json:"sourceSecurityGroupId,omitempty" tf:"source_security_group_id,omitempty"`

	// Reference to a SecurityGroup in vpc to populate sourceSecurityGroupId.
	// +kubebuilder:validation:Optional
	SourceSecurityGroupIDRef *v1.Reference `json:"sourceSecurityGroupIdRef,omitempty" tf:"-"`

	// Selector for a SecurityGroup in vpc to populate sourceSecurityGroupId.
	// +kubebuilder:validation:Optional
	SourceSecurityGroupIDSelector *v1.Selector `json:"sourceSecurityGroupIdSelector,omitempty" tf:"-"`
}

type IngressObservation struct {

	// (List of Number) :
	// :
	//
	// List of destination ports to which the rule applies.
	// Optional. Empty list means any port.
	// Valid range: 1–65535.
	// Maximum of 8 ports can be specified.
	DestinationPorts []*float64 `json:"destinationPorts,omitempty" tf:"destination_ports,omitempty"`

	// (List of String) :
	// :
	//
	// CIDR blocks as the source.
	// Optional. Empty list means any address.
	// Must be a valid IPv4
	// Maximum of 8 CIDRs can be specified.
	SourceCidrs []*string `json:"sourceCidrs,omitempty" tf:"source_cidrs,omitempty"`

	// (String) ID of the referenced Security Group as the source.
	// ID of the referenced Security Group as the source.
	SourceSecurityGroupID *string `json:"sourceSecurityGroupId,omitempty" tf:"source_security_group_id,omitempty"`
}

type IngressParameters struct {

	// (List of Number) :
	// :
	//
	// List of destination ports to which the rule applies.
	// Optional. Empty list means any port.
	// Valid range: 1–65535.
	// Maximum of 8 ports can be specified.
	// +kubebuilder:validation:Optional
	DestinationPorts []*float64 `json:"destinationPorts,omitempty" tf:"destination_ports,omitempty"`

	// (List of String) :
	// :
	//
	// CIDR blocks as the source.
	// Optional. Empty list means any address.
	// Must be a valid IPv4
	// Maximum of 8 CIDRs can be specified.
	// +kubebuilder:validation:Optional
	SourceCidrs []*string `json:"sourceCidrs,omitempty" tf:"source_cidrs,omitempty"`

	// (String) ID of the referenced Security Group as the source.
	// ID of the referenced Security Group as the source.
	// +crossplane:generate:reference:type=github.com/upbound/provider-nebius/apis/cluster/vpc/v1beta1.SecurityGroup
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id",true)
	// +kubebuilder:validation:Optional
	SourceSecurityGroupID *string `json:"sourceSecurityGroupId,omitempty" tf:"source_security_group_id,omitempty"`

	// Reference to a SecurityGroup in vpc to populate sourceSecurityGroupId.
	// +kubebuilder:validation:Optional
	SourceSecurityGroupIDRef *v1.Reference `json:"sourceSecurityGroupIdRef,omitempty" tf:"-"`

	// Selector for a SecurityGroup in vpc to populate sourceSecurityGroupId.
	// +kubebuilder:validation:Optional
	SourceSecurityGroupIDSelector *v1.Selector `json:"sourceSecurityGroupIdSelector,omitempty" tf:"-"`
}

type SecurityRuleInitParameters struct {

	// (String) :
	// :
	//
	// Access action for the rule.
	// Required. Determines whether matching traffic is allowed or denied.
	//
	// #### Supported values
	//
	// Access specifies action on matching traffic: ALLOW or DENY.
	// Possible values:
	//
	// - `ACCESS_UNSPECIFIED`
	// - `ALLOW`
	// - `DENY`
	Access *string `json:"access,omitempty" tf:"access,omitempty"`

	// (Attributes) :
	Egress *EgressInitParameters `json:"egress,omitempty" tf:"egress,omitempty"`

	// (Attributes) :
	Ingress *IngressInitParameters `json:"ingress,omitempty" tf:"ingress,omitempty"`

	// (Map of String) :
	// :
	//
	// Labels associated with the resource.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (Attributes) :
	Metadata *SecurityRuleMetadataInitParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// (String) Human readable name for the resource.
	// Human readable name for the resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Identifier of the parent resource to which the resource belongs.
	// Identifier of the parent resource to which the resource belongs.
	// +crossplane:generate:reference:type=github.com/upbound/provider-nebius/apis/cluster/vpc/v1beta1.SecurityGroup
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id",true)
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// Reference to a SecurityGroup in vpc to populate parentId.
	// +kubebuilder:validation:Optional
	ParentIDRef *v1.Reference `json:"parentIdRef,omitempty" tf:"-"`

	// Selector for a SecurityGroup in vpc to populate parentId.
	// +kubebuilder:validation:Optional
	ParentIDSelector *v1.Selector `json:"parentIdSelector,omitempty" tf:"-"`

	// (Number) :
	// :
	//
	// Priority of the rule. Valid range: 0-1000.
	// Optional. If not specified or set to 0, defaults to 500.
	// Rules are evaluated in priority order (lower numbers first) using a first-match algorithm:
	// only the first matching rule takes effect (ALLOW or DENY), and subsequent rules are skipped.
	//
	// When multiple rules share the same priority, DENY rules are evaluated before ALLOW rules.
	// The final evaluation order is reflected in 'effective_priority' (see SecurityRuleStatus).
	Priority *float64 `json:"priority,omitempty" tf:"priority,omitempty"`

	// (String) :
	// :
	//
	// Protocol used in the rule.
	// Supported values: ANY, TCP, UDP, ICMP.
	//
	// #### Supported values
	//
	// Protocol specifies traffic protocol.
	// Possible values:
	//
	// - `PROTOCOL_UNSPECIFIED`
	// - `ANY`
	// - `TCP`
	// - `UDP`
	// - `ICMP`
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// (String) :
	// :
	//
	// Type of the rule (STATEFUL or STATELESS)
	// Default value is STATEFUL
	//
	// #### Supported values
	//
	// RuleType specifies whether the security rule is stateful or stateless.
	// Possible values:
	//
	// - `RULE_TYPE_UNSPECIFIED`
	// - `STATEFUL`
	// - `STATELESS`
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type SecurityRuleMetadataInitParameters struct {
}

type SecurityRuleMetadataObservation struct {
}

type SecurityRuleMetadataParameters struct {
}

type SecurityRuleObservation struct {

	// (String) :
	// :
	//
	// Access action for the rule.
	// Required. Determines whether matching traffic is allowed or denied.
	//
	// #### Supported values
	//
	// Access specifies action on matching traffic: ALLOW or DENY.
	// Possible values:
	//
	// - `ACCESS_UNSPECIFIED`
	// - `ALLOW`
	// - `DENY`
	Access *string `json:"access,omitempty" tf:"access,omitempty"`

	// (String) :
	// :
	//
	// Timestamp indicating when the resource was created.
	//
	// A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (Attributes) :
	Egress *EgressObservation `json:"egress,omitempty" tf:"egress,omitempty"`

	// (String) Identifier for the resource, unique for its resource type.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Attributes) :
	Ingress *IngressObservation `json:"ingress,omitempty" tf:"ingress,omitempty"`

	// (Map of String) :
	// :
	//
	// Labels associated with the resource.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (Attributes) :
	Metadata *SecurityRuleMetadataParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// (String) Human readable name for the resource.
	// Human readable name for the resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Identifier of the parent resource to which the resource belongs.
	// Identifier of the parent resource to which the resource belongs.
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// (Number) :
	// :
	//
	// Priority of the rule. Valid range: 0-1000.
	// Optional. If not specified or set to 0, defaults to 500.
	// Rules are evaluated in priority order (lower numbers first) using a first-match algorithm:
	// only the first matching rule takes effect (ALLOW or DENY), and subsequent rules are skipped.
	//
	// When multiple rules share the same priority, DENY rules are evaluated before ALLOW rules.
	// The final evaluation order is reflected in 'effective_priority' (see SecurityRuleStatus).
	Priority *float64 `json:"priority,omitempty" tf:"priority,omitempty"`

	// (String) :
	// :
	//
	// Protocol used in the rule.
	// Supported values: ANY, TCP, UDP, ICMP.
	//
	// #### Supported values
	//
	// Protocol specifies traffic protocol.
	// Possible values:
	//
	// - `PROTOCOL_UNSPECIFIED`
	// - `ANY`
	// - `TCP`
	// - `UDP`
	// - `ICMP`
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// (Number) :
	// :
	//
	// Version of the resource for safe concurrent modifications and consistent reads.
	// Positive and monotonically increases on each resource spec change (but *not* on each change of the
	// resource's container(s) or status).
	// Service allows zero value or current.
	ResourceVersion *float64 `json:"resourceVersion,omitempty" tf:"resource_version,omitempty"`

	// (Attributes) Current status of the security rule. (see below for nested schema)
	Status *SecurityRuleStatusObservation `json:"status,omitempty" tf:"status,omitempty"`

	// (String) :
	// :
	//
	// Type of the rule (STATEFUL or STATELESS)
	// Default value is STATEFUL
	//
	// #### Supported values
	//
	// RuleType specifies whether the security rule is stateful or stateless.
	// Possible values:
	//
	// - `RULE_TYPE_UNSPECIFIED`
	// - `STATEFUL`
	// - `STATELESS`
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) :
	// :
	//
	// Timestamp indicating when the resource was last updated.
	//
	// A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type SecurityRuleParameters struct {

	// (String) :
	// :
	//
	// Access action for the rule.
	// Required. Determines whether matching traffic is allowed or denied.
	//
	// #### Supported values
	//
	// Access specifies action on matching traffic: ALLOW or DENY.
	// Possible values:
	//
	// - `ACCESS_UNSPECIFIED`
	// - `ALLOW`
	// - `DENY`
	// +kubebuilder:validation:Optional
	Access *string `json:"access,omitempty" tf:"access,omitempty"`

	// (Attributes) :
	// +kubebuilder:validation:Optional
	Egress *EgressParameters `json:"egress,omitempty" tf:"egress,omitempty"`

	// (Attributes) :
	// +kubebuilder:validation:Optional
	Ingress *IngressParameters `json:"ingress,omitempty" tf:"ingress,omitempty"`

	// (Map of String) :
	// :
	//
	// Labels associated with the resource.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (Attributes) :
	// +kubebuilder:validation:Optional
	Metadata *SecurityRuleMetadataParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// (String) Human readable name for the resource.
	// Human readable name for the resource.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Identifier of the parent resource to which the resource belongs.
	// Identifier of the parent resource to which the resource belongs.
	// +crossplane:generate:reference:type=github.com/upbound/provider-nebius/apis/cluster/vpc/v1beta1.SecurityGroup
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id",true)
	// +kubebuilder:validation:Optional
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// Reference to a SecurityGroup in vpc to populate parentId.
	// +kubebuilder:validation:Optional
	ParentIDRef *v1.Reference `json:"parentIdRef,omitempty" tf:"-"`

	// Selector for a SecurityGroup in vpc to populate parentId.
	// +kubebuilder:validation:Optional
	ParentIDSelector *v1.Selector `json:"parentIdSelector,omitempty" tf:"-"`

	// (Number) :
	// :
	//
	// Priority of the rule. Valid range: 0-1000.
	// Optional. If not specified or set to 0, defaults to 500.
	// Rules are evaluated in priority order (lower numbers first) using a first-match algorithm:
	// only the first matching rule takes effect (ALLOW or DENY), and subsequent rules are skipped.
	//
	// When multiple rules share the same priority, DENY rules are evaluated before ALLOW rules.
	// The final evaluation order is reflected in 'effective_priority' (see SecurityRuleStatus).
	// +kubebuilder:validation:Optional
	Priority *float64 `json:"priority,omitempty" tf:"priority,omitempty"`

	// (String) :
	// :
	//
	// Protocol used in the rule.
	// Supported values: ANY, TCP, UDP, ICMP.
	//
	// #### Supported values
	//
	// Protocol specifies traffic protocol.
	// Possible values:
	//
	// - `PROTOCOL_UNSPECIFIED`
	// - `ANY`
	// - `TCP`
	// - `UDP`
	// - `ICMP`
	// +kubebuilder:validation:Optional
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// (String) :
	// :
	//
	// Type of the rule (STATEFUL or STATELESS)
	// Default value is STATEFUL
	//
	// #### Supported values
	//
	// RuleType specifies whether the security rule is stateful or stateless.
	// Possible values:
	//
	// - `RULE_TYPE_UNSPECIFIED`
	// - `STATEFUL`
	// - `STATELESS`
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type SecurityRuleStatusInitParameters struct {
}

type SecurityRuleStatusObservation struct {

	// (Attributes) Destination of the traffic that matched the rule. (see below for nested schema)
	Destination *StatusDestinationObservation `json:"destination,omitempty" tf:"destination,omitempty"`

	// (String) :
	// :
	//
	// Direction of traffic affected by the rule.
	//
	// #### Supported values
	//
	// Direction specifies whether traffic is INGRESS (incoming) or EGRESS (outgoing).
	// Possible values:
	//
	// - `DIRECTION_UNSPECIFIED`
	// - `INGRESS`
	// - `EGRESS`
	Direction *string `json:"direction,omitempty" tf:"direction,omitempty"`

	// (Number) :
	// :
	//
	// Effective priority used for rule evaluation order, calculated by the system.
	// This value is computed from the user-specified 'priority' (SecurityRuleSpec).
	// Rules are evaluated in ascending order of effective_priority using a first-match algorithm.
	EffectivePriority *float64 `json:"effectivePriority,omitempty" tf:"effective_priority,omitempty"`

	// (Attributes) Source of the traffic that matched the rule. (see below for nested schema)
	Source *SourceObservation `json:"source,omitempty" tf:"source,omitempty"`

	// (String) :
	// :
	//
	// #### Supported values
	//
	// State describes lifecycle phases of a security rule.
	// Possible values:
	//
	// - `STATE_UNSPECIFIED`
	// - `CREATING`
	// - `READY`
	// - `DELETING`
	State *string `json:"state,omitempty" tf:"state,omitempty"`
}

type SecurityRuleStatusParameters struct {
}

type SourceInitParameters struct {
}

type SourceObservation struct {

	// (List of String) List of CIDR blocks.
	// List of CIDR blocks.
	Cidrs []*string `json:"cidrs,omitempty" tf:"cidrs,omitempty"`

	// (List of Number) List of ports.
	// List of ports.
	Ports []*float64 `json:"ports,omitempty" tf:"ports,omitempty"`

	// (String) ID of the Security Group.
	// ID of the Security Group.
	SecurityGroupID *string `json:"securityGroupId,omitempty" tf:"security_group_id,omitempty"`
}

type SourceParameters struct {
}

type StatusDestinationInitParameters struct {
}

type StatusDestinationObservation struct {

	// (List of String) List of CIDR blocks.
	// List of CIDR blocks.
	Cidrs []*string `json:"cidrs,omitempty" tf:"cidrs,omitempty"`

	// (List of Number) List of ports.
	// List of ports.
	Ports []*float64 `json:"ports,omitempty" tf:"ports,omitempty"`

	// (String) ID of the Security Group.
	// ID of the Security Group.
	SecurityGroupID *string `json:"securityGroupId,omitempty" tf:"security_group_id,omitempty"`
}

type StatusDestinationParameters struct {
}

// SecurityRuleSpec defines the desired state of SecurityRule
type SecurityRuleSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     SecurityRuleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SecurityRuleInitParameters `json:"initProvider,omitempty"`
}

// SecurityRuleStatus defines the observed state of SecurityRule.
type SecurityRuleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SecurityRuleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SecurityRule is the Schema for the SecurityRules API. SecurityRules define rules for controlling network traffic within a network. These rules specify when traffic is ALLOWED or DENIED based on direction, protocol, match source, and ports.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,nebius}
type SecurityRule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.access) || (has(self.initProvider) && has(self.initProvider.access))",message="spec.forProvider.access is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.protocol) || (has(self.initProvider) && has(self.initProvider.protocol))",message="spec.forProvider.protocol is a required parameter"
	Spec   SecurityRuleSpec   `json:"spec"`
	Status SecurityRuleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SecurityRuleList contains a list of SecurityRules
type SecurityRuleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SecurityRule `json:"items"`
}

// Repository type metadata.
var (
	SecurityRule_Kind             = "SecurityRule"
	SecurityRule_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SecurityRule_Kind}.String()
	SecurityRule_KindAPIVersion   = SecurityRule_Kind + "." + CRDGroupVersion.String()
	SecurityRule_GroupVersionKind = CRDGroupVersion.WithKind(SecurityRule_Kind)
)

func init() {
	SchemeBuilder.Register(&SecurityRule{}, &SecurityRuleList{})
}
