apiVersion: vpcv1.nebius.upbound.io/v1beta1
kind: Allocation
metadata:
  annotations:
    meta.upbound.io/example-id: vpcv1/v1beta1/allocation
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    name: vpcv1allocation
    ipv4Private:
      cidr: /32
      subnetIdSelector:
        matchLabels:
          testing.upbound.io/example-name: default
    parentId: ${data.nebius_project_id}

---

apiVersion: vpcv1.nebius.upbound.io/v1beta1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: vpcv1/v1beta1/allocation
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    ipv4PrivatePools:
      useNetworkPools: true
    name: vpcv1allocation
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    parentId: ${data.nebius_project_id}

---

apiVersion: vpcv1.nebius.upbound.io/v1beta1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: vpcv1/v1beta1/allocation
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    name: vpcv1allocation
    parentId: ${data.nebius_project_id}
