apiVersion: vpc.nebius.upbound.io/v1beta1
kind: Pool
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/pool
  labels:
    testing.upbound.io/example-name: vpc-v1beta1-pool
  name: private-ipv4-pool-child
spec:
  forProvider:
    cidrs:
    - cidr: 10.10.0.0/24
      maxMaskLength: 32
    name: private-ipv4-pool-child
    parentId: ${data.nebius_project_id}
    version: IPV4
    visibility: PRIVATE
    sourcePoolIdRef:
      name: private-ipv4-pool-parent
---
apiVersion: vpc.nebius.upbound.io/v1beta1
kind: Pool
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/pool
  labels:
    testing.upbound.io/example-name: vpc-v1beta1-pool
  name: private-ipv4-pool-parent
spec:
  forProvider:
    cidrs:
    - cidr: 10.10.0.0/16
      maxMaskLength: 32
    name: private-ipv4-pool-parent
    parentId: ${data.nebius_project_id}
    version: IPV4
    visibility: PRIVATE
