apiVersion: vpc.nebius.upbound.io/v1beta1
kind: RouteTable
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/routetable
  labels:
    testing.upbound.io/example-name: vpc-v1beta1-routetable
  name: vpcv1routetable
spec:
  forProvider:
    name: vpcv1routetable
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc-v1beta1-routetable
    parentId: ${data.nebius_project_id}

---

apiVersion: vpc.nebius.upbound.io/v1beta1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/routetable
  labels:
    testing.upbound.io/example-name: vpc-v1beta1-routetable
  name: vpcv1routetable
spec:
  forProvider:
    name: vpcv1routetable
    parentId: ${data.nebius_project_id}
