apiVersion: iamv1.nebius.m.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  annotations:
    meta.upbound.io/example-id: iamv1/v1beta1/serviceaccount
  labels:
    testing.upbound.io/example-name: terraform
  name: terraform
  namespace: upbound-system
spec:
  forProvider:
    description: Service account for Terraform automation
    name: terraform-sa
    parentId: project-id
