// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1beta1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this SecretVersion.
func (mg *SecretVersion) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ParentID),
		Extract:      resource.ExtractParamPath("id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ParentIDRef,
		Selector:     mg.Spec.ForProvider.ParentIDSelector,
		To: reference.To{
			List:    &SecretList{},
			Managed: &Secret{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ParentID")
	}
	mg.Spec.ForProvider.ParentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ParentIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ParentID),
		Extract:      resource.ExtractParamPath("id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ParentIDRef,
		Selector:     mg.Spec.InitProvider.ParentIDSelector,
		To: reference.To{
			List:    &SecretList{},
			Managed: &Secret{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ParentID")
	}
	mg.Spec.InitProvider.ParentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ParentIDRef = rsp.ResolvedReference

	return nil
}
