apiVersion: storage.nebius.upbound.io/v1beta1
kind: Inventory
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1beta1/inventory
  labels:
    testing.upbound.io/example-name: storage-v1beta1-inventory
  name: storagev1inventory
spec:
  forProvider:
    name: storagev1inventory
    # parentId is the (source) bucket whose contents get inventoried.
    parentIdRef:
      name: storagev1inventorysource
    destinationBucketIdRef:
      name: storagev1inventorydestination
    outputFormat: CSV_GZIP
    schedule: DAILY
    enabled: true

---

apiVersion: storage.nebius.upbound.io/v1beta1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1beta1/inventory
  labels:
    testing.upbound.io/example-name: storage-v1beta1-inventory
  name: storagev1inventorysource
spec:
  forProvider:
    name: storagev1inventorysource
    parentId: ${data.nebius_project_id}

---

apiVersion: storage.nebius.upbound.io/v1beta1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1beta1/inventory
  labels:
    testing.upbound.io/example-name: storage-v1beta1-inventory
  name: storagev1inventorydestination
spec:
  forProvider:
    name: storagev1inventorydestination
    parentId: ${data.nebius_project_id}
