apiVersion: iam.nebius.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1beta1/serviceaccount
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    description: Service account for E2E testing
    name: iamv1serviceaccount
    parentId: ${data.nebius_project_id}
