apiVersion: mysterybox.nebius.upbound.io/v1beta1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: mysterybox/v1beta1/secret
  labels:
    testing.upbound.io/example-name: mysterybox-v1beta1-secret
  name: mysteryboxv1secret
spec:
  forProvider:
    name: mysteryboxv1secret
    description: Application secret
    parentId: ${data.nebius_project_id}
