apiVersion: mysterybox.nebius.upbound.io/v1beta1
kind: SecretVersion
metadata:
  annotations:
    meta.upbound.io/example-id: mysterybox/v1beta1/secretversion
  labels:
    testing.upbound.io/example-name: mysterybox-v1beta1-secretversion
  name: default
spec:
  forProvider:
    parentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: mysterybox-v1beta1-secretversion
    payload:
      - key: password
        stringValueSecretRef:
          name: mysterybox-payload
          namespace: upbound-system
          key: payload-value
    setPrimary: true

---

apiVersion: mysterybox.nebius.upbound.io/v1beta1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: mysterybox/v1beta1/secretversion
  labels:
    testing.upbound.io/example-name: mysterybox-v1beta1-secretversion
  name: mysteryboxv1secretver
spec:
  forProvider:
    name: mysteryboxv1secretver
    parentId: ${data.nebius_project_id}

---

apiVersion: v1
kind: Secret
metadata:
  name: mysterybox-payload
  namespace: upbound-system
type: Opaque
stringData:
  payload-value: example-secret-value
