// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type FederationInitParameters struct {

	// Specifies if the federation in active state
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// Labels associated with the resource.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	Metadata *FederationMetadataInitParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// Human readable name for the resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Identifier of the parent resource to which the resource belongs.
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	SAMLSettings *SAMLSettingsInitParameters `json:"samlSettings,omitempty" tf:"saml_settings,omitempty"`

	// :
	//
	// If false, users with access to the federation cannot sign in automatically
	// and user accounts for them must be pre-created by a federation administrator.
	UserAccountAutoCreation *bool `json:"userAccountAutoCreation,omitempty" tf:"user_account_auto_creation,omitempty"`
}

type FederationMetadataInitParameters struct {
}

type FederationMetadataObservation struct {
}

type FederationMetadataParameters struct {
}

type FederationObservation struct {

	// Specifies if the federation in active state
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// :
	//
	// Timestamp indicating when the resource was created.
	//
	// A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Labels associated with the resource.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	Metadata *FederationMetadataParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// Human readable name for the resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Identifier of the parent resource to which the resource belongs.
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// :
	//
	// Version of the resource for safe concurrent modifications and consistent reads.
	// Positive and monotonically increases on each resource spec change (but *not* on each change of the
	// resource's container(s) or status).
	// Service allows zero value or current.
	ResourceVersion *float64 `json:"resourceVersion,omitempty" tf:"resource_version,omitempty"`

	SAMLSettings *SAMLSettingsObservation `json:"samlSettings,omitempty" tf:"saml_settings,omitempty"`

	Status *FederationStatusObservation `json:"status,omitempty" tf:"status,omitempty"`

	// :
	//
	// Timestamp indicating when the resource was last updated.
	//
	// A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`

	// :
	//
	// If false, users with access to the federation cannot sign in automatically
	// and user accounts for them must be pre-created by a federation administrator.
	UserAccountAutoCreation *bool `json:"userAccountAutoCreation,omitempty" tf:"user_account_auto_creation,omitempty"`
}

type FederationParameters struct {

	// Specifies if the federation in active state
	// +kubebuilder:validation:Optional
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// Labels associated with the resource.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// +kubebuilder:validation:Optional
	Metadata *FederationMetadataParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// Human readable name for the resource.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Identifier of the parent resource to which the resource belongs.
	// +kubebuilder:validation:Optional
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// +kubebuilder:validation:Optional
	SAMLSettings *SAMLSettingsParameters `json:"samlSettings,omitempty" tf:"saml_settings,omitempty"`

	// :
	//
	// If false, users with access to the federation cannot sign in automatically
	// and user accounts for them must be pre-created by a federation administrator.
	// +kubebuilder:validation:Optional
	UserAccountAutoCreation *bool `json:"userAccountAutoCreation,omitempty" tf:"user_account_auto_creation,omitempty"`
}

type FederationStatusInitParameters struct {
}

type FederationStatusObservation struct {

	// Number of certificates attached to the SAML federation for verifying SAML responses.
	CertificatesCount *float64 `json:"certificatesCount,omitempty" tf:"certificates_count,omitempty"`

	// :
	//
	// Federation state.
	//
	// #### Supported values
	//
	// Possible values:
	//
	// - `UNSPECIFIED`
	// - `ACTIVE`
	// - `INACTIVE`
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// Number of users registered in the IAM federation. This value may differ from the number of users in the identity provider.
	UsersCount *float64 `json:"usersCount,omitempty" tf:"users_count,omitempty"`
}

type FederationStatusParameters struct {
}

type SAMLSettingsInitParameters struct {

	// if "true", the identity provider MUST authenticate the presenter directly rather than rely on a previous security context.
	ForceAuthn *bool `json:"forceAuthn,omitempty" tf:"force_authn,omitempty"`

	// The unique identifier of the SAML Identity Provider. It usually matches the entityID from the IdP metadata.
	IdpIssuer *string `json:"idpIssuer,omitempty" tf:"idp_issuer,omitempty"`

	// Identity Provider’s Single Sign-On endpoint. This is the URL where the user is redirected to start SAML login.
	SsoURL *string `json:"ssoUrl,omitempty" tf:"sso_url,omitempty"`
}

type SAMLSettingsObservation struct {

	// if "true", the identity provider MUST authenticate the presenter directly rather than rely on a previous security context.
	ForceAuthn *bool `json:"forceAuthn,omitempty" tf:"force_authn,omitempty"`

	// The unique identifier of the SAML Identity Provider. It usually matches the entityID from the IdP metadata.
	IdpIssuer *string `json:"idpIssuer,omitempty" tf:"idp_issuer,omitempty"`

	// Identity Provider’s Single Sign-On endpoint. This is the URL where the user is redirected to start SAML login.
	SsoURL *string `json:"ssoUrl,omitempty" tf:"sso_url,omitempty"`
}

type SAMLSettingsParameters struct {

	// if "true", the identity provider MUST authenticate the presenter directly rather than rely on a previous security context.
	// +kubebuilder:validation:Optional
	ForceAuthn *bool `json:"forceAuthn,omitempty" tf:"force_authn,omitempty"`

	// The unique identifier of the SAML Identity Provider. It usually matches the entityID from the IdP metadata.
	// +kubebuilder:validation:Optional
	IdpIssuer *string `json:"idpIssuer,omitempty" tf:"idp_issuer,omitempty"`

	// Identity Provider’s Single Sign-On endpoint. This is the URL where the user is redirected to start SAML login.
	// +kubebuilder:validation:Optional
	SsoURL *string `json:"ssoUrl,omitempty" tf:"sso_url,omitempty"`
}

// FederationSpec defines the desired state of Federation
type FederationSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            FederationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FederationInitParameters `json:"initProvider,omitempty"`
}

// FederationStatus defines the observed state of Federation.
type FederationStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               FederationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Federation is the Schema for the Federations API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,nebius}
type Federation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.parentId) || (has(self.initProvider) && has(self.initProvider.parentId))",message="spec.forProvider.parentId is a required parameter"
	Spec   FederationSpec   `json:"spec"`
	Status FederationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FederationList contains a list of Federations
type FederationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Federation `json:"items"`
}

// Repository type metadata.
var (
	Federation_Kind             = "Federation"
	Federation_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Federation_Kind}.String()
	Federation_KindAPIVersion   = Federation_Kind + "." + CRDGroupVersion.String()
	Federation_GroupVersionKind = CRDGroupVersion.WithKind(Federation_Kind)
)

func init() {
	SchemeBuilder.Register(&Federation{}, &FederationList{})
}
