// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1beta1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this AccessKey.
func (mg *AccessKey) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	if mg.Spec.ForProvider.Account != nil {
		if mg.Spec.ForProvider.Account.ServiceAccount != nil {
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Account.ServiceAccount.ID),
				Extract:      resource.ExtractParamPath("id", true),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.Account.ServiceAccount.IDRef,
				Selector:     mg.Spec.ForProvider.Account.ServiceAccount.IDSelector,
				To: reference.To{
					List:    &ServiceAccountList{},
					Managed: &ServiceAccount{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.Account.ServiceAccount.ID")
			}
			mg.Spec.ForProvider.Account.ServiceAccount.ID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.Account.ServiceAccount.IDRef = rsp.ResolvedReference

		}
	}
	if mg.Spec.InitProvider.Account != nil {
		if mg.Spec.InitProvider.Account.ServiceAccount != nil {
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Account.ServiceAccount.ID),
				Extract:      resource.ExtractParamPath("id", true),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.Account.ServiceAccount.IDRef,
				Selector:     mg.Spec.InitProvider.Account.ServiceAccount.IDSelector,
				To: reference.To{
					List:    &ServiceAccountList{},
					Managed: &ServiceAccount{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.Account.ServiceAccount.ID")
			}
			mg.Spec.InitProvider.Account.ServiceAccount.ID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.Account.ServiceAccount.IDRef = rsp.ResolvedReference

		}
	}

	return nil
}

// ResolveReferences of this AccessPermit.
func (mg *AccessPermit) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ParentID),
		Extract:      resource.ExtractParamPath("id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ParentIDRef,
		Selector:     mg.Spec.ForProvider.ParentIDSelector,
		To: reference.To{
			List:    &GroupList{},
			Managed: &Group{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ParentID")
	}
	mg.Spec.ForProvider.ParentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ParentIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ParentID),
		Extract:      resource.ExtractParamPath("id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ParentIDRef,
		Selector:     mg.Spec.InitProvider.ParentIDSelector,
		To: reference.To{
			List:    &GroupList{},
			Managed: &Group{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ParentID")
	}
	mg.Spec.InitProvider.ParentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ParentIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this AuthPublicKey.
func (mg *AuthPublicKey) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	if mg.Spec.ForProvider.Account != nil {
		if mg.Spec.ForProvider.Account.ServiceAccount != nil {
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Account.ServiceAccount.ID),
				Extract:      resource.ExtractParamPath("id", true),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.Account.ServiceAccount.IDRef,
				Selector:     mg.Spec.ForProvider.Account.ServiceAccount.IDSelector,
				To: reference.To{
					List:    &ServiceAccountList{},
					Managed: &ServiceAccount{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.Account.ServiceAccount.ID")
			}
			mg.Spec.ForProvider.Account.ServiceAccount.ID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.Account.ServiceAccount.IDRef = rsp.ResolvedReference

		}
	}
	if mg.Spec.InitProvider.Account != nil {
		if mg.Spec.InitProvider.Account.ServiceAccount != nil {
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Account.ServiceAccount.ID),
				Extract:      resource.ExtractParamPath("id", true),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.Account.ServiceAccount.IDRef,
				Selector:     mg.Spec.InitProvider.Account.ServiceAccount.IDSelector,
				To: reference.To{
					List:    &ServiceAccountList{},
					Managed: &ServiceAccount{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.Account.ServiceAccount.ID")
			}
			mg.Spec.InitProvider.Account.ServiceAccount.ID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.Account.ServiceAccount.IDRef = rsp.ResolvedReference

		}
	}

	return nil
}

// ResolveReferences of this FederatedCredentials.
func (mg *FederatedCredentials) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SubjectID),
		Extract:      resource.ExtractParamPath("id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.SubjectIDRef,
		Selector:     mg.Spec.ForProvider.SubjectIDSelector,
		To: reference.To{
			List:    &ServiceAccountList{},
			Managed: &ServiceAccount{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SubjectID")
	}
	mg.Spec.ForProvider.SubjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SubjectIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SubjectID),
		Extract:      resource.ExtractParamPath("id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.SubjectIDRef,
		Selector:     mg.Spec.InitProvider.SubjectIDSelector,
		To: reference.To{
			List:    &ServiceAccountList{},
			Managed: &ServiceAccount{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.SubjectID")
	}
	mg.Spec.InitProvider.SubjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.SubjectIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this FederationCertificate.
func (mg *FederationCertificate) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ParentID),
		Extract:      resource.ExtractParamPath("id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ParentIDRef,
		Selector:     mg.Spec.ForProvider.ParentIDSelector,
		To: reference.To{
			List:    &FederationList{},
			Managed: &Federation{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ParentID")
	}
	mg.Spec.ForProvider.ParentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ParentIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ParentID),
		Extract:      resource.ExtractParamPath("id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ParentIDRef,
		Selector:     mg.Spec.InitProvider.ParentIDSelector,
		To: reference.To{
			List:    &FederationList{},
			Managed: &Federation{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ParentID")
	}
	mg.Spec.InitProvider.ParentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ParentIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this GroupMembership.
func (mg *GroupMembership) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.MemberID),
		Extract:      resource.ExtractParamPath("id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.MemberIDRef,
		Selector:     mg.Spec.ForProvider.MemberIDSelector,
		To: reference.To{
			List:    &ServiceAccountList{},
			Managed: &ServiceAccount{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.MemberID")
	}
	mg.Spec.ForProvider.MemberID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.MemberIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ParentID),
		Extract:      resource.ExtractParamPath("id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ParentIDRef,
		Selector:     mg.Spec.ForProvider.ParentIDSelector,
		To: reference.To{
			List:    &GroupList{},
			Managed: &Group{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ParentID")
	}
	mg.Spec.ForProvider.ParentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ParentIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.MemberID),
		Extract:      resource.ExtractParamPath("id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.MemberIDRef,
		Selector:     mg.Spec.InitProvider.MemberIDSelector,
		To: reference.To{
			List:    &ServiceAccountList{},
			Managed: &ServiceAccount{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.MemberID")
	}
	mg.Spec.InitProvider.MemberID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.MemberIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ParentID),
		Extract:      resource.ExtractParamPath("id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ParentIDRef,
		Selector:     mg.Spec.InitProvider.ParentIDSelector,
		To: reference.To{
			List:    &GroupList{},
			Managed: &Group{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ParentID")
	}
	mg.Spec.InitProvider.ParentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ParentIDRef = rsp.ResolvedReference

	return nil
}
