apiVersion: vpc.nebius.m.upbound.io/v1beta1
kind: Pool
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/pool
  labels:
    testing.upbound.io/example-name: private-with-source-pool-child
  name: private-child
  namespace: upbound-system
spec:
  forProvider:
    cidrs:
    - cidr: 10.10.0.0/24
      maxMaskLength: 32
    name: private-ipv4-pool-child
    parentId: ${data.nebius_project_id}
    version: IPV4
    visibility: PRIVATE
    sourcePoolIdSelector:
      matchLabels:
        testing.upbound.io/example-name: private-with-source-pool-parent
---
apiVersion: vpc.nebius.m.upbound.io/v1beta1
kind: Pool
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/pool
  labels:
    testing.upbound.io/example-name: private-with-source-pool-parent
  name: private-parent
  namespace: upbound-system
spec:
  forProvider:
    cidrs:
    - cidr: 10.10.0.0/16
      maxMaskLength: 32
    name: private-ipv4-pool-parent
    parentId: ${data.nebius_project_id}
    version: IPV4
    visibility: PRIVATE
