apiVersion: vpc.nebius.m.upbound.io/v1beta1
kind: Route
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/route
  labels:
    testing.upbound.io/example-name: default
  name: default
  namespace: upbound-system
spec:
  forProvider:
    name: vpcv1route
    destination:
      cidr: 0.0.0.0/0
    nextHop:
      defaultEgressGateway: true
    parentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default

---

apiVersion: vpc.nebius.m.upbound.io/v1beta1
kind: RouteTable
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/route
  labels:
    testing.upbound.io/example-name: default
  name: default
  namespace: upbound-system
spec:
  forProvider:
    name: vpcv1route
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    parentId: ${data.nebius_project_id}

---

apiVersion: vpc.nebius.m.upbound.io/v1beta1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/route
  labels:
    testing.upbound.io/example-name: default
  name: default
  namespace: upbound-system
spec:
  forProvider:
    name: vpcv1route
    parentId: ${data.nebius_project_id}
