apiVersion: computev1.nebius.m.upbound.io/v1beta1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: computev1/v1beta1/instance
  labels:
    testing.upbound.io/example-name: default
  name: default
  namespace: upbound-system
spec:
  forProvider:
    parentId: ${data.nebius_project_id}
    name: computev1instance
    resources:
      platform: cpu-d3
      preset: 4vcpu-16gb
    bootDisk:
      attachMode: READ_WRITE
      managedDisk:
        name: computev1instance-boot
        spec:
          type: NETWORK_SSD
          sizeGibibytes: 16
          sourceImageFamily:
            imageFamily: ubuntu24.04-driverless
    networkInterfaces:
      - name: eth0
        subnetIdSelector:
          matchLabels:
            testing.upbound.io/example-name: default
        ipAddress: {}

---

apiVersion: vpcv1.nebius.m.upbound.io/v1beta1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: computev1/v1beta1/instance
  labels:
    testing.upbound.io/example-name: default
  name: default
  namespace: upbound-system
spec:
  forProvider:
    ipv4PrivatePools:
      useNetworkPools: true
    name: computev1instance
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    parentId: ${data.nebius_project_id}

---

apiVersion: vpcv1.nebius.m.upbound.io/v1beta1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: computev1/v1beta1/instance
  labels:
    testing.upbound.io/example-name: default
  name: default
  namespace: upbound-system
spec:
  forProvider:
    name: computev1instance
    parentId: ${data.nebius_project_id}
