// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type AccessPermitInitParameters struct {

	// :
	//
	// Labels associated with the resource.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	Metadata *MetadataInitParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// Human readable name for the resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Identifier of the parent resource to which the resource belongs.
	// +crossplane:generate:reference:type=github.com/upbound/provider-nebius/apis/cluster/iam/v1beta1.Group
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id",true)
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// Reference to a Group in iam to populate parentId.
	// +kubebuilder:validation:Optional
	ParentIDRef *v1.Reference `json:"parentIdRef,omitempty" tf:"-"`

	// Selector for a Group in iam to populate parentId.
	// +kubebuilder:validation:Optional
	ParentIDSelector *v1.Selector `json:"parentIdSelector,omitempty" tf:"-"`

	// Resource for granting access permit.
	ResourceID *string `json:"resourceId,omitempty" tf:"resource_id,omitempty"`

	// Role for granting access permit.
	Role *string `json:"role,omitempty" tf:"role,omitempty"`
}

type AccessPermitObservation struct {

	// :
	//
	// Timestamp indicating when the resource was created.
	//
	// A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// :
	//
	// Labels associated with the resource.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	Metadata *MetadataParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// Human readable name for the resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Identifier of the parent resource to which the resource belongs.
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// Resource for granting access permit.
	ResourceID *string `json:"resourceId,omitempty" tf:"resource_id,omitempty"`

	// :
	//
	// Version of the resource for safe concurrent modifications and consistent reads.
	// Positive and monotonically increases on each resource spec change (but *not* on each change of the
	// resource's container(s) or status).
	// Service allows zero value or current.
	ResourceVersion *float64 `json:"resourceVersion,omitempty" tf:"resource_version,omitempty"`

	// Role for granting access permit.
	Role *string `json:"role,omitempty" tf:"role,omitempty"`

	Status *StatusObservation `json:"status,omitempty" tf:"status,omitempty"`

	// :
	//
	// Timestamp indicating when the resource was last updated.
	//
	// A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type AccessPermitParameters struct {

	// :
	//
	// Labels associated with the resource.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// +kubebuilder:validation:Optional
	Metadata *MetadataParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// Human readable name for the resource.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Identifier of the parent resource to which the resource belongs.
	// +crossplane:generate:reference:type=github.com/upbound/provider-nebius/apis/cluster/iam/v1beta1.Group
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id",true)
	// +kubebuilder:validation:Optional
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// Reference to a Group in iam to populate parentId.
	// +kubebuilder:validation:Optional
	ParentIDRef *v1.Reference `json:"parentIdRef,omitempty" tf:"-"`

	// Selector for a Group in iam to populate parentId.
	// +kubebuilder:validation:Optional
	ParentIDSelector *v1.Selector `json:"parentIdSelector,omitempty" tf:"-"`

	// Resource for granting access permit.
	// +kubebuilder:validation:Optional
	ResourceID *string `json:"resourceId,omitempty" tf:"resource_id,omitempty"`

	// Role for granting access permit.
	// +kubebuilder:validation:Optional
	Role *string `json:"role,omitempty" tf:"role,omitempty"`
}

type MetadataInitParameters struct {
}

type MetadataObservation struct {
}

type MetadataParameters struct {
}

type StatusInitParameters struct {
}

type StatusObservation struct {
}

type StatusParameters struct {
}

// AccessPermitSpec defines the desired state of AccessPermit
type AccessPermitSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AccessPermitParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AccessPermitInitParameters `json:"initProvider,omitempty"`
}

// AccessPermitStatus defines the observed state of AccessPermit.
type AccessPermitStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AccessPermitObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AccessPermit is the Schema for the AccessPermits API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,nebius}
type AccessPermit struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              AccessPermitSpec   `json:"spec"`
	Status            AccessPermitStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccessPermitList contains a list of AccessPermits
type AccessPermitList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccessPermit `json:"items"`
}

// Repository type metadata.
var (
	AccessPermit_Kind             = "AccessPermit"
	AccessPermit_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AccessPermit_Kind}.String()
	AccessPermit_KindAPIVersion   = AccessPermit_Kind + "." + CRDGroupVersion.String()
	AccessPermit_GroupVersionKind = CRDGroupVersion.WithKind(AccessPermit_Kind)
)

func init() {
	SchemeBuilder.Register(&AccessPermit{}, &AccessPermitList{})
}
