// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type GroupInitParameters struct {

	// Labels associated with the resource.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	Metadata *GroupMetadataInitParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// Human readable name for the resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Identifier of the parent resource to which the resource belongs.
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`
}

type GroupMetadataInitParameters struct {
}

type GroupMetadataObservation struct {
}

type GroupMetadataParameters struct {
}

type GroupObservation struct {

	// :
	//
	// Timestamp indicating when the resource was created.
	//
	// A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Labels associated with the resource.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	Metadata *GroupMetadataParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// Human readable name for the resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Identifier of the parent resource to which the resource belongs.
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// :
	//
	// Version of the resource for safe concurrent modifications and consistent reads.
	// Positive and monotonically increases on each resource spec change (but *not* on each change of the
	// resource's container(s) or status).
	// Service allows zero value or current.
	ResourceVersion *float64 `json:"resourceVersion,omitempty" tf:"resource_version,omitempty"`

	Status *GroupStatusObservation `json:"status,omitempty" tf:"status,omitempty"`

	// :
	//
	// Timestamp indicating when the resource was last updated.
	//
	// A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type GroupParameters struct {

	// Labels associated with the resource.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// +kubebuilder:validation:Optional
	Metadata *GroupMetadataParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// Human readable name for the resource.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Identifier of the parent resource to which the resource belongs.
	// +kubebuilder:validation:Optional
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`
}

type GroupStatusInitParameters struct {
}

type GroupStatusObservation struct {
	MembersCount *float64 `json:"membersCount,omitempty" tf:"members_count,omitempty"`

	ServiceAccountsCount *float64 `json:"serviceAccountsCount,omitempty" tf:"service_accounts_count,omitempty"`

	// :
	//
	// #### Supported values
	//
	// Possible values:
	//
	// - `UNSPECIFIED`
	// - `ACTIVE`
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	TenantUserAccountsCount *float64 `json:"tenantUserAccountsCount,omitempty" tf:"tenant_user_accounts_count,omitempty"`
}

type GroupStatusParameters struct {
}

// GroupSpec defines the desired state of Group
type GroupSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   GroupParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider GroupInitParameters `json:"initProvider,omitempty"`
}

// GroupStatus defines the observed state of Group.
type GroupStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               GroupObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Group is the Schema for the Groups API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,nebius}
type Group struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.parentId) || (has(self.initProvider) && has(self.initProvider.parentId))",message="spec.forProvider.parentId is a required parameter"
	Spec   GroupSpec   `json:"spec"`
	Status GroupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GroupList contains a list of Groups
type GroupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Group `json:"items"`
}

// Repository type metadata.
var (
	Group_Kind             = "Group"
	Group_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Group_Kind}.String()
	Group_KindAPIVersion   = Group_Kind + "." + CRDGroupVersion.String()
	Group_GroupVersionKind = CRDGroupVersion.WithKind(Group_Kind)
)

func init() {
	SchemeBuilder.Register(&Group{}, &GroupList{})
}
