// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

// Package cluster contains Kubernetes API for the provider.
package cluster

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1beta1 "github.com/upbound/provider-nebius/apis/cluster/computev1/v1beta1"
	v1beta1dnsv1 "github.com/upbound/provider-nebius/apis/cluster/dnsv1/v1beta1"
	v1beta1iamv1 "github.com/upbound/provider-nebius/apis/cluster/iamv1/v1beta1"
	v1beta1iamv2 "github.com/upbound/provider-nebius/apis/cluster/iamv2/v1beta1"
	v1beta1kmsv1 "github.com/upbound/provider-nebius/apis/cluster/kmsv1/v1beta1"
	v1beta1mk8sv1 "github.com/upbound/provider-nebius/apis/cluster/mk8sv1/v1beta1"
	v1beta1mysteryboxv1 "github.com/upbound/provider-nebius/apis/cluster/mysteryboxv1/v1beta1"
	v1beta1quotasv1 "github.com/upbound/provider-nebius/apis/cluster/quotasv1/v1beta1"
	v1beta1registryv1 "github.com/upbound/provider-nebius/apis/cluster/registryv1/v1beta1"
	v1beta1storagev1 "github.com/upbound/provider-nebius/apis/cluster/storagev1/v1beta1"
	v1alpha1 "github.com/upbound/provider-nebius/apis/cluster/v1alpha1"
	v1beta1cluster "github.com/upbound/provider-nebius/apis/cluster/v1beta1"
	v1beta1vpcv1 "github.com/upbound/provider-nebius/apis/cluster/vpcv1/v1beta1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1beta1.SchemeBuilder.AddToScheme,
		v1beta1dnsv1.SchemeBuilder.AddToScheme,
		v1beta1iamv1.SchemeBuilder.AddToScheme,
		v1beta1iamv2.SchemeBuilder.AddToScheme,
		v1beta1kmsv1.SchemeBuilder.AddToScheme,
		v1beta1mk8sv1.SchemeBuilder.AddToScheme,
		v1beta1mysteryboxv1.SchemeBuilder.AddToScheme,
		v1beta1quotasv1.SchemeBuilder.AddToScheme,
		v1beta1registryv1.SchemeBuilder.AddToScheme,
		v1beta1storagev1.SchemeBuilder.AddToScheme,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1beta1cluster.SchemeBuilder.AddToScheme,
		v1beta1vpcv1.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
