apiVersion: storagev1.nebius.m.upbound.io/v1beta1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: storagev1/v1beta1/bucket
  labels:
    testing.upbound.io/example-name: state
  name: state
  namespace: upbound-system
spec:
  forProvider:
    defaultStorageClass: STANDARD
    name: terraform-state-bucket
    parentId: project-id
    versioningPolicy: ENABLED
