// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1beta1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	errors "github.com/pkg/errors"
	v1beta11 "github.com/upbound/provider-nebius/apis/cluster/iamv1/v1beta1"
	v1beta1 "github.com/upbound/provider-nebius/apis/cluster/vpcv1/v1beta1"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Instance.
func (mg *Instance) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	if mg.Spec.ForProvider.BootDisk != nil {
		if mg.Spec.ForProvider.BootDisk.ExistingDisk != nil {
			rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.BootDisk.ExistingDisk.ID),
				Extract:      resource.ExtractParamPath("id", true),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.BootDisk.ExistingDisk.IDRef,
				Selector:     mg.Spec.ForProvider.BootDisk.ExistingDisk.IDSelector,
				To: reference.To{
					List:    &DiskList{},
					Managed: &Disk{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.BootDisk.ExistingDisk.ID")
			}
			mg.Spec.ForProvider.BootDisk.ExistingDisk.ID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.BootDisk.ExistingDisk.IDRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.Filesystems); i3++ {
		if mg.Spec.ForProvider.Filesystems[i3].ExistingFilesystem != nil {
			rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Filesystems[i3].ExistingFilesystem.ID),
				Extract:      resource.ExtractParamPath("id", true),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.Filesystems[i3].ExistingFilesystem.IDRef,
				Selector:     mg.Spec.ForProvider.Filesystems[i3].ExistingFilesystem.IDSelector,
				To: reference.To{
					List:    &FilesystemList{},
					Managed: &Filesystem{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.Filesystems[i3].ExistingFilesystem.ID")
			}
			mg.Spec.ForProvider.Filesystems[i3].ExistingFilesystem.ID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.Filesystems[i3].ExistingFilesystem.IDRef = rsp.ResolvedReference

		}
	}
	if mg.Spec.ForProvider.GpuCluster != nil {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.GpuCluster.ID),
			Extract:      resource.ExtractParamPath("id", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.GpuCluster.IDRef,
			Selector:     mg.Spec.ForProvider.GpuCluster.IDSelector,
			To: reference.To{
				List:    &GpuClusterList{},
				Managed: &GpuCluster{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.GpuCluster.ID")
		}
		mg.Spec.ForProvider.GpuCluster.ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.GpuCluster.IDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.NetworkInterfaces); i3++ {
		for i4 := 0; i4 < len(mg.Spec.ForProvider.NetworkInterfaces[i3].SecurityGroups); i4++ {
			rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.NetworkInterfaces[i3].SecurityGroups[i4].ID),
				Extract:      resource.ExtractParamPath("id", true),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.NetworkInterfaces[i3].SecurityGroups[i4].IDRef,
				Selector:     mg.Spec.ForProvider.NetworkInterfaces[i3].SecurityGroups[i4].IDSelector,
				To: reference.To{
					List:    &v1beta1.SecurityGroupList{},
					Managed: &v1beta1.SecurityGroup{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.NetworkInterfaces[i3].SecurityGroups[i4].ID")
			}
			mg.Spec.ForProvider.NetworkInterfaces[i3].SecurityGroups[i4].ID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.NetworkInterfaces[i3].SecurityGroups[i4].IDRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.NetworkInterfaces); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.NetworkInterfaces[i3].SubnetID),
			Extract:      resource.ExtractParamPath("id", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.NetworkInterfaces[i3].SubnetIDRef,
			Selector:     mg.Spec.ForProvider.NetworkInterfaces[i3].SubnetIDSelector,
			To: reference.To{
				List:    &v1beta1.SubnetList{},
				Managed: &v1beta1.Subnet{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.NetworkInterfaces[i3].SubnetID")
		}
		mg.Spec.ForProvider.NetworkInterfaces[i3].SubnetID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.NetworkInterfaces[i3].SubnetIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.SecondaryDisks); i3++ {
		if mg.Spec.ForProvider.SecondaryDisks[i3].ExistingDisk != nil {
			rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SecondaryDisks[i3].ExistingDisk.ID),
				Extract:      resource.ExtractParamPath("id", true),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.SecondaryDisks[i3].ExistingDisk.IDRef,
				Selector:     mg.Spec.ForProvider.SecondaryDisks[i3].ExistingDisk.IDSelector,
				To: reference.To{
					List:    &DiskList{},
					Managed: &Disk{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.SecondaryDisks[i3].ExistingDisk.ID")
			}
			mg.Spec.ForProvider.SecondaryDisks[i3].ExistingDisk.ID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.SecondaryDisks[i3].ExistingDisk.IDRef = rsp.ResolvedReference

		}
	}
	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ServiceAccountID),
		Extract:      resource.ExtractParamPath("id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ServiceAccountIDRef,
		Selector:     mg.Spec.ForProvider.ServiceAccountIDSelector,
		To: reference.To{
			List:    &v1beta11.ServiceAccountList{},
			Managed: &v1beta11.ServiceAccount{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ServiceAccountID")
	}
	mg.Spec.ForProvider.ServiceAccountID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ServiceAccountIDRef = rsp.ResolvedReference

	if mg.Spec.InitProvider.BootDisk != nil {
		if mg.Spec.InitProvider.BootDisk.ExistingDisk != nil {
			rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.BootDisk.ExistingDisk.ID),
				Extract:      resource.ExtractParamPath("id", true),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.BootDisk.ExistingDisk.IDRef,
				Selector:     mg.Spec.InitProvider.BootDisk.ExistingDisk.IDSelector,
				To: reference.To{
					List:    &DiskList{},
					Managed: &Disk{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.BootDisk.ExistingDisk.ID")
			}
			mg.Spec.InitProvider.BootDisk.ExistingDisk.ID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.BootDisk.ExistingDisk.IDRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.Filesystems); i3++ {
		if mg.Spec.InitProvider.Filesystems[i3].ExistingFilesystem != nil {
			rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Filesystems[i3].ExistingFilesystem.ID),
				Extract:      resource.ExtractParamPath("id", true),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.Filesystems[i3].ExistingFilesystem.IDRef,
				Selector:     mg.Spec.InitProvider.Filesystems[i3].ExistingFilesystem.IDSelector,
				To: reference.To{
					List:    &FilesystemList{},
					Managed: &Filesystem{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.Filesystems[i3].ExistingFilesystem.ID")
			}
			mg.Spec.InitProvider.Filesystems[i3].ExistingFilesystem.ID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.Filesystems[i3].ExistingFilesystem.IDRef = rsp.ResolvedReference

		}
	}
	if mg.Spec.InitProvider.GpuCluster != nil {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.GpuCluster.ID),
			Extract:      resource.ExtractParamPath("id", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.GpuCluster.IDRef,
			Selector:     mg.Spec.InitProvider.GpuCluster.IDSelector,
			To: reference.To{
				List:    &GpuClusterList{},
				Managed: &GpuCluster{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.GpuCluster.ID")
		}
		mg.Spec.InitProvider.GpuCluster.ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.GpuCluster.IDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.NetworkInterfaces); i3++ {
		for i4 := 0; i4 < len(mg.Spec.InitProvider.NetworkInterfaces[i3].SecurityGroups); i4++ {
			rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.NetworkInterfaces[i3].SecurityGroups[i4].ID),
				Extract:      resource.ExtractParamPath("id", true),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.NetworkInterfaces[i3].SecurityGroups[i4].IDRef,
				Selector:     mg.Spec.InitProvider.NetworkInterfaces[i3].SecurityGroups[i4].IDSelector,
				To: reference.To{
					List:    &v1beta1.SecurityGroupList{},
					Managed: &v1beta1.SecurityGroup{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.NetworkInterfaces[i3].SecurityGroups[i4].ID")
			}
			mg.Spec.InitProvider.NetworkInterfaces[i3].SecurityGroups[i4].ID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.NetworkInterfaces[i3].SecurityGroups[i4].IDRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.NetworkInterfaces); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.NetworkInterfaces[i3].SubnetID),
			Extract:      resource.ExtractParamPath("id", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.NetworkInterfaces[i3].SubnetIDRef,
			Selector:     mg.Spec.InitProvider.NetworkInterfaces[i3].SubnetIDSelector,
			To: reference.To{
				List:    &v1beta1.SubnetList{},
				Managed: &v1beta1.Subnet{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.NetworkInterfaces[i3].SubnetID")
		}
		mg.Spec.InitProvider.NetworkInterfaces[i3].SubnetID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.NetworkInterfaces[i3].SubnetIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.SecondaryDisks); i3++ {
		if mg.Spec.InitProvider.SecondaryDisks[i3].ExistingDisk != nil {
			rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SecondaryDisks[i3].ExistingDisk.ID),
				Extract:      resource.ExtractParamPath("id", true),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.SecondaryDisks[i3].ExistingDisk.IDRef,
				Selector:     mg.Spec.InitProvider.SecondaryDisks[i3].ExistingDisk.IDSelector,
				To: reference.To{
					List:    &DiskList{},
					Managed: &Disk{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.SecondaryDisks[i3].ExistingDisk.ID")
			}
			mg.Spec.InitProvider.SecondaryDisks[i3].ExistingDisk.ID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.SecondaryDisks[i3].ExistingDisk.IDRef = rsp.ResolvedReference

		}
	}
	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ServiceAccountID),
		Extract:      resource.ExtractParamPath("id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ServiceAccountIDRef,
		Selector:     mg.Spec.InitProvider.ServiceAccountIDSelector,
		To: reference.To{
			List:    &v1beta11.ServiceAccountList{},
			Managed: &v1beta11.ServiceAccount{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ServiceAccountID")
	}
	mg.Spec.InitProvider.ServiceAccountID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ServiceAccountIDRef = rsp.ResolvedReference

	return nil
}
