apiVersion: iam.nebius.m.upbound.io/v1beta1
kind: GroupMembership
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1beta1/groupmembership
  labels:
    testing.upbound.io/example-name: iam-v1beta1-groupmembership
  name: iamv1groupmembership
  namespace: upbound-system
spec:
  forProvider:
    parentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: iam-v1beta1-groupmembership
    memberIdSelector:
      matchLabels:
        testing.upbound.io/example-name: iam-v1beta1-groupmembership

---

apiVersion: iam.nebius.m.upbound.io/v1beta1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1beta1/groupmembership
  labels:
    testing.upbound.io/example-name: iam-v1beta1-groupmembership
  name: iamv1groupmembership
  namespace: upbound-system
spec:
  forProvider:
    name: iamv1groupmembership
    parentId: ${data.nebius_tenant_id}

---

apiVersion: iam.nebius.m.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1beta1/groupmembership
  labels:
    testing.upbound.io/example-name: iam-v1beta1-groupmembership
  name: iamv1groupmembership
  namespace: upbound-system
spec:
  forProvider:
    name: iamv1groupmembership
    parentId: ${data.nebius_project_id}
