apiVersion: storagev1.nebius.upbound.io/v1beta1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: storagev1/v1beta1/bucket
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    name: storagev1bucket
    parentId: ${data.nebius_project_id}
    defaultStorageClass: STANDARD
    versioningPolicy: ENABLED
