apiVersion: compute.nebius.upbound.io/v1beta1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/instance
  labels:
    testing.upbound.io/example-name: vm
  name: vm
spec:
  forProvider:
    bootDisk:
      attachMode: READ_WRITE
      managedDisk:
        name: example-vm-boot
        spec:
          sizeGibibytes: 64
          sourceImageFamily:
            imageFamily: ubuntu22.04
            parentId: project-id
          type: NETWORK_SSD
    name: example-vm
    networkInterfaces:
    - ipAddress:
        allocationId: private-allocation-id
      name: eth0
      subnetIdSelector:
        matchLabels:
          testing.upbound.io/example-name: example
    parentId: project-id
    resources:
      platform: cpu-e2
      preset: 2vcpu-8gb
