// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type FederatedCredentialsInitParameters struct {

	// :
	//
	// Federated subject ID. For oidc_provider, the subject is calculated from the
	// "sub" claim of the federated JWT token.
	FederatedSubjectID *string `json:"federatedSubjectId,omitempty" tf:"federated_subject_id,omitempty"`

	// :
	//
	// Labels associated with the resource.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	Metadata *FederatedCredentialsMetadataInitParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// Human readable name for the resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	OidcProvider *OidcProviderInitParameters `json:"oidcProvider,omitempty" tf:"oidc_provider,omitempty"`

	// Identifier of the parent resource to which the resource belongs.
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// IAM subject (service account) that the federated subject impersonates.
	// +crossplane:generate:reference:type=github.com/upbound/provider-nebius/apis/cluster/iamv1/v1beta1.ServiceAccount
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id",true)
	SubjectID *string `json:"subjectId,omitempty" tf:"subject_id,omitempty"`

	// Reference to a ServiceAccount in iamv1 to populate subjectId.
	// +kubebuilder:validation:Optional
	SubjectIDRef *v1.Reference `json:"subjectIdRef,omitempty" tf:"-"`

	// Selector for a ServiceAccount in iamv1 to populate subjectId.
	// +kubebuilder:validation:Optional
	SubjectIDSelector *v1.Selector `json:"subjectIdSelector,omitempty" tf:"-"`
}

type FederatedCredentialsMetadataInitParameters struct {
}

type FederatedCredentialsMetadataObservation struct {
}

type FederatedCredentialsMetadataParameters struct {
}

type FederatedCredentialsObservation struct {

	// :
	//
	// Timestamp indicating when the resource was created.
	//
	// A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// :
	//
	// Federated subject ID. For oidc_provider, the subject is calculated from the
	// "sub" claim of the federated JWT token.
	FederatedSubjectID *string `json:"federatedSubjectId,omitempty" tf:"federated_subject_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// :
	//
	// Labels associated with the resource.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	Metadata *FederatedCredentialsMetadataParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// Human readable name for the resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	OidcProvider *OidcProviderObservation `json:"oidcProvider,omitempty" tf:"oidc_provider,omitempty"`

	// Identifier of the parent resource to which the resource belongs.
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// :
	//
	// Version of the resource for safe concurrent modifications and consistent reads.
	// Positive and monotonically increases on each resource spec change (but *not* on each change of the
	// resource's container(s) or status).
	// Service allows zero value or current.
	ResourceVersion *float64 `json:"resourceVersion,omitempty" tf:"resource_version,omitempty"`

	Status *FederatedCredentialsStatusObservation `json:"status,omitempty" tf:"status,omitempty"`

	// IAM subject (service account) that the federated subject impersonates.
	SubjectID *string `json:"subjectId,omitempty" tf:"subject_id,omitempty"`

	// :
	//
	// Timestamp indicating when the resource was last updated.
	//
	// A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type FederatedCredentialsParameters struct {

	// :
	//
	// Federated subject ID. For oidc_provider, the subject is calculated from the
	// "sub" claim of the federated JWT token.
	// +kubebuilder:validation:Optional
	FederatedSubjectID *string `json:"federatedSubjectId,omitempty" tf:"federated_subject_id,omitempty"`

	// :
	//
	// Labels associated with the resource.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// +kubebuilder:validation:Optional
	Metadata *FederatedCredentialsMetadataParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// Human readable name for the resource.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// +kubebuilder:validation:Optional
	OidcProvider *OidcProviderParameters `json:"oidcProvider,omitempty" tf:"oidc_provider,omitempty"`

	// Identifier of the parent resource to which the resource belongs.
	// +kubebuilder:validation:Optional
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// IAM subject (service account) that the federated subject impersonates.
	// +crossplane:generate:reference:type=github.com/upbound/provider-nebius/apis/cluster/iamv1/v1beta1.ServiceAccount
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id",true)
	// +kubebuilder:validation:Optional
	SubjectID *string `json:"subjectId,omitempty" tf:"subject_id,omitempty"`

	// Reference to a ServiceAccount in iamv1 to populate subjectId.
	// +kubebuilder:validation:Optional
	SubjectIDRef *v1.Reference `json:"subjectIdRef,omitempty" tf:"-"`

	// Selector for a ServiceAccount in iamv1 to populate subjectId.
	// +kubebuilder:validation:Optional
	SubjectIDSelector *v1.Selector `json:"subjectIdSelector,omitempty" tf:"-"`
}

type FederatedCredentialsStatusInitParameters struct {
}

type FederatedCredentialsStatusObservation struct {
}

type FederatedCredentialsStatusParameters struct {
}

type OidcProviderInitParameters struct {

	// OIDC-compatible JWT issuer URL.
	IssuerURL *string `json:"issuerUrl,omitempty" tf:"issuer_url,omitempty"`

	// :
	//
	// JSON representation of a JSON Web Key Set (JWKS) with public keys used for
	// JWT signature verification.
	// If set, the token service uses this JWKS to verify token signatures.
	JwkSetJSON *string `json:"jwkSetJson,omitempty" tf:"jwk_set_json,omitempty"`
}

type OidcProviderObservation struct {

	// OIDC-compatible JWT issuer URL.
	IssuerURL *string `json:"issuerUrl,omitempty" tf:"issuer_url,omitempty"`

	// :
	//
	// JSON representation of a JSON Web Key Set (JWKS) with public keys used for
	// JWT signature verification.
	// If set, the token service uses this JWKS to verify token signatures.
	JwkSetJSON *string `json:"jwkSetJson,omitempty" tf:"jwk_set_json,omitempty"`
}

type OidcProviderParameters struct {

	// OIDC-compatible JWT issuer URL.
	// +kubebuilder:validation:Optional
	IssuerURL *string `json:"issuerUrl" tf:"issuer_url,omitempty"`

	// :
	//
	// JSON representation of a JSON Web Key Set (JWKS) with public keys used for
	// JWT signature verification.
	// If set, the token service uses this JWKS to verify token signatures.
	// +kubebuilder:validation:Optional
	JwkSetJSON *string `json:"jwkSetJson,omitempty" tf:"jwk_set_json,omitempty"`
}

// FederatedCredentialsSpec defines the desired state of FederatedCredentials
type FederatedCredentialsSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     FederatedCredentialsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FederatedCredentialsInitParameters `json:"initProvider,omitempty"`
}

// FederatedCredentialsStatus defines the observed state of FederatedCredentials.
type FederatedCredentialsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        FederatedCredentialsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// FederatedCredentials is the Schema for the FederatedCredentialss API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,nebius}
type FederatedCredentials struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.parentId) || (has(self.initProvider) && has(self.initProvider.parentId))",message="spec.forProvider.parentId is a required parameter"
	Spec   FederatedCredentialsSpec   `json:"spec"`
	Status FederatedCredentialsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FederatedCredentialsList contains a list of FederatedCredentialss
type FederatedCredentialsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []FederatedCredentials `json:"items"`
}

// Repository type metadata.
var (
	FederatedCredentials_Kind             = "FederatedCredentials"
	FederatedCredentials_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: FederatedCredentials_Kind}.String()
	FederatedCredentials_KindAPIVersion   = FederatedCredentials_Kind + "." + CRDGroupVersion.String()
	FederatedCredentials_GroupVersionKind = CRDGroupVersion.WithKind(FederatedCredentials_Kind)
)

func init() {
	SchemeBuilder.Register(&FederatedCredentials{}, &FederatedCredentialsList{})
}
