apiVersion: mysteryboxv1.nebius.upbound.io/v1beta1
kind: SecretVersion
metadata:
  annotations:
    meta.upbound.io/example-id: mysteryboxv1/v1beta1/secretversion
  labels:
    testing.upbound.io/example-name: current
  name: current
spec:
  forProvider:
    name: current
    parentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: app
    sensitive:
      payload:
      - key: password
        string_value: ${var.secret_value}
      version: "1"
    setPrimary: true

---

apiVersion: mysteryboxv1.nebius.upbound.io/v1beta1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: mysteryboxv1/v1beta1/secretversion
  labels:
    testing.upbound.io/example-name: app
  name: app
spec:
  forProvider:
    name: app-secret
    parentId: project-id
