apiVersion: quotas.nebius.m.upbound.io/v1beta1
kind: QuotaAllowance
metadata:
  annotations:
    meta.upbound.io/example-id: quotas/v1beta1/quotaallowance
  labels:
    testing.upbound.io/example-name: bucket_count
  name: bucket-count
  namespace: upbound-system
spec:
  forProvider:
    limit: 20
    name: storage.bucket.count
    parentId: project-id
