// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1beta1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	errors "github.com/pkg/errors"
	v1beta1 "github.com/upbound/provider-nebius/apis/cluster/iamv1/v1beta1"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this AccessKey.
func (mg *AccessKey) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	if mg.Spec.ForProvider.Account != nil {
		if mg.Spec.ForProvider.Account.ServiceAccount != nil {
			rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Account.ServiceAccount.ID),
				Extract:      resource.ExtractParamPath("id", true),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.Account.ServiceAccount.IDRef,
				Selector:     mg.Spec.ForProvider.Account.ServiceAccount.IDSelector,
				To: reference.To{
					List:    &v1beta1.ServiceAccountList{},
					Managed: &v1beta1.ServiceAccount{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.Account.ServiceAccount.ID")
			}
			mg.Spec.ForProvider.Account.ServiceAccount.ID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.Account.ServiceAccount.IDRef = rsp.ResolvedReference

		}
	}
	if mg.Spec.InitProvider.Account != nil {
		if mg.Spec.InitProvider.Account.ServiceAccount != nil {
			rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Account.ServiceAccount.ID),
				Extract:      resource.ExtractParamPath("id", true),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.Account.ServiceAccount.IDRef,
				Selector:     mg.Spec.InitProvider.Account.ServiceAccount.IDSelector,
				To: reference.To{
					List:    &v1beta1.ServiceAccountList{},
					Managed: &v1beta1.ServiceAccount{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.Account.ServiceAccount.ID")
			}
			mg.Spec.InitProvider.Account.ServiceAccount.ID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.Account.ServiceAccount.IDRef = rsp.ResolvedReference

		}
	}

	return nil
}
