apiVersion: kms.nebius.upbound.io/v1beta1
kind: SymmetricKey
metadata:
  annotations:
    meta.upbound.io/example-id: kms/v1beta1/symmetrickey
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    parentId: ${data.nebius_project_id}
    name: kmsv1symmetrickey
    algorithm: AES_256
    rotationPeriod: 8760h
