apiVersion: iamv1.nebius.m.upbound.io/v1beta1
kind: AccessPermit
metadata:
  annotations:
    meta.upbound.io/example-id: iamv1/v1beta1/accesspermit
  labels:
    testing.upbound.io/example-name: default
  name: default
  namespace: upbound-system
spec:
  forProvider:
    # parent_id is the group the role is granted to.
    parentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    # resource_id is the resource the role applies to.
    resourceId: ${data.nebius_project_id}
    # role is the IAM role granted to the group on the resource.
    role: viewer

---

apiVersion: iamv1.nebius.m.upbound.io/v1beta1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: iamv1/v1beta1/accesspermit
  labels:
    testing.upbound.io/example-name: default
  name: default
  namespace: upbound-system
spec:
  forProvider:
    name: iamv1accesspermit
    parentId: ${data.nebius_tenant_id}
